[package]
name = "mox-ai-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
mox-platform-foundation = { path = "../../foundation/mox-platform-foundation" }
mox-ai-core = { path = "../../core/ai/mox-ai-core" }
serde = { workspace = true }
validator = { workspace = true }

[dev-dependencies]



