<!-- Generated by Trae Work -->
<!-- MOX AI 指挥中心 · 用户出思路，AI多跑腿 · 黄金比例设计 -->
<template>
  <div class="ai-command-center">
    <!-- 左侧：助手 & 会话侧边栏 -->
    <div class="ai-sidebar" :class="{ collapsed: sidebarCollapsed }">
      <div class="ai-sidebar-header">
        <div class="ai-logo">
          <div class="ai-logo-icon">
            <el-icon><Cpu /></el-icon>
          </div>
          <span v-if="!sidebarCollapsed" class="ai-logo-text">AI 指挥中心</span>
        </div>
        <el-button class="collapse-btn" text @click="sidebarCollapsed = !sidebarCollapsed">
          <el-icon><component :is="sidebarCollapsed ? 'Expand' : 'Fold'" /></el-icon>
        </el-button>
      </div>

      <!-- 当前助手卡片 -->
      <div class="current-assistant-card" @click="showAssistantPanel = true">
        <div class="assistant-avatar-mini" :style="{ background: currentAssistantObj.gradient }">
          <span>{{ currentAssistantObj.emoji }}</span>
        </div>
        <div v-if="!sidebarCollapsed" class="assistant-meta">
          <div class="assistant-name-mini">{{ currentAssistantObj.name }}</div>
          <div class="assistant-status">
            <span class="status-dot online"></span>
            在线待命
          </div>
        </div>
        <el-icon v-if="!sidebarCollapsed" class="switch-icon"><ArrowRight /></el-icon>
      </div>

      <!-- 新建任务按钮 -->
      <div class="ai-new-chat">
        <el-button type="primary" class="new-task-btn" @click="newSession">
          <el-icon><Plus /></el-icon>
          <span v-if="!sidebarCollapsed">新建任务</span>
        </el-button>
      </div>

      <!-- 会话列表 -->
      <div class="ai-session-list" v-if="!sidebarCollapsed">
        <div class="session-group">
          <div class="session-group-title">进行中</div>
          <div
            v-for="s in activeSessions"
            :key="s.id"
            class="session-item"
            :class="{ active: s.id === currentSession }"
            @click="selectSession(s.id)"
          >
            <div class="session-icon-wrap" :class="s.status">
              <el-icon v-if="s.status === 'running'" class="spin"><Loading /></el-icon>
              <el-icon v-else-if="s.status === 'done'"><CircleCheck /></el-icon>
              <el-icon v-else><ChatDotRound /></el-icon>
            </div>
            <div class="session-info">
              <span class="session-title">{{ s.title }}</span>
              <span class="session-sub">{{ s.subtitle }}</span>
            </div>
          </div>
        </div>
        <div class="session-group" v-if="completedSessions.length">
          <div class="session-group-title">已完成</div>
          <div
            v-for="s in completedSessions"
            :key="s.id"
            class="session-item"
            :class="{ active: s.id === currentSession }"
            @click="selectSession(s.id)"
          >
            <div class="session-icon-wrap done">
              <el-icon><CircleCheck /></el-icon>
            </div>
            <div class="session-info">
              <span class="session-title">{{ s.title }}</span>
              <span class="session-sub">{{ s.subtitle }}</span>
            </div>
          </div>
        </div>
      </div>

      <div class="ai-sidebar-footer">
        <div class="user-card">
          <div class="user-avatar">
            <el-icon><User /></el-icon>
          </div>
          <div v-if="!sidebarCollapsed" class="user-info">
            <div class="user-name">指挥者</div>
            <div class="user-role">出思路 · 定方向</div>
          </div>
        </div>
      </div>
    </div>

    <!-- 中间：主工作区 -->
    <div class="ai-main">
      <!-- 顶部状态栏 -->
      <div class="ai-topbar">
        <div class="topbar-left">
          <el-button text class="mobile-menu-btn" @click="mobileSidebar = !mobileSidebar">
            <el-icon><Menu /></el-icon>
          </el-button>
          <div class="current-task-title">
            <span v-if="messages.length === 0">新任务 · 等待你的指令</span>
            <span v-else>{{ currentTaskTitle }}</span>
          </div>
        </div>
        <div class="topbar-right">
          <el-tag v-if="taskRunning" type="primary" effect="light" class="task-status-tag">
            <el-icon class="spin"><Loading /></el-icon>
            AI 执行中
          </el-tag>
          <el-tooltip content="切换主题">
            <el-button text class="icon-btn" @click.stop="showThemePanel = !showThemePanel">
              <el-icon><Brush /></el-icon>
            </el-button>
          </el-tooltip>
        </div>
      </div>

      <!-- 空状态：AI 能力中心欢迎页 -->
      <div v-if="messages.length === 0" class="ai-welcome">
        <div class="welcome-hero">
          <div class="hero-orb orb-1"></div>
          <div class="hero-orb orb-2"></div>
          <div class="hero-orb orb-3"></div>

          <div class="hero-content">
            <div class="hero-badge">
              <el-icon><MagicStick /></el-icon>
              AI Agent 指挥中心
            </div>
            <h1 class="hero-title">
              你出思路，<span class="gradient-text">AI 跑腿</span>
            </h1>
            <p class="hero-subtitle">
              描述你想要的结果，AI 将自动拆解任务、调用工具、执行落地
            </p>
          </div>
        </div>

        <!-- AI 能帮你做什么 -->
        <div class="capability-section">
          <div class="section-label">AI 能帮你做什么</div>
          <div class="capability-grid">
            <div
              class="capability-card"
              v-for="(cap, i) in capabilities"
              :key="i"
              @click="sendSuggestion(cap.prompt)"
            >
              <div class="cap-icon" :style="{ background: cap.bg }">
                <span>{{ cap.icon }}</span>
              </div>
              <div class="cap-title">{{ cap.title }}</div>
              <div class="cap-desc">{{ cap.desc }}</div>
              <div class="cap-tags">
                <span v-for="(t, j) in cap.tags" :key="j" class="cap-tag">{{ t }}</span>
              </div>
            </div>
          </div>
        </div>

        <!-- 快捷指令 -->
        <div class="quick-section">
          <div class="section-label">快捷指令</div>
          <div class="quick-chips">
            <el-tag
              v-for="(q, i) in quickCommands"
              :key="i"
              size="large"
              effect="plain"
              class="quick-chip"
              @click="sendSuggestion(q)"
            >
              {{ q }}
            </el-tag>
          </div>
        </div>

        <!-- 底部输入框 -->
        <div class="welcome-input">
          <div class="chat-input-wrap welcome-input-wrap">
            <div class="input-prefix">
              <el-icon><Promotion /></el-icon>
            </div>
            <el-input
              v-model="inputText"
              type="textarea"
              :rows="1"
              :autosize="{ minRows: 1, maxRows: 6 }"
              placeholder="描述你的目标，让 AI 帮你跑腿实现…"
              resize="none"
              class="chat-input"
              @keydown.enter.exact.prevent="sendMessage"
            />
            <div class="input-suffix">
              <el-tooltip content="上传文件">
                <el-button text class="icon-btn-sm">
                  <el-icon><Paperclip /></el-icon>
                </el-button>
              </el-tooltip>
              <el-tooltip content="语音输入">
                <el-button text class="icon-btn-sm">
                  <el-icon><Microphone /></el-icon>
                </el-button>
              </el-tooltip>
              <el-button
                type="primary"
                class="send-btn"
                @click="sendMessage"
                :disabled="!inputText.trim()"
              >
                开始执行
              </el-button>
            </div>
          </div>
          <div class="input-tips">
            💡 试试「帮我设计一个知识图谱系统，从需求到架构」
          </div>
        </div>
      </div>

      <!-- 对话执行状态 -->
      <div v-else class="ai-chat">
        <div class="chat-messages" ref="messagesRef">
          <div
            v-for="msg in messages"
            :key="msg.id"
            class="message-row"
            :class="msg.role"
          >
            <!-- AI 头像 -->
            <div v-if="msg.role === 'assistant'" class="msg-avatar ai">
              <span class="avatar-emoji">{{ currentAssistantObj.emoji }}</span>
            </div>

            <div class="msg-content">
              <div v-if="msg.role === 'assistant'" class="msg-sender">
                {{ currentAssistantObj.name }}
                <el-tag size="small" type="primary" effect="plain" class="sender-tag">AI 助手</el-tag>
              </div>

              <!-- 用户消息气泡 -->
              <div v-if="msg.role === 'user'" class="msg-bubble user-bubble">
                {{ msg.content }}
              </div>

              <!-- AI 消息：任务执行可视化 -->
              <div v-else-if="msg.type === 'task'" class="msg-bubble ai-bubble no-pad">
                <AgentTaskRunner
                  :title="msg.taskTitle"
                  :status="msg.taskStatus"
                  :steps="msg.taskSteps"
                />
              </div>

              <!-- AI 消息：文本回复 -->
              <div v-else class="msg-bubble ai-bubble">
                <div class="ai-msg-body" v-html="formatMarkdown(msg.content)"></div>
              </div>

              <!-- 消息操作 -->
              <div v-if="msg.role === 'assistant' && msg.type !== 'task'" class="msg-actions">
                <el-button text size="small" @click="copyMsg(msg.content)">
                  <el-icon><CopyDocument /></el-icon> 复制
                </el-button>
                <el-button text size="small" @click="regenerate(msg)">
                  <el-icon><Refresh /></el-icon> 重新生成
                </el-button>
                <el-button text size="small" type="primary" @click="continueTask(msg)">
                  <el-icon><Right /></el-icon> 继续深入
                </el-button>
              </div>
            </div>

            <!-- 用户头像 -->
            <div v-if="msg.role === 'user'" class="msg-avatar user">
              <el-icon><User /></el-icon>
            </div>
          </div>

          <!-- 正在输入 -->
          <div v-if="isTyping && !taskRunning" class="message-row assistant">
            <div class="msg-avatar ai">
              <span class="avatar-emoji">{{ currentAssistantObj.emoji }}</span>
            </div>
            <div class="msg-content">
              <div class="msg-bubble ai-bubble typing-bubble">
                <span class="typing-dot"></span>
                <span class="typing-dot"></span>
                <span class="typing-dot"></span>
              </div>
            </div>
          </div>
        </div>

        <!-- 对话底部输入框 -->
        <div class="chat-bottom">
          <div class="chat-input-wrap">
            <div class="input-prefix">
              <el-tooltip content="选择工具">
                <el-button text class="icon-btn-sm">
                  <el-icon><Tools /></el-icon>
                </el-button>
              </el-tooltip>
            </div>
            <el-input
              v-model="inputText"
              type="textarea"
              :rows="1"
              :autosize="{ minRows: 1, maxRows: 6 }"
              placeholder="继续指令…  / 切换助手  ·  # 引用  ·  @ 工具"
              resize="none"
              class="chat-input"
              @keydown.enter.exact.prevent="sendMessage"
            />
            <div class="input-suffix">
              <el-tooltip content="上传附件">
                <el-button text class="icon-btn-sm">
                  <el-icon><Paperclip /></el-icon>
                </el-button>
              </el-tooltip>
              <el-button
                type="primary"
                class="send-btn"
                @click="sendMessage"
                :disabled="!inputText.trim()"
              >
                <el-icon><Promotion /></el-icon>
              </el-button>
            </div>
          </div>
          <div class="chat-bottom-tip">
            AI 生成的内容仅供参考 · 按 Enter 发送，Shift + Enter 换行
          </div>
        </div>
      </div>
    </div>

    <!-- 右侧：Agent 处理流程图 + 代码/DSL 双视图面板（对话联动 · 不切 TAB） -->
    <AgentFlowPanel :agents="flowAgents" v-model="flowPanelVisible" />

    <!-- 右侧：助手选择面板（抽屉式） -->
    <div class="assistant-panel" :class="{ open: showAssistantPanel }">
      <div class="panel-overlay" @click="showAssistantPanel = false"></div>
      <div class="panel-content">
        <div class="panel-header">
          <div class="panel-title">选择 AI 助手</div>
          <el-button text @click="showAssistantPanel = false">
            <el-icon><Close /></el-icon>
          </el-button>
        </div>
        <AssistantSelector v-model="currentAssistant" @change="onAssistantChange" />
      </div>
    </div>

    <!-- 主题切换面板 -->
    <div v-if="showThemePanel" class="theme-panel-popover" @click.stop>
      <div class="theme-panel-title">选择主题</div>
      <div class="theme-options">
        <div
          v-for="t in themeOptions"
          :key="t.key"
          class="theme-option"
          :class="{ active: currentTheme === t.key }"
          @click="switchTheme(t.key)"
        >
          <div class="theme-preview" :style="{ background: t.preview }"></div>
          <span class="theme-name">{{ t.name }}</span>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, nextTick, onMounted, onUnmounted } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import {
  Cpu, Expand, Fold, Plus, ChatDotRound, Loading, CircleCheck,
  User, Menu, Brush, MagicStick, Promotion, Paperclip, Microphone,
  Tools, CopyDocument, Refresh, Right, Close, ArrowRight
} from '@element-plus/icons-vue'
import { ElMessage } from 'element-plus'
import AgentTaskRunner from '@/components/AgentTaskRunner.vue'
import AgentFlowPanel from '@/components/AgentFlowPanel.vue'
import AssistantSelector from '@/components/AssistantSelector.vue'
import { useTheme } from '@/composables/useTheme'

const route = useRoute()
const router = useRouter()
const { theme, setTheme } = useTheme()

/* ===== 状态 ===== */
const sidebarCollapsed = ref(false)
const mobileSidebar = ref(false)
const showAssistantPanel = ref(false)
const showThemePanel = ref(false)
const flowPanelVisible = ref(true)
const flowAgents = ref([])
const inputText = ref('')
const currentSession = ref('s1')
const isTyping = ref(false)
const taskRunning = ref(false)
const messagesRef = ref(null)

/* ===== 当前 AI 助手 ===== */
const currentAssistant = ref('general')
const assistants = {
  architect: { name: '架构师小智', emoji: '🏗️', gradient: 'linear-gradient(135deg, #6366f1, #8b5cf6)' },
  analyst: { name: '分析师小研', emoji: '📊', gradient: 'linear-gradient(135deg, #06b6d4, #0ea5e9)' },
  data: { name: '数据工程师小数', emoji: '🔗', gradient: 'linear-gradient(135deg, #10b981, #059669)' },
  product: { name: '产品经理小策', emoji: '💡', gradient: 'linear-gradient(135deg, #f59e0b, #f97316)' },
  devops: { name: '运维工程师小运', emoji: '⚙️', gradient: 'linear-gradient(135deg, #ef4444, #dc2626)' },
  general: { name: '全能助手小通', emoji: '✨', gradient: 'linear-gradient(135deg, #ec4899, #8b5cf6)' }
}
const currentAssistantObj = computed(() => assistants[currentAssistant.value] || assistants.general)

/* ===== 会话列表 ===== */
const sessions = ref([
  { id: 's1', title: '知识图谱系统设计', subtitle: '架构师小智 · 5 步', status: 'running', date: 'today' },
  { id: 's2', title: '竞品分析报告', subtitle: '分析师小研 · 完成', status: 'done', date: 'today' },
  { id: 's3', title: '数据治理方案', subtitle: '数据工程师小数 · 完成', status: 'done', date: 'yesterday' },
  { id: 's4', title: 'CI/CD 流水线设计', subtitle: '运维工程师小运 · 完成', status: 'done', date: 'earlier' }
])

const activeSessions = computed(() => sessions.value.filter(s => s.status === 'running'))
const completedSessions = computed(() => sessions.value.filter(s => s.status === 'done'))

/* ===== AI 能力卡片 · 黄金比例 6 宫格 ===== */
const capabilities = ref([
  {
    icon: '🏗️', title: '系统架构设计',
    desc: '从需求到技术栈选型，输出完整架构方案',
    tags: ['架构图', '技术选型', '性能评估'],
    bg: 'linear-gradient(135deg, #6366f1, #8b5cf6)',
    prompt: '帮我设计一个企业级知识图谱系统的技术架构，从数据层到应用层，给出完整的技术选型建议和架构图说明。'
  },
  {
    icon: '📋', title: '需求全维分析',
    desc: '自动拆解业务需求，输出结构化需求文档',
    tags: ['需求拆解', '优先级', '用例设计'],
    bg: 'linear-gradient(135deg, #06b6d4, #0ea5e9)',
    prompt: '帮我做一个知识图谱项目的全维需求分析，包括功能需求、非功能需求、约束条件，并给出优先级排序。'
  },
  {
    icon: '🔗', title: '图谱 Schema 设计',
    desc: '根据业务场景设计实体关系模型',
    tags: ['实体建模', '关系定义', '属性设计'],
    bg: 'linear-gradient(135deg, #10b981, #059669)',
    prompt: '帮我设计一个企业知识图谱的 Schema 模型，包括核心实体、关系和属性，给出设计理由和最佳实践。'
  },
  {
    icon: '📊', title: '数据分析报告',
    desc: '自动抓取数据、分析洞察、生成报告',
    tags: ['数据采集', '可视化', '洞察结论'],
    bg: 'linear-gradient(135deg, #f59e0b, #f97316)',
    prompt: '帮我分析当前知识图谱领域的技术趋势，生成一份包含主流技术栈、市场格局和发展方向的分析报告。'
  },
  {
    icon: '🧪', title: '方案评审优化',
    desc: '多维度评审技术方案，发现潜在问题',
    tags: ['技术评审', '风险识别', '优化建议'],
    bg: 'linear-gradient(135deg, #ec4899, #f472b6)',
    prompt: '作为技术评审专家，请帮我评审一个微服务架构设计方案，从性能、安全、可维护性等维度给出评估和优化建议。'
  },
  {
    icon: '⚡', title: '工作流自动化',
    desc: '编排多步任务，AI 自动执行并交付结果',
    tags: ['任务编排', '自动执行', '结果交付'],
    bg: 'linear-gradient(135deg, #8b5cf6, #6366f1)',
    prompt: '帮我设计一个从数据采集、清洗、建模到入库的完整知识图谱数据处理工作流，并给出每一步的工具和脚本建议。'
  }
])

/* ===== 快捷指令 ===== */
const quickCommands = ref([
  '帮我写一份产品 PRD',
  '设计一个微服务架构',
  '生成数据库 ER 图',
  '做竞品对比分析',
  '写技术方案文档',
  '代码 Review 建议'
])

/* ===== 主题切换 ===== */
const currentTheme = computed(() => theme.value)
const themeOptions = [
  { key: 'light', name: '浅色深空', preview: 'linear-gradient(135deg, #f6f8fc, #e0e7ff)' },
  { key: 'dark', name: '暗黑模式', preview: 'linear-gradient(135deg, #0a0e1a, #1e293b)' },
  { key: 'sky', name: '天蓝科技', preview: 'linear-gradient(135deg, #0ea5e9, #06b6d4)' },
  { key: 'cyberpunk', name: '赛博朋克', preview: 'linear-gradient(135deg, #00d4ff, #b14aff)' }
]

function switchTheme(key) {
  setTheme(key)
  showThemePanel.value = false
}

/* ===== 消息 ===== */
const messages = ref([])

const currentTaskTitle = computed(() => {
  const firstUserMsg = messages.value.find(m => m.role === 'user')
  if (firstUserMsg) {
    return firstUserMsg.content.slice(0, 30) + (firstUserMsg.content.length > 30 ? '…' : '')
  }
  return '新任务'
})

/* ===== 方法 ===== */
function newSession() {
  const id = 's' + Date.now()
  sessions.value.unshift({
    id, title: '新任务', subtitle: '等待指令',
    status: 'running', date: 'today'
  })
  currentSession.value = id
  messages.value = []
}

function selectSession(id) {
  currentSession.value = id
  const session = sessions.value.find(s => s.id === id)
  if (session && session.status === 'done') {
    messages.value = [
      { id: 1, role: 'user', content: session.title },
      { id: 2, role: 'assistant', content: '任务已完成！以下是执行结果摘要：\n\n## ✅ 执行成果\n\n**需求分析** - 已完成，输出 3 大类 15 项需求\n**架构设计** - 已完成，四层架构 + 技术选型\n**图谱建模** - 已完成，8 个核心实体 + 12 种关系\n\n需要我重新执行或深入某个方向吗？' }
    ]
  } else {
    messages.value = []
  }
  scrollToBottom()
}

function sendSuggestion(prompt) {
  inputText.value = prompt
  sendMessage()
}

function sendMessage() {
  const text = inputText.value.trim()
  if (!text) return

  const session = sessions.value.find(s => s.id === currentSession.value)
  if (session && messages.value.length === 0) {
    session.title = text.slice(0, 20) + (text.length > 20 ? '…' : '')
    session.subtitle = currentAssistantObj.value.name + ' · 执行中'
  }

  messages.value.push({ id: Date.now(), role: 'user', content: text })
  inputText.value = ''
  scrollToBottom()

  taskRunning.value = true
  isTyping.value = true

  setTimeout(() => {
    isTyping.value = false
    const taskMsg = {
      id: Date.now() + 1,
      role: 'assistant',
      type: 'task',
      taskTitle: '正在执行：' + text.slice(0, 30) + (text.length > 30 ? '…' : ''),
      taskStatus: 'running',
      taskSteps: generateTaskSteps(text)
    }
    messages.value.push(taskMsg)
    const reactiveMsg = messages.value[messages.value.length - 1]
    // 同步到右侧 Agent 流程图面板
    flowAgents.value = taskMsg.taskSteps.map((s, i) => ({
      id: 'agent-' + i,
      name: s.title,
      role: s.tool || 'Agent',
      emoji: AGENT_EMOJIS[i % AGENT_EMOJIS.length],
      gradient: AGENT_GRADIENTS[i % AGENT_GRADIENTS.length],
      status: s.status === 'done' ? 'done' : (s.status === 'running' ? 'running' : 'pending'),
      desc: s.detail || '',
      result: s.result || ''
    }))
    scrollToBottom()
    animateTaskSteps(reactiveMsg)
  }, 800)
}

function generateTaskSteps(text) {
  const steps = [
    { title: '理解需求', status: 'running', tool: 'NLP 语义解析', detail: '分析核心目标和约束条件…' },
    { title: '任务拆解', status: 'pending', tool: '规划引擎' },
    { title: '信息收集', status: 'pending', tool: '知识检索' },
    { title: '方案生成', status: 'pending', tool: '推理引擎' },
    { title: '结果整理', status: 'pending', tool: '内容编排' }
  ]
  if (text.includes('架构') || text.includes('设计')) {
    steps.splice(2, 1, { title: '技术选型', status: 'pending', tool: '方案检索' })
    steps.splice(3, 1, { title: '架构设计', status: 'pending', tool: '架构推理引擎' })
  }
  if (text.includes('需求') || text.includes('分析')) {
    steps.splice(2, 1, { title: '需求调研', status: 'pending', tool: '知识库检索' })
  }
  return steps
}

function animateTaskSteps(taskMsg) {
  const details = [
    '提取到核心目标：构建完整方案',
    '拆分为 5 个子任务，预计 5 步完成',
    '检索相关知识库，匹配 12 条参考资料',
    '综合分析，生成结构化输出',
    '整理为可交付的结果文档'
  ]
  const results = [
    '识别 3 个核心目标 + 8 项约束',
    '生成执行计划，含依赖关系',
    '收集到 12 份相关资料与案例',
    '输出完整方案文档',
    '格式化并优化可读性'
  ]
  let stepIdx = 0
  const totalSteps = taskMsg.taskSteps.length

  const runStep = () => {
    if (stepIdx >= totalSteps) {
      taskMsg.taskStatus = 'done'
      taskRunning.value = false
      flowAgents.value.forEach(a => { if (a.status !== 'error') a.status = 'done' })
      setTimeout(() => {
        messages.value.push({
          id: Date.now() + 100,
          role: 'assistant',
          content: generateFinalResponse(messages.value.find(m => m.role === 'user')?.content || '')
        })
        const session = sessions.value.find(s => s.id === currentSession.value)
        if (session) {
          session.status = 'done'
          session.subtitle = currentAssistantObj.value.name + ' · 已完成'
        }
        scrollToBottom()
      }, 500)
      return
    }
    const step = taskMsg.taskSteps[stepIdx]
    step.status = 'running'
    step.detail = details[stepIdx] || '执行中…'
    syncFlowAgent(stepIdx, 'running', step.detail)
    setTimeout(() => {
      step.status = 'done'
      step.result = results[stepIdx] || '完成'
      syncFlowAgent(stepIdx, 'done', step.detail, step.result)
      stepIdx++
      scrollToBottom()
      setTimeout(runStep, 600 + Math.random() * 400)
    }, 800 + Math.random() * 600)
  }
  setTimeout(runStep, 500)
}

/* 同步单个步骤状态到右侧 Agent 流程图面板 */
function syncFlowAgent(idx, status, detail, result) {
  if (!flowAgents.value || !flowAgents.value[idx]) return
  flowAgents.value[idx].status = status
  if (detail) flowAgents.value[idx].desc = detail
  if (result) flowAgents.value[idx].result = result
}

const AGENT_EMOJIS = ['🏗️', '🔗', '📊', '🧠', '📋', '⚙️', '🚀', '🧪']
const AGENT_GRADIENTS = [
  'linear-gradient(135deg, #6366f1, #8b5cf6)',
  'linear-gradient(135deg, #06b6d4, #0ea5e9)',
  'linear-gradient(135deg, #10b981, #059669)',
  'linear-gradient(135deg, #f59e0b, #f97316)',
  'linear-gradient(135deg, #ec4899, #f472b6)',
  'linear-gradient(135deg, #8b5cf6, #6366f1)',
  'linear-gradient(135deg, #ef4444, #f97316)',
  'linear-gradient(135deg, #0ea5e9, #06b6d4)'
]

function generateFinalResponse(text) {
  if (text.includes('架构') || text.includes('设计')) {
    return `## 🏗️ 架构设计方案已完成\n\n我已为你完成了知识图谱系统的架构设计，以下是核心结论：\n\n### 📐 四层架构\n1. **数据层** - Neo4j + PostgreSQL + Elasticsearch + MinIO\n2. **计算层** - GraphScope + Spark + AI 推理服务\n3. **服务层** - Graph API + Workflow Engine + MCP Server\n4. **应用层** - 可视化工作台 + AI 助手 + 管理控制台\n\n### 🛠 技术选型亮点\n- 图数据库选择 **Neo4j**（社区成熟，生态完善）\n- 计算引擎选择 **GraphScope**（阿里开源，性能优异）\n- 前端采用 **Vue 3 + Element Plus**（快速交付）\n\n### 📊 性能预估\n- 十亿级实体秒级查询响应\n- 支持水平扩展，按需扩容\n- 99.9% SLA 可用性保障\n\n需要我针对某一层深入展开，或者调整技术选型吗？`
  }
  if (text.includes('需求') || text.includes('分析')) {
    return `## 📋 需求分析报告已完成\n\n我已为你梳理了知识图谱项目的全维需求：\n\n### ✅ 功能需求（12 项）\n- 数据采集：多源异构数据接入\n- 知识建模：可视化 Schema 定义\n- 图谱构建：自动化抽取与对齐\n- 图谱查询：Cypher/Gremlin 双语言支持\n- 分析挖掘：6 大类 20+ 图算法\n- 可视化展示：2D/3D 交互探索\n\n### ⚡ 非功能需求（6 项）\n- 性能：十亿级实体秒级查询\n- 可扩展性：水平扩展，按需扩容\n- 安全性：细粒度权限 + 数据加密\n- 可用性：99.9% SLA\n\n### 🎯 优先级排序\n**P0（必须）**：数据采集、图谱构建、基础查询\n**P1（重要）**：可视化、核心分析算法\n**P2（锦上添花）**：高级分析、AI 增强\n\n需要我针对某个需求模块深入展开吗？`
  }
  return `## ✅ 任务执行完成\n\n我已完成你提出的任务，以下是执行摘要：\n\n### 📊 执行统计\n- **总步骤数**：5 步\n- **调用工具**：NLP 解析 / 规划引擎 / 知识检索 / 推理引擎 / 内容编排\n- **参考资料**：12 份相关文档与案例\n\n### 🎯 核心成果\n1. 明确了目标与约束条件\n2. 制定了详细执行计划\n3. 收集了充分的参考资料\n4. 生成了完整方案输出\n5. 优化了结果可读性\n\n需要我继续深入某个方向，或者启动新的任务吗？`
}

function formatMarkdown(content) {
  let html = content
    .replace(/^## (.+)$/gm, '<h3 style="margin: 16px 0 8px; font-size: 16px; font-weight: 700;">$1</h3>')
    .replace(/^### (.+)$/gm, '<h4 style="margin: 12px 0 6px; font-size: 14px; font-weight: 600;">$1</h4>')
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/^- (.+)$/gm, '<li style="margin: 4px 0;">$1</li>')
    .replace(/\n/g, '<br>')
  html = html.replace(/(<li.*?<\/li>\s*)+/g, '<ul style="margin: 8px 0; padding-left: 20px;">$&</ul>')
  return html
}

function copyMsg(content) {
  navigator.clipboard.writeText(content)
  ElMessage.success('已复制到剪贴板')
}

function regenerate(msg) {
  const lastUserMsg = [...messages.value].reverse().find(m => m.role === 'user')
  if (lastUserMsg) {
    const msgIdx = messages.value.indexOf(msg)
    if (msgIdx > 0) messages.value.splice(msgIdx, 1)
    taskRunning.value = true
    isTyping.value = true
    setTimeout(() => {
      isTyping.value = false
      const taskMsg = {
        id: Date.now(), role: 'assistant', type: 'task',
        taskTitle: '重新生成中…', taskStatus: 'running',
        taskSteps: generateTaskSteps(lastUserMsg.content)
      }
      messages.value.push(taskMsg)
      const reactiveMsg = messages.value[messages.value.length - 1]
      scrollToBottom()
      animateTaskSteps(reactiveMsg)
    }, 500)
  }
}

function continueTask(msg) {
  inputText.value = '请继续深入展开，给出更详细的实现方案和代码示例。'
  sendMessage()
}

function onAssistantChange(assistant) {
  currentAssistant.value = assistant.id
  showAssistantPanel.value = false
  ElMessage.success(`已切换到 ${assistant.name}`)
}

function scrollToBottom() {
  nextTick(() => {
    if (messagesRef.value) {
      messagesRef.value.scrollTop = messagesRef.value.scrollHeight
    }
  })
}

function handleClickOutside(e) {
  if (showThemePanel.value && !e.target.closest('.theme-panel-popover') && !e.target.closest('.icon-btn')) {
    showThemePanel.value = false
  }
}

onMounted(() => {
  document.addEventListener('click', handleClickOutside)
  if (route.query.prompt) {
    inputText.value = decodeURIComponent(route.query.prompt)
    setTimeout(() => sendMessage(), 300)
  }
})

onUnmounted(() => {
  document.removeEventListener('click', handleClickOutside)
})
</script>

<style scoped>
/* ===== 黄金比例 φ ≈ 1.618 =====
   间距序列：4 → 6 → 10 → 16 → 26 → 42 → 68 → 110
   圆角序列：6 → 10 → 16 → 26 → 42
   字号序列：11 → 12 → 14 → 16 → 20 → 26 → 34 → 44 → 56 → 72 */

.ai-command-center {
  display: flex;
  height: 100%;
  width: 100%;
  background: var(--bg-deep-sky, #f6f8fc);
  position: relative;
  overflow: hidden;
}

.spin { animation: spin 1s linear infinite; }
@keyframes spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }

/* ===== 左侧侧边栏 · 黄金宽度 260px ===== */
.ai-sidebar {
  width: 260px;
  background: var(--bg-sidebar, #0b1120);
  border-right: 1px solid var(--border-soft, rgba(15, 23, 42, 0.09));
  display: flex;
  flex-direction: column;
  transition: width 0.3s cubic-bezier(0.22, 1, 0.36, 1);
  flex-shrink: 0;
  z-index: 10;
}
.ai-sidebar.collapsed { width: 68px; }

.ai-sidebar-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 16px 12px;
  min-height: 56px;
}
.ai-logo {
  display: flex;
  align-items: center;
  gap: 10px;
  font-weight: 800;
  font-size: 15px;
}
.ai-logo-icon {
  width: 42px;
  height: 42px;
  border-radius: 12px;
  background: linear-gradient(135deg, var(--brand, #6366f1), var(--accent, #06b6d4));
  display: grid;
  place-items: center;
  color: #fff;
  font-size: 20px;
  flex-shrink: 0;
  box-shadow: 0 4px 16px rgba(99, 102, 241, 0.35);
}
.ai-logo-text {
  white-space: nowrap;
  overflow: hidden;
  color: var(--text-primary, #0b1120);
  letter-spacing: -0.3px;
}
.collapse-btn {
  color: var(--text-tertiary, #64748b);
  padding: 4px;
}

/* 当前助手卡片 */
.current-assistant-card {
  display: flex;
  align-items: center;
  gap: 10px;
  margin: 0 12px 16px;
  padding: 12px;
  background: var(--bg-surface-2, #fafbfe);
  border: 1px solid var(--border-soft, rgba(15, 23, 42, 0.09));
  border-radius: 12px;
  cursor: pointer;
  transition: all 0.2s cubic-bezier(0.22, 1, 0.36, 1);
}
.current-assistant-card:hover {
  border-color: var(--brand, #6366f1);
  transform: translateY(-2px);
  box-shadow: 0 6px 20px rgba(99, 102, 241, 0.12);
}
.assistant-avatar-mini {
  width: 42px;
  height: 42px;
  border-radius: 12px;
  display: grid;
  place-items: center;
  flex-shrink: 0;
}
.assistant-avatar-mini span { font-size: 22px; }
.assistant-meta { flex: 1; min-width: 0; }
.assistant-name-mini {
  font-weight: 700;
  font-size: 13px;
  color: var(--text-primary, #0b1120);
  margin-bottom: 3px;
}
.assistant-status {
  font-size: 11px;
  color: var(--text-tertiary, #64748b);
  display: flex;
  align-items: center;
  gap: 5px;
}
.status-dot {
  width: 6px;
  height: 6px;
  border-radius: 50%;
  background: var(--text-quaternary, #94a3b8);
}
.status-dot.online {
  background: #10b981;
  box-shadow: 0 0 6px rgba(16, 185, 129, 0.6);
  animation: pulse 2s ease-in-out infinite;
}
@keyframes pulse {
  0%, 100% { opacity: 1; }
  50% { opacity: 0.6; }
}
.switch-icon {
  color: var(--text-quaternary, #94a3b8);
  font-size: 14px;
  flex-shrink: 0;
}

/* 新建任务按钮 */
.ai-new-chat { padding: 0 12px 16px; }
.new-task-btn {
  width: 100%;
  height: 44px;
  border-radius: 12px;
  font-weight: 700;
  font-size: 14px;
  background: linear-gradient(135deg, var(--brand, #6366f1), var(--accent, #06b6d4));
  border: none;
  box-shadow: 0 4px 16px rgba(99, 102, 241, 0.3);
  transition: all 0.2s cubic-bezier(0.22, 1, 0.36, 1);
}
.new-task-btn:hover {
  transform: translateY(-1px);
  box-shadow: 0 6px 20px rgba(99, 102, 241, 0.4);
}

/* 会话列表 */
.ai-session-list {
  flex: 1;
  overflow-y: auto;
  padding: 4px 10px;
}
.session-group { margin-bottom: 16px; }
.session-group-title {
  font-size: 11px;
  font-weight: 700;
  color: var(--text-tertiary, #64748b);
  padding: 8px 8px 6px;
  text-transform: uppercase;
  letter-spacing: 0.8px;
}
.session-item {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 10px;
  border-radius: 10px;
  cursor: pointer;
  color: var(--text-secondary, #334155);
  font-size: 13px;
  transition: all 0.15s;
  margin-bottom: 2px;
}
.session-item:hover {
  background: var(--bg-sidebar-hover, #101a2c);
  color: var(--text-primary, #0b1120);
}
.session-item.active {
  background: var(--bg-sidebar-active, #172033);
  color: var(--brand, #4f46e5);
  font-weight: 600;
  box-shadow: inset 0 0 0 1px var(--border-focus, rgba(99, 102, 241, 0.2));
}
.session-icon-wrap {
  width: 24px;
  height: 24px;
  display: grid;
  place-items: center;
  flex-shrink: 0;
  font-size: 16px;
}
.session-icon-wrap.running { color: var(--brand, #6366f1); }
.session-icon-wrap.done { color: #10b981; }
.session-info {
  flex: 1;
  min-width: 0;
  display: flex;
  flex-direction: column;
  gap: 2px;
}
.session-title {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  font-weight: 500;
  font-size: 13px;
}
.session-sub {
  font-size: 11px;
  color: var(--text-quaternary, #94a3b8);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

/* 底部用户卡片 */
.ai-sidebar-footer {
  padding: 14px 12px;
  border-top: 1px solid var(--border-soft, rgba(15, 23, 42, 0.09));
}
.user-card {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 8px;
  border-radius: 12px;
  cursor: pointer;
  transition: background 0.15s;
}
.user-card:hover { background: var(--bg-sidebar-hover, #101a2c); }
.user-avatar {
  width: 40px;
  height: 40px;
  border-radius: 50%;
  background: linear-gradient(135deg, #10b981, #06b6d4);
  display: grid;
  place-items: center;
  color: #fff;
  font-size: 18px;
  flex-shrink: 0;
}
.user-name {
  font-weight: 700;
  font-size: 13px;
  color: var(--text-primary, #0b1120);
}
.user-role {
  font-size: 11px;
  color: var(--text-tertiary, #64748b);
  margin-top: 2px;
}

/* ===== 中间主区域 ===== */
.ai-main {
  flex: 1;
  display: flex;
  flex-direction: column;
  overflow: hidden;
  position: relative;
  min-width: 0;
}

/* 顶部状态栏 · 黄金高度 56px */
.ai-topbar {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0 20px;
  height: 56px;
  border-bottom: 1px solid var(--border-soft, rgba(15, 23, 42, 0.09));
  background: var(--bg-surface, #fff);
  flex-shrink: 0;
  backdrop-filter: blur(8px);
}
.topbar-left {
  display: flex;
  align-items: center;
  gap: 12px;
}
.mobile-menu-btn { display: none; }
.current-task-title {
  font-size: 14px;
  font-weight: 700;
  color: var(--text-primary, #0b1120);
  letter-spacing: -0.2px;
}
.topbar-right {
  display: flex;
  align-items: center;
  gap: 6px;
}
.task-status-tag {
  display: flex;
  align-items: center;
  gap: 6px;
  font-size: 12px;
  font-weight: 600;
  height: 28px;
  padding: 0 12px;
  border-radius: 20px;
}
.icon-btn {
  width: 36px;
  height: 36px;
  color: var(--text-tertiary, #64748b);
  border-radius: 10px;
  transition: all 0.15s;
}
.icon-btn:hover {
  background: var(--bg-surface-2, #fafbfe);
  color: var(--brand, #6366f1);
}

/* ===== 欢迎页 · 黄金比例布局 ===== */
.ai-welcome {
  flex: 1;
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 42px 26px 26px;
  overflow-y: auto;
  position: relative;
  background: var(--hero-gradient, transparent);
}

/* Hero 区域 · 黄金比例高度 */
.welcome-hero {
  position: relative;
  text-align: center;
  margin-bottom: 42px;
  padding: 26px 0;
  width: 100%;
  max-width: 720px;
}
.hero-orb {
  position: absolute;
  border-radius: 50%;
  filter: blur(68px);
  opacity: 0.35;
  pointer-events: none;
}
.orb-1 {
  width: 260px;
  height: 260px;
  background: var(--brand, #6366f1);
  top: -42px;
  left: 10%;
  animation: float 6s ease-in-out infinite;
}
.orb-2 {
  width: 190px;
  height: 190px;
  background: var(--accent, #06b6d4);
  top: -16px;
  right: 15%;
  animation: float 7s ease-in-out infinite 1s;
}
.orb-3 {
  width: 220px;
  height: 220px;
  background: #ec4899;
  bottom: -68px;
  left: 50%;
  transform: translateX(-50%);
  animation: float 8s ease-in-out infinite 2s;
  opacity: 0.22;
}
@keyframes float {
  0%, 100% { transform: translateY(0); }
  50% { transform: translateY(-16px); }
}

.hero-content { position: relative; z-index: 1; }
.hero-badge {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  padding: 6px 16px;
  background: var(--brand-50, #eef2ff);
  color: var(--brand, #6366f1);
  border-radius: 20px;
  font-size: 12px;
  font-weight: 700;
  margin-bottom: 18px;
  letter-spacing: 0.3px;
}
.hero-title {
  font-size: 44px;
  font-weight: 800;
  color: var(--text-primary, #0b1120);
  margin: 0 0 14px;
  letter-spacing: -1.5px;
  line-height: 1.15;
}
.gradient-text {
  background: linear-gradient(135deg, var(--brand, #6366f1), var(--accent, #06b6d4));
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
}
.hero-subtitle {
  font-size: 16px;
  color: var(--text-secondary, #334155);
  margin: 0;
  line-height: 1.7;
  max-width: 480px;
  margin-left: auto;
  margin-right: auto;
}

/* 能力卡片 · 黄金 3 列 */
.capability-section {
  width: 100%;
  max-width: 820px;
  margin-bottom: 26px;
}
.section-label {
  font-size: 12px;
  font-weight: 700;
  color: var(--text-tertiary, #64748b);
  margin-bottom: 12px;
  text-transform: uppercase;
  letter-spacing: 1px;
}
.capability-grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 12px;
}
.capability-card {
  padding: 20px;
  background: var(--bg-surface, #fff);
  border: 1px solid var(--border-soft, rgba(15, 23, 42, 0.09));
  border-radius: 16px;
  cursor: pointer;
  transition: all 0.25s cubic-bezier(0.22, 1, 0.36, 1);
  position: relative;
  overflow: hidden;
}
.capability-card::before {
  content: '';
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  height: 3px;
  background: linear-gradient(90deg, var(--brand, #6366f1), var(--accent, #06b6d4));
  opacity: 0;
  transition: opacity 0.25s;
}
.capability-card:hover {
  border-color: var(--brand, #6366f1);
  box-shadow: 0 10px 30px rgba(99, 102, 241, 0.15);
  transform: translateY(-4px);
}
.capability-card:hover::before { opacity: 1; }
.cap-icon {
  width: 48px;
  height: 48px;
  border-radius: 12px;
  display: grid;
  place-items: center;
  margin-bottom: 14px;
}
.cap-icon span { font-size: 26px; }
.cap-title {
  font-weight: 700;
  font-size: 15px;
  color: var(--text-primary, #0b1120);
  margin-bottom: 6px;
  letter-spacing: -0.2px;
}
.cap-desc {
  font-size: 12px;
  color: var(--text-tertiary, #64748b);
  line-height: 1.6;
  margin-bottom: 12px;
}
.cap-tags {
  display: flex;
  flex-wrap: wrap;
  gap: 5px;
}
.cap-tag {
  font-size: 10px;
  padding: 3px 8px;
  background: var(--bg-surface-2, #fafbfe);
  color: var(--text-tertiary, #64748b);
  border-radius: 6px;
  font-weight: 500;
}

/* 快捷指令 */
.quick-section {
  width: 100%;
  max-width: 820px;
  margin-bottom: 26px;
}
.quick-chips {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
}
.quick-chip {
  cursor: pointer;
  transition: all 0.15s;
  font-size: 12px;
  padding: 8px 14px !important;
  height: auto !important;
  border-radius: 10px !important;
  font-weight: 500;
}
.quick-chip:hover {
  background: var(--brand-50, #eef2ff);
  border-color: var(--brand, #6366f1);
  color: var(--brand, #6366f1);
  transform: translateY(-1px);
}

/* 底部输入框 */
.welcome-input {
  width: 100%;
  max-width: 720px;
}
.welcome-input-wrap {
  padding: 14px 14px 14px 18px;
}

/* ===== 对话页 ===== */
.ai-chat {
  flex: 1;
  display: flex;
  flex-direction: column;
  overflow: hidden;
}

.chat-messages {
  flex: 1;
  overflow-y: auto;
  padding: 26px 20px 20px;
}
.message-row {
  display: flex;
  gap: 14px;
  margin-bottom: 26px;
  max-width: 820px;
  margin-left: auto;
  margin-right: auto;
}
.message-row.user { flex-direction: row-reverse; }
.msg-avatar {
  width: 40px;
  height: 40px;
  border-radius: 12px;
  display: grid;
  place-items: center;
  flex-shrink: 0;
}
.msg-avatar.ai {
  background: linear-gradient(135deg, var(--brand, #6366f1), var(--accent, #06b6d4));
  color: #fff;
  box-shadow: 0 4px 12px rgba(99, 102, 241, 0.3);
}
.avatar-emoji { font-size: 20px; }
.msg-avatar.user {
  background: linear-gradient(135deg, #10b981, #06b6d4);
  color: #fff;
  font-size: 18px;
}
.msg-content {
  max-width: calc(100% - 54px);
  min-width: 0;
}
.msg-sender {
  font-size: 12px;
  font-weight: 600;
  color: var(--text-tertiary, #64748b);
  margin-bottom: 8px;
  display: flex;
  align-items: center;
  gap: 8px;
}
.sender-tag { font-weight: 500; }
.msg-bubble {
  padding: 14px 18px;
  border-radius: 16px;
  line-height: 1.7;
  font-size: 14px;
  word-wrap: break-word;
}
.msg-bubble.no-pad {
  padding: 0;
  background: transparent !important;
  border: none !important;
}
.user-bubble {
  background: linear-gradient(135deg, var(--brand, #6366f1), var(--accent, #06b6d4));
  color: #fff;
  border-radius: 16px 16px 4px 16px;
  box-shadow: 0 4px 14px rgba(99, 102, 241, 0.25);
}
.ai-bubble {
  background: var(--bg-surface, #fff);
  border: 1px solid var(--border-soft, rgba(15, 23, 42, 0.09));
  color: var(--text-primary, #0b1120);
  border-radius: 4px 16px 16px 16px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.03);
}
.ai-msg-body { line-height: 1.75; }
.ai-msg-body :deep(h3) { margin-top: 0 !important; }
.msg-actions {
  display: flex;
  gap: 4px;
  margin-top: 8px;
  opacity: 0;
  transition: opacity 0.2s;
}
.message-row.assistant:hover .msg-actions { opacity: 1; }
.msg-actions .el-button {
  font-size: 12px;
  color: var(--text-tertiary, #64748b);
}
.msg-actions .el-button:hover { color: var(--brand, #6366f1); }

/* 正在输入 */
.typing-bubble {
  display: flex;
  gap: 6px;
  padding: 22px 26px;
}
.typing-dot {
  width: 8px;
  height: 8px;
  border-radius: 50%;
  background: var(--text-tertiary, #64748b);
  animation: typing 1.4s ease-in-out infinite;
}
.typing-dot:nth-child(2) { animation-delay: 0.2s; }
.typing-dot:nth-child(3) { animation-delay: 0.4s; }
@keyframes typing {
  0%, 60%, 100% { transform: translateY(0); opacity: 0.5; }
  30% { transform: translateY(-6px); opacity: 1; }
}

/* 底部输入框 */
.chat-bottom {
  padding: 16px 20px 20px;
  background: linear-gradient(180deg, transparent, var(--bg-deep-sky, #f6f8fc) 40%);
  flex-shrink: 0;
}
.chat-bottom-tip {
  text-align: center;
  font-size: 11px;
  color: var(--text-quaternary, #94a3b8);
  margin-top: 10px;
}

.chat-input-wrap {
  max-width: 720px;
  margin: 0 auto;
  background: var(--bg-surface, #fff);
  border: 1px solid var(--border-normal, rgba(15, 23, 42, 0.12));
  border-radius: 16px;
  padding: 10px 10px 10px 14px;
  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.04);
  transition: all 0.2s cubic-bezier(0.22, 1, 0.36, 1);
  display: flex;
  align-items: flex-end;
  gap: 10px;
}
.chat-input-wrap:focus-within {
  border-color: var(--brand, #6366f1);
  box-shadow: 0 0 0 4px var(--shadow-ring, rgba(99, 102, 241, 0.1)), 0 6px 24px rgba(99, 102, 241, 0.1);
}
.input-prefix {
  display: flex;
  align-items: center;
  padding-top: 8px;
  flex-shrink: 0;
  color: var(--text-tertiary, #64748b);
  font-size: 18px;
}
.chat-input {
  flex: 1;
  min-width: 0;
}
.chat-input :deep(.el-textarea__inner) {
  border: none;
  box-shadow: none !important;
  padding: 8px 0;
  font-size: 14px;
  line-height: 1.65;
  resize: none;
  background: transparent;
  font-family: inherit;
}
.chat-input :deep(.el-textarea__inner:focus) { box-shadow: none; }
.input-suffix {
  display: flex;
  align-items: center;
  gap: 4px;
  flex-shrink: 0;
}
.icon-btn-sm {
  width: 36px;
  height: 36px;
  border-radius: 10px;
  color: var(--text-tertiary, #64748b);
  font-size: 16px;
  transition: all 0.15s;
}
.icon-btn-sm:hover {
  background: var(--brand-50, #eef2ff);
  color: var(--brand, #6366f1);
}
.send-btn {
  height: 40px;
  padding: 0 18px;
  border-radius: 10px;
  font-weight: 700;
  background: linear-gradient(135deg, var(--brand, #6366f1), var(--accent, #06b6d4));
  border: none;
  display: flex;
  align-items: center;
  gap: 6px;
  transition: all 0.2s cubic-bezier(0.22, 1, 0.36, 1);
}
.send-btn:hover:not(:disabled) {
  transform: translateY(-1px);
  box-shadow: 0 4px 14px rgba(99, 102, 241, 0.35);
}
.send-btn:disabled {
  background: var(--bg-surface-2, #fafbfe);
  color: var(--text-quaternary, #94a3b8);
}

.input-tips {
  text-align: center;
  font-size: 12px;
  color: var(--text-tertiary, #64748b);
  margin-top: 12px;
}

/* ===== 助手选择面板（抽屉） ===== */
.assistant-panel {
  position: fixed;
  top: 0;
  right: 0;
  width: 100%;
  height: 100%;
  z-index: 1000;
  pointer-events: none;
}
.assistant-panel.open { pointer-events: auto; }
.panel-overlay {
  position: absolute;
  inset: 0;
  background: rgba(0, 0, 0, 0.3);
  opacity: 0;
  transition: opacity 0.3s;
}
.assistant-panel.open .panel-overlay { opacity: 1; }
.panel-content {
  position: absolute;
  top: 0;
  right: 0;
  width: 340px;
  height: 100%;
  background: var(--bg-surface, #fff);
  box-shadow: -4px 0 30px rgba(0, 0, 0, 0.12);
  transform: translateX(100%);
  transition: transform 0.3s cubic-bezier(0.22, 1, 0.36, 1);
  overflow-y: auto;
  padding: 20px;
}
.assistant-panel.open .panel-content { transform: translateX(0); }
.panel-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 20px;
}
.panel-title {
  font-size: 18px;
  font-weight: 800;
  color: var(--text-primary, #0b1120);
  letter-spacing: -0.3px;
}

/* ===== 主题切换面板 ===== */
.theme-panel-popover {
  position: absolute;
  top: 56px;
  right: 20px;
  background: var(--bg-surface, #fff);
  border: 1px solid var(--border-soft, rgba(15, 23, 42, 0.09));
  border-radius: 12px;
  padding: 14px;
  box-shadow: var(--shadow-md, 0 4px 20px rgba(0, 0, 0, 0.08));
  z-index: 100;
  width: 210px;
}
.theme-panel-title {
  font-size: 11px;
  font-weight: 700;
  color: var(--text-tertiary, #64748b);
  margin-bottom: 12px;
  text-transform: uppercase;
  letter-spacing: 1px;
}
.theme-options {
  display: flex;
  flex-direction: column;
  gap: 6px;
}
.theme-option {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 10px 12px;
  border-radius: 10px;
  cursor: pointer;
  transition: all 0.15s;
}
.theme-option:hover { background: var(--bg-surface-2, #fafbfe); }
.theme-option.active { background: var(--brand-50, #eef2ff); }
.theme-preview {
  width: 28px;
  height: 28px;
  border-radius: 8px;
  border: 2px solid var(--border-soft, rgba(15, 23, 42, 0.09));
  flex-shrink: 0;
}
.theme-name {
  font-size: 13px;
  color: var(--text-primary, #0b1120);
  font-weight: 600;
}

/* ===== 响应式 · 黄金断点 ===== */
@media (max-width: 1100px) {
  .capability-grid { grid-template-columns: repeat(2, 1fr); }
  .hero-title { font-size: 36px; }
}

@media (max-width: 768px) {
  .ai-sidebar {
    position: fixed;
    z-index: 100;
    transform: translateX(-100%);
    transition: transform 0.3s;
    height: 100%;
  }
  .ai-sidebar.mobile-open { transform: translateX(0); }
  .mobile-menu-btn { display: block; }
  .capability-grid { grid-template-columns: 1fr; }
  .hero-title { font-size: 28px; }
  .hero-subtitle { font-size: 14px; }
  .panel-content { width: 100%; }
}
</style>
