<!-- Generated by Trae Work -->
<template>
  <div class="ai-layout">
    <!-- 左侧：会话历史侧边栏 -->
    <div class="ai-sidebar" :class="{ collapsed: sidebarCollapsed }">
      <div class="ai-sidebar-header">
        <div class="ai-logo">
          <div class="ai-logo-icon"><el-icon><MagicStick /></el-icon></div>
          <span v-if="!sidebarCollapsed" class="ai-logo-text">知识图谱 AI</span>
        </div>
        <el-button class="collapse-btn" text @click="sidebarCollapsed = !sidebarCollapsed">
          <el-icon><component :is="sidebarCollapsed ? 'Expand' : 'Fold'" /></el-icon>
        </el-button>
      </div>

      <div class="ai-new-chat">
        <el-button type="primary" class="new-chat-btn" @click="newSession">
          <el-icon><Edit /></el-icon>
          <span v-if="!sidebarCollapsed">新建对话</span>
        </el-button>
      </div>

      <div class="ai-session-list" v-if="!sidebarCollapsed">
        <div class="session-group">
          <div class="session-group-title">今天</div>
          <div
            v-for="s in todaySessions"
            :key="s.id"
            class="session-item"
            :class="{ active: s.id === currentSession }"
            @click="selectSession(s.id)"
          >
            <el-icon class="session-icon"><ChatDotRound /></el-icon>
            <span class="session-title">{{ s.title }}</span>
          </div>
        </div>
        <div class="session-group" v-if="yesterdaySessions.length">
          <div class="session-group-title">昨天</div>
          <div
            v-for="s in yesterdaySessions"
            :key="s.id"
            class="session-item"
            :class="{ active: s.id === currentSession }"
            @click="selectSession(s.id)"
          >
            <el-icon class="session-icon"><ChatDotRound /></el-icon>
            <span class="session-title">{{ s.title }}</span>
          </div>
        </div>
        <div class="session-group" v-if="earlierSessions.length">
          <div class="session-group-title">更早</div>
          <div
            v-for="s in earlierSessions"
            :key="s.id"
            class="session-item"
            :class="{ active: s.id === currentSession }"
            @click="selectSession(s.id)"
          >
            <el-icon class="session-icon"><ChatDotRound /></el-icon>
            <span class="session-title">{{ s.title }}</span>
          </div>
        </div>
      </div>

      <div class="ai-sidebar-footer">
        <div class="user-card">
          <div class="user-avatar">
            <el-icon><User /></el-icon>
          </div>
          <div v-if="!sidebarCollapsed" class="user-info">
            <div class="user-name">研究员</div>
            <div class="user-role">知识图谱专家</div>
          </div>
        </div>
      </div>
    </div>

    <!-- 中间：对话主区域 -->
    <div class="ai-main">
      <!-- 空状态：欢迎页 -->
      <div v-if="messages.length === 0" class="ai-welcome">
        <div class="welcome-brand">
          <div class="brand-logo"><el-icon><MagicStick /></el-icon></div>
          <h1 class="brand-title">你好，我是知识图谱 AI</h1>
          <p class="brand-subtitle">
            基于知识图谱与大模型，帮你做<span class="highlight">需求分析</span>、<span class="highlight">架构设计</span>、<span class="highlight">图谱推理</span>
          </p>
        </div>

        <!-- 推荐问法 -->
        <div class="suggestion-grid">
          <div class="suggest-card" v-for="(s, i) in welcomeSuggestions" :key="i" @click="sendSuggestion(s.prompt)">
            <div class="suggest-icon">{{ s.icon }}</div>
            <div class="suggest-title">{{ s.title }}</div>
            <div class="suggest-desc">{{ s.desc }}</div>
          </div>
        </div>

        <!-- 快捷标签 -->
        <div class="quick-tags">
          <el-tag
            v-for="(tag, i) in quickTags"
            :key="i"
            size="large"
            effect="plain"
            class="quick-tag"
            @click="sendSuggestion(tag)"
          >
            {{ tag }}
          </el-tag>
        </div>

        <!-- 底部输入框 -->
        <div class="welcome-input">
          <div class="chat-input-wrap">
            <el-input
              v-model="inputText"
              type="textarea"
              :rows="1"
              :autosize="{ minRows: 1, maxRows: 6 }"
              placeholder="给 AI 发消息，Shift + Enter 换行"
              resize="none"
              class="chat-input"
              @keydown.enter.exact.prevent="sendMessage"
            />
            <el-button type="primary" class="send-btn" :icon="Promotion" @click="sendMessage" :disabled="!inputText.trim()">
              发送
            </el-button>
          </div>
          <div class="input-tips">
            <span>💡 试试「帮我梳理一个知识图谱项目的需求」</span>
          </div>
        </div>
      </div>

      <!-- 对话状态 -->
      <div v-else class="ai-chat">
        <div class="chat-messages" ref="messagesRef">
          <div
            v-for="msg in messages"
            :key="msg.id"
            class="message-row"
            :class="msg.role"
          >
            <div v-if="msg.role === 'assistant'" class="msg-avatar ai">
              <el-icon><MagicStick /></el-icon>
            </div>
            <div class="msg-content">
              <div v-if="msg.role === 'assistant'" class="msg-sender">知识图谱 AI</div>
              <div class="msg-bubble">
                <p v-if="msg.role === 'user'">{{ msg.content }}</p>
                <div v-else class="ai-msg-body">
                  <p v-for="(p, idx) in formatAIResponse(msg.content)" :key="idx">{{ p }}</p>
                </div>
              </div>
              <div v-if="msg.role === 'assistant'" class="msg-actions">
                <el-button text size="small" @click="copyMsg(msg.content)">
                  <el-icon><CopyDocument /></el-icon> 复制
                </el-button>
                <el-button text size="small" @click="regenerate">
                  <el-icon><Refresh /></el-icon> 重新生成
                </el-button>
                <el-button text size="small" type="primary">
                  <el-icon><Top /></el-icon>
                </el-button>
                <el-button text size="small">
                  <el-icon><Bottom /></el-icon>
                </el-button>
              </div>
            </div>
            <div v-if="msg.role === 'user'" class="msg-avatar user">
              <el-icon><User /></el-icon>
            </div>
          </div>

          <!-- 正在输入 -->
          <div v-if="isTyping" class="message-row assistant">
            <div class="msg-avatar ai"><el-icon><MagicStick /></el-icon></div>
            <div class="msg-content">
              <div class="msg-bubble typing-bubble">
                <span class="typing-dot"></span>
                <span class="typing-dot"></span>
                <span class="typing-dot"></span>
              </div>
            </div>
          </div>
        </div>

        <!-- 对话底部输入框 -->
        <div class="chat-bottom">
          <div class="chat-input-wrap chat-input-wrap-bottom">
            <el-input
              v-model="inputText"
              type="textarea"
              :rows="1"
              :autosize="{ minRows: 1, maxRows: 6 }"
              placeholder="给 AI 发消息，Shift + Enter 换行"
              resize="none"
              class="chat-input"
              @keydown.enter.exact.prevent="sendMessage"
            />
            <div class="input-actions">
              <el-button text class="attach-btn" title="上传文件">
                <el-icon><Picture /></el-icon>
              </el-button>
              <el-button text class="attach-btn" title="引用图谱">
                <el-icon><Share /></el-icon>
              </el-button>
              <el-button type="primary" class="send-btn" :icon="Promotion" @click="sendMessage" :disabled="!inputText.trim()">
                发送
              </el-button>
            </div>
          </div>
          <div class="chat-bottom-tip">
            AI 生成的内容仅供参考，请核实重要信息
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, nextTick, onMounted, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import {
  MagicStick, ChatDotRound, Edit, User, Promotion, CopyDocument,
  Refresh, Top, Bottom, Picture, Share, Fold, Expand
} from '@element-plus/icons-vue'
import { ElMessage } from 'element-plus'

const route = useRoute()
const router = useRouter()

const sidebarCollapsed = ref(false)
const inputText = ref('')
const currentSession = ref('s1')
const isTyping = ref(false)
const messagesRef = ref(null)

// 模拟会话列表
const sessions = ref([
  { id: 's1', title: '知识图谱项目需求分析', date: 'today' },
  { id: 's2', title: '图计算算子选型建议', date: 'today' },
  { id: 's3', title: '用户权限模型设计', date: 'yesterday' },
  { id: 's4', title: '数据同步工作流编排', date: 'yesterday' },
  { id: 's5', title: '中心性分析算法对比', date: 'earlier' },
  { id: 's6', title: '社区发现算法应用场景', date: 'earlier' }
])

const todaySessions = computed(() => sessions.value.filter(s => s.date === 'today'))
const yesterdaySessions = computed(() => sessions.value.filter(s => s.date === 'yesterday'))
const earlierSessions = computed(() => sessions.value.filter(s => s.date === 'earlier'))

// 欢迎页推荐问法
const welcomeSuggestions = ref([
  { icon: '🎯', title: '需求分析', desc: '帮我梳理一个知识图谱项目的完整需求', prompt: '请帮我系统梳理一个知识图谱项目的完整需求，从功能需求、非功能需求、约束条件三个维度进行结构化分析，并给出优先级排序建议。' },
  { icon: '🏗️', title: '架构设计', desc: '设计一套可扩展的图谱技术架构', prompt: '请设计一套可扩展的知识图谱技术架构，包括数据层、计算层、服务层和应用层的技术选型建议。' },
  { icon: '🔗', title: '图谱分析', desc: '解释知识图谱的核心分析算法', prompt: '请系统解释知识图谱的核心分析算法，包括中心性分析、社区发现、路径分析等，并说明各自的应用场景。' },
  { icon: '🧵', title: '工作流编排', desc: '帮我设计一个数据处理工作流', prompt: '请帮我设计一个从数据采集、清洗、建模到入库的完整知识图谱数据处理工作流。' }
])

const quickTags = ref([
  '什么是知识图谱？',
  '推荐几个图计算算子',
  '如何设计图谱 Schema？',
  '中心性分析怎么用？'
])

// 当前会话的消息
const messages = ref([])

function newSession() {
  const id = 's' + Date.now()
  sessions.value.unshift({ id, title: '新对话', date: 'today' })
  currentSession.value = id
  messages.value = []
}

function selectSession(id) {
  currentSession.value = id
  // 模拟加载历史消息
  if (id !== 's1') {
    messages.value = [
      { id: 1, role: 'user', content: '你好，我想了解一下知识图谱' },
      { id: 2, role: 'assistant', content: '你好！知识图谱是一种用图结构来存储和表示知识的技术。它以实体为节点，以关系为边，将分散的知识组织成一个结构化的网络。\n\n知识图谱的核心价值在于：\n1. **关联发现** - 通过关系连接发现隐藏的关联\n2. **推理能力** - 基于已有知识推理出新知识\n3. **语义理解** - 让机器理解数据的含义\n4. **知识复用** - 结构化知识便于共享和复用\n\n有什么具体方面想深入了解吗？' }
    ]
  } else {
    messages.value = []
  }
  scrollToBottom()
}

function sendSuggestion(prompt) {
  inputText.value = prompt
  sendMessage()
}

function sendMessage() {
  const text = inputText.value.trim()
  if (!text) return

  // 如果是新对话，更新标题
  const session = sessions.value.find(s => s.id === currentSession.value)
  if (session && messages.value.length === 0) {
    session.title = text.slice(0, 20) + (text.length > 20 ? '…' : '')
  }

  // 添加用户消息
  messages.value.push({
    id: Date.now(),
    role: 'user',
    content: text
  })
  inputText.value = ''

  // 模拟 AI 回复
  isTyping.value = true
  scrollToBottom()

  setTimeout(() => {
    isTyping.value = false
    messages.value.push({
      id: Date.now() + 1,
      role: 'assistant',
      content: generateAIResponse(text)
    })
    nextTick(() => scrollToBottom())
  }, 1200)
}

function generateAIResponse(text) {
  if (text.includes('需求') || text.includes('梳理')) {
    return `好的，我来帮你系统梳理知识图谱项目的需求。\n\n## 📋 需求分析框架\n\n### 1. 功能需求\n- **数据采集**：支持多源异构数据接入（结构化/半结构化/非结构化）\n- **知识建模**：可视化 Schema 定义，支持实体/关系/属性建模\n- **图谱构建**：自动化抽取、实体对齐、关系抽取\n- **图谱查询**：支持 Cypher/Gremlin 等图查询语言\n- **分析挖掘**：中心性分析、社区发现、路径分析、链接预测\n- **可视化展示**：2D/3D 图谱可视化，支持交互探索\n\n### 2. 非功能需求\n- **性能**：十亿级实体秒级查询响应\n- **可扩展性**：支持水平扩展，按需扩容\n- **安全性**：细粒度权限控制，数据加密存储\n- **可用性**：99.9% SLA，支持故障自动恢复\n\n### 3. 约束条件\n- 技术栈：Vue 3 + Node.js + Neo4j\n- 部署环境：私有化部署 / 云原生\n- 项目周期：3 个月 MVP 版本\n\n需要我针对某个方向深入展开吗？`
  }
  if (text.includes('架构') || text.includes('设计')) {
    return `好的，这是一套可扩展的知识图谱技术架构设计方案。\n\n## 🏗️ 四层架构设计\n\n### 数据层（Data Layer）\n- **图数据库**：Neo4j / NebulaGraph / JanusGraph\n- **关系型数据库**：PostgreSQL（元数据管理）\n- **搜索引擎**：Elasticsearch（全文检索）\n- **对象存储**：MinIO（文件存储）\n\n### 计算层（Compute Layer）\n- **图计算引擎**：GraphX / GraphScope\n- **ETL 引擎**：Apache Spark / Flink\n- **AI 推理**：PyTorch + 大模型服务\n- **算子引擎**：自定义算子框架 + 插件化扩展\n\n### 服务层（Service Layer）\n- **Graph API**：统一的图谱查询接口\n- **Workflow Engine**：工作流编排引擎\n- **MCP Server**：多模态计算协议服务\n- **Auth Service**：认证与权限服务\n\n### 应用层（Application Layer）\n- **可视化工作台**：图谱可视化与交互探索\n- **AI 助手**：对话式图谱分析\n- **管理控制台**：系统监控与管理\n- **开放 API**：第三方集成接口\n\n想深入了解哪一层的细节？`
  }
  return `好的，关于「${text.slice(0, 20)}」这个问题，我来为你分析一下：\n\n这是一个很好的问题。在知识图谱领域，通常可以从以下几个维度来思考：\n\n1. **业务视角**：明确目标和价值，理解业务场景\n2. **数据视角**：评估数据质量、数量和多样性\n3. **技术视角**：选择合适的技术栈和工具\n4. **工程视角**：考虑可扩展性、可维护性和性能\n\n如果你能提供更多背景信息，我可以给出更具体的建议。你目前处于项目的哪个阶段呢？`
}

function formatAIResponse(content) {
  return content.split('\n').filter(p => p.trim())
}

function copyMsg(content) {
  navigator.clipboard.writeText(content)
  ElMessage.success('已复制到剪贴板')
}

function regenerate() {
  const lastUserMsg = [...messages.value].reverse().find(m => m.role === 'user')
  if (lastUserMsg) {
    // 移除最后一条 AI 消息
    const lastAiIdx = [...messages.value].reverse().findIndex(m => m.role === 'assistant')
    if (lastAiIdx !== -1) {
      messages.value.splice(messages.value.length - 1 - lastAiIdx, 1)
    }
    isTyping.value = true
    scrollToBottom()
    setTimeout(() => {
      isTyping.value = false
      messages.value.push({
        id: Date.now(),
        role: 'assistant',
        content: generateAIResponse(lastUserMsg.content + '（重新生成）')
      })
      nextTick(() => scrollToBottom())
    }, 1000)
  }
}

function scrollToBottom() {
  nextTick(() => {
    if (messagesRef.value) {
      messagesRef.value.scrollTop = messagesRef.value.scrollHeight
    }
  })
}

// 从 URL 参数读取初始 prompt
onMounted(() => {
  if (route.query.prompt) {
    inputText.value = decodeURIComponent(route.query.prompt)
    setTimeout(() => sendMessage(), 300)
  }
})

watch(() => route.query.prompt, (newVal) => {
  if (newVal && !messages.value.length) {
    inputText.value = decodeURIComponent(newVal)
    setTimeout(() => sendMessage(), 300)
  }
})
</script>

<style scoped>
.ai-layout {
  display: flex;
  height: 100%;
  width: 100%;
  background: var(--bg-deep-sky, #f8fafc);
}

/* ===== 左侧侧边栏 ===== */
.ai-sidebar {
  width: 260px;
  background: var(--bg-sidebar, #f1f5f9);
  border-right: 1px solid var(--border-soft, #e2e8f0);
  display: flex;
  flex-direction: column;
  transition: width 0.3s ease;
  flex-shrink: 0;
}
.ai-sidebar.collapsed {
  width: 60px;
}

.ai-sidebar-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 14px 12px;
  min-height: 56px;
}
.ai-logo {
  display: flex;
  align-items: center;
  gap: 10px;
  font-weight: 800;
  color: var(--text-primary, #1e293b);
  font-size: 15px;
}
.ai-logo-icon {
  width: 34px;
  height: 34px;
  border-radius: 10px;
  background: linear-gradient(135deg, #6366f1, #8b5cf6);
  display: grid;
  place-items: center;
  color: #fff;
  font-size: 18px;
  flex-shrink: 0;
}
.ai-logo-text {
  white-space: nowrap;
  overflow: hidden;
}
.collapse-btn {
  color: var(--text-tertiary, #94a3b8);
  padding: 4px;
}

.ai-new-chat {
  padding: 0 12px 12px;
}
.new-chat-btn {
  width: 100%;
  height: 40px;
  border-radius: 10px;
  font-weight: 600;
  background: linear-gradient(135deg, #6366f1, #8b5cf6);
  border: none;
  box-shadow: 0 2px 8px rgba(99, 102, 241, 0.3);
}
.new-chat-btn:hover {
  opacity: 0.92;
  box-shadow: 0 4px 12px rgba(99, 102, 241, 0.4);
}

.ai-session-list {
  flex: 1;
  overflow-y: auto;
  padding: 4px 8px;
}
.session-group {
  margin-bottom: 12px;
}
.session-group-title {
  font-size: 11px;
  font-weight: 600;
  color: var(--text-tertiary, #94a3b8);
  padding: 8px 8px 4px;
  text-transform: uppercase;
  letter-spacing: 0.5px;
}
.session-item {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 8px 10px;
  border-radius: 8px;
  cursor: pointer;
  color: var(--text-secondary, #475569);
  font-size: 13px;
  transition: all 0.15s;
  margin-bottom: 2px;
}
.session-item:hover {
  background: var(--bg-sidebar-hover, #e2e8f0);
  color: var(--text-primary, #1e293b);
}
.session-item.active {
  background: var(--bg-sidebar-active, #dbeafe);
  color: var(--brand, #4f46e5);
  font-weight: 600;
}
.session-icon {
  font-size: 16px;
  flex-shrink: 0;
}
.session-title {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  flex: 1;
}

.ai-sidebar-footer {
  padding: 12px;
  border-top: 1px solid var(--border-soft, #e2e8f0);
}
.user-card {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 6px;
  border-radius: 10px;
  cursor: pointer;
  transition: background 0.15s;
}
.user-card:hover {
  background: var(--bg-sidebar-hover, #e2e8f0);
}
.user-avatar {
  width: 34px;
  height: 34px;
  border-radius: 50%;
  background: linear-gradient(135deg, #10b981, #06b6d4);
  display: grid;
  place-items: center;
  color: #fff;
  font-size: 16px;
  flex-shrink: 0;
}
.user-name {
  font-weight: 600;
  font-size: 13px;
  color: var(--text-primary, #1e293b);
}
.user-role {
  font-size: 11px;
  color: var(--text-tertiary, #94a3b8);
  margin-top: 1px;
}

/* ===== 中间主区域 ===== */
.ai-main {
  flex: 1;
  display: flex;
  flex-direction: column;
  overflow: hidden;
  position: relative;
}

/* --- 欢迎页 --- */
.ai-welcome {
  flex: 1;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 40px 20px;
  overflow-y: auto;
}

.welcome-brand {
  text-align: center;
  margin-bottom: 36px;
}
.brand-logo {
  width: 64px;
  height: 64px;
  border-radius: 20px;
  background: linear-gradient(135deg, #6366f1, #8b5cf6, #ec4899);
  display: grid;
  place-items: center;
  color: #fff;
  font-size: 32px;
  margin: 0 auto 20px;
  box-shadow: 0 8px 24px rgba(99, 102, 241, 0.3);
  animation: brandFloat 3s ease-in-out infinite;
}
@keyframes brandFloat {
  0%, 100% { transform: translateY(0); }
  50% { transform: translateY(-6px); }
}
.brand-title {
  font-size: 28px;
  font-weight: 800;
  color: var(--text-primary, #1e293b);
  margin: 0 0 10px;
  letter-spacing: -0.5px;
}
.brand-subtitle {
  font-size: 15px;
  color: var(--text-secondary, #64748b);
  margin: 0;
  line-height: 1.6;
}
.brand-subtitle .highlight {
  color: var(--brand, #6366f1);
  font-weight: 600;
}

.suggestion-grid {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: 12px;
  max-width: 640px;
  width: 100%;
  margin-bottom: 28px;
}
.suggest-card {
  padding: 16px 18px;
  background: var(--bg-surface, #fff);
  border: 1px solid var(--border-soft, #e2e8f0);
  border-radius: 12px;
  cursor: pointer;
  transition: all 0.2s;
}
.suggest-card:hover {
  border-color: var(--brand, #6366f1);
  box-shadow: 0 4px 16px rgba(99, 102, 241, 0.15);
  transform: translateY(-2px);
}
.suggest-icon {
  font-size: 22px;
  margin-bottom: 8px;
}
.suggest-title {
  font-weight: 700;
  font-size: 14px;
  color: var(--text-primary, #1e293b);
  margin-bottom: 4px;
}
.suggest-desc {
  font-size: 12px;
  color: var(--text-tertiary, #64748b);
  line-height: 1.5;
}

.quick-tags {
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
  gap: 8px;
  margin-bottom: 28px;
}
.quick-tag {
  cursor: pointer;
  transition: all 0.15s;
  font-size: 12px;
}
.quick-tag:hover {
  background: var(--brand-50, #eef2ff);
  border-color: var(--brand, #6366f1);
  color: var(--brand, #6366f1);
}

.welcome-input {
  width: 100%;
  max-width: 640px;
}

/* --- 对话页 --- */
.ai-chat {
  flex: 1;
  display: flex;
  flex-direction: column;
  overflow: hidden;
}

.chat-messages {
  flex: 1;
  overflow-y: auto;
  padding: 24px 20px 20px;
}
.message-row {
  display: flex;
  gap: 12px;
  margin-bottom: 24px;
  max-width: 760px;
  margin-left: auto;
  margin-right: auto;
}
.message-row.user {
  flex-direction: row-reverse;
}
.msg-avatar {
  width: 36px;
  height: 36px;
  border-radius: 10px;
  display: grid;
  place-items: center;
  font-size: 18px;
  flex-shrink: 0;
}
.msg-avatar.ai {
  background: linear-gradient(135deg, #6366f1, #8b5cf6);
  color: #fff;
}
.msg-avatar.user {
  background: linear-gradient(135deg, #10b981, #06b6d4);
  color: #fff;
}
.msg-content {
  max-width: calc(100% - 48px);
}
.msg-sender {
  font-size: 12px;
  font-weight: 600;
  color: var(--text-tertiary, #64748b);
  margin-bottom: 6px;
}
.msg-bubble {
  padding: 12px 16px;
  border-radius: 12px;
  line-height: 1.7;
  font-size: 14px;
  word-wrap: break-word;
}
.message-row.user .msg-bubble {
  background: linear-gradient(135deg, #6366f1, #8b5cf6);
  color: #fff;
  border-radius: 12px 12px 4px 12px;
}
.message-row.assistant .msg-bubble {
  background: var(--bg-surface, #fff);
  border: 1px solid var(--border-soft, #e2e8f0);
  color: var(--text-primary, #1e293b);
  border-radius: 4px 12px 12px 12px;
}
.ai-msg-body p {
  margin: 0 0 8px;
}
.ai-msg-body p:last-child {
  margin-bottom: 0;
}
.msg-actions {
  display: flex;
  gap: 4px;
  margin-top: 6px;
  opacity: 0;
  transition: opacity 0.2s;
}
.message-row.assistant:hover .msg-actions {
  opacity: 1;
}
.msg-actions .el-button {
  font-size: 12px;
  color: var(--text-tertiary, #64748b);
}
.msg-actions .el-button:hover {
  color: var(--brand, #6366f1);
}

/* 正在输入 */
.typing-bubble {
  display: flex;
  gap: 4px;
  padding: 18px 20px;
}
.typing-dot {
  width: 8px;
  height: 8px;
  border-radius: 50%;
  background: var(--text-tertiary, #94a3b8);
  animation: typing 1.4s ease-in-out infinite;
}
.typing-dot:nth-child(2) { animation-delay: 0.2s; }
.typing-dot:nth-child(3) { animation-delay: 0.4s; }
@keyframes typing {
  0%, 60%, 100% { transform: translateY(0); opacity: 0.5; }
  30% { transform: translateY(-6px); opacity: 1; }
}

/* --- 底部输入框 --- */
.chat-bottom {
  padding: 16px 20px 20px;
  background: linear-gradient(180deg, transparent, var(--bg-deep-sky, #f8fafc) 40%);
}
.chat-bottom-tip {
  text-align: center;
  font-size: 11px;
  color: var(--text-quaternary, #94a3b8);
  margin-top: 8px;
}

.chat-input-wrap {
  max-width: 640px;
  margin: 0 auto;
  background: var(--bg-surface, #fff);
  border: 1px solid var(--border-normal, #cbd5e1);
  border-radius: 14px;
  padding: 10px 10px 10px 14px;
  box-shadow: 0 4px 16px rgba(0, 0, 0, 0.06);
  transition: all 0.2s;
}
.chat-input-wrap:focus-within {
  border-color: var(--brand, #6366f1);
  box-shadow: 0 0 0 4px rgba(99, 102, 241, 0.1), 0 4px 16px rgba(99, 102, 241, 0.1);
}
.chat-input-wrap-bottom {
  display: flex;
  align-items: flex-end;
  gap: 8px;
}
.chat-input :deep(.el-textarea__inner) {
  border: none;
  box-shadow: none !important;
  padding: 0;
  font-size: 14px;
  line-height: 1.6;
  resize: none;
  background: transparent;
}
.chat-input :deep(.el-textarea__inner:focus) {
  box-shadow: none;
}
.input-actions {
  display: flex;
  align-items: center;
  gap: 4px;
  flex-shrink: 0;
}
.attach-btn {
  width: 36px;
  height: 36px;
  border-radius: 10px;
  color: var(--text-tertiary, #64748b);
  font-size: 18px;
}
.attach-btn:hover {
  background: var(--brand-50, #eef2ff);
  color: var(--brand, #6366f1);
}
.send-btn {
  height: 36px;
  padding: 0 16px;
  border-radius: 10px;
  font-weight: 600;
  background: linear-gradient(135deg, #6366f1, #8b5cf6);
  border: none;
}
.send-btn:hover:not(:disabled) {
  opacity: 0.9;
  box-shadow: 0 2px 8px rgba(99, 102, 241, 0.3);
}
.send-btn:disabled {
  background: var(--bg-surface-2, #e2e8f0);
  color: var(--text-quaternary, #94a3b8);
}

.input-tips {
  text-align: center;
  font-size: 12px;
  color: var(--text-tertiary, #64748b);
  margin-top: 10px;
}

/* ===== 响应式 ===== */
@media (max-width: 768px) {
  .ai-sidebar {
    position: fixed;
    z-index: 100;
    transform: translateX(-100%);
    transition: transform 0.3s;
    height: 100%;
  }
  .ai-sidebar.mobile-open {
    transform: translateX(0);
  }
  .suggestion-grid {
    grid-template-columns: 1fr;
  }
  .brand-title {
    font-size: 22px;
  }
}
</style>
