apiVersion: v1
kind: Service
metadata:
  name: {{ include "xuanji-dr.fullname" . }}-secondary
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "xuanji-dr.labels" . | nindent 4 }}
    app.kubernetes.io/role: secondary
    dr.xuanji.io/region: {{ .Values.failoverRegion }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: graph
      port: {{ .Values.service.secondaryPort }}
      targetPort: graph
      protocol: TCP
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
    - name: raft
      port: 8200
      targetPort: raft
      protocol: TCP
  selector:
    {{- include "xuanji-dr.secondarySelectorLabels" . | nindent 4 }}
