<!-- Generated by Trae Work -->
<template>
  <el-dropdown trigger="click" @visible-change="onVisibleChange" class="notification-center">
    <button type="button" class="nc-trigger" aria-label="打开通知中心">
      <el-badge :value="unreadCount" :hidden="unreadCount === 0" :max="99" class="nc-badge">
        <el-icon class="nc-icon"><Bell /></el-icon>
      </el-badge>
    </button>
    <template #dropdown>
      <el-dropdown-menu class="nc-dropdown">
        <!-- 头部 -->
        <div class="nc-header">
          <div class="nc-title">
            <el-icon><Bell /></el-icon>
            <span>通知中心</span>
          </div>
          <el-button size="small" text type="primary" :disabled="marking || loading" @click.stop="markAllRead" v-if="unreadCount > 0">全部已读</el-button>
        </div>

        <!-- Tab 分类 -->
        <el-tabs v-model="activeTab" class="nc-tabs" @tab-change="onTabChange">
          <el-tab-pane label="全部" name="all">
            <span class="nc-tab-count" v-if="unreadCount > 0">{{ unreadCount }}</span>
          </el-tab-pane>
          <el-tab-pane label="消息" name="message">
            <span class="nc-tab-count" v-if="countByType('message') > 0">{{ countByType('message') }}</span>
          </el-tab-pane>
          <el-tab-pane label="任务" name="task">
            <span class="nc-tab-count" v-if="countByType('task') > 0">{{ countByType('task') }}</span>
          </el-tab-pane>
          <el-tab-pane label="告警" name="alert">
            <span class="nc-tab-count" v-if="countByType('alert') > 0">{{ countByType('alert') }}</span>
          </el-tab-pane>
        </el-tabs>

        <!-- 通知列表 -->
        <div class="nc-list" v-loading="loading" element-loading-text="加载通知中…">
          <div v-if="error && !loading" class="nc-empty">
            <el-icon :size="32" style="color:#ef4444"><Warning /></el-icon>
            <span>{{ error }}</span>
            <el-button size="small" type="primary" @click.stop="loadNotifications">重试</el-button>
          </div>
          <template v-else>
          <div
            v-for="item in filteredNotifications"
            :key="item.id"
            class="nc-item"
            role="button"
            tabindex="0"
            :class="{ unread: !item.read }"
            @click="handleClick(item)"
            @keydown.enter.prevent="handleClick(item)"
            @keydown.space.prevent="handleClick(item)"
          >
            <div class="nc-item-icon" :style="{ background: typeStyles[item.type].bg, color: typeStyles[item.type].color }">
              <el-icon><component :is="typeStyles[item.type].icon" /></el-icon>
            </div>
            <div class="nc-item-body">
              <div class="nc-item-title">
                {{ item.title }}
                <span v-if="!item.read" class="nc-dot"></span>
              </div>
              <div class="nc-item-desc">{{ item.desc }}</div>
              <div class="nc-item-time">{{ item.time }}</div>
            </div>
          </div>
          <div v-if="filteredNotifications.length === 0" class="nc-empty">
            <el-icon :size="32" style="color:#cbd5e1"><Check /></el-icon>
            <span>暂无{{ activeTab === 'all' ? '' : typeLabels[activeTab] }}通知</span>
          </div>
          </template>
        </div>

        <!-- 底部 -->
        <div class="nc-footer" v-if="!error">
          <el-button text size="small" :disabled="page === 1 || loading" @click.stop="changePage(-1)">上一页</el-button>
          <span>{{ page }} / {{ Math.max(1, Math.ceil(total / 20)) }}</span>
          <el-button text size="small" :disabled="page * 20 >= total || loading" @click.stop="changePage(1)">下一页</el-button>
        </div>
      </el-dropdown-menu>
    </template>
  </el-dropdown>
  <el-dialog v-model="detailVisible" title="通知详情" width="min(560px, 90vw)">
    <h3>{{ selected?.title }}</h3>
    <p style="white-space: pre-wrap; overflow-wrap: anywhere">{{ selected?.desc }}</p>
  </el-dialog>
</template>

<script setup>
import { ref, computed, watch, onBeforeUnmount } from 'vue'
import { useAuthStore } from '@/stores'
import { formatDateTimeLocale } from '@/utils'
import { ElMessage } from 'element-plus/es/components/message/index'
import { Bell, Message, List, Warning, Check } from '@element-plus/icons-vue'
import { getNotifications, getNotificationUnreadCount, markNotificationRead, markAllNotificationsRead } from '@/api'

const auth = useAuthStore()
const counts = ref(null)
const page = ref(1)
const total = ref(0)
const marking = ref(false)
const selected = ref(null)
const detailVisible = ref(false)
let generation = 0
const activeTab = ref('all')
const loading = ref(false)
const error = ref('')

const typeStyles = {
  message: { icon: Message, bg: '#e0f2fe', color: '#0284c7' },
  task: { icon: List, bg: '#fef3c7', color: '#d97706' },
  alert: { icon: Warning, bg: '#fee2e2', color: '#dc2626' }
}
const typeLabels = { message: '消息', task: '任务', alert: '告警' }

// 通知列表：调用 GET /api/notifications
const notifications = ref([])

const unreadCount = computed(() => counts.value?.total ?? 0)

function countByType(type) {
  return counts.value?.by_type?.[type] ?? 0
}

const filteredNotifications = computed(() => {
  if (activeTab.value === 'all') return notifications.value
  return notifications.value.filter(n => n.type === activeTab.value)
})

async function loadNotifications() {
  const request = ++generation
  loading.value = true
  error.value = ''
  if (!auth.isLoggedIn) { notifications.value = []; counts.value = null; loading.value = false; return }
  try {
    const [data, unread] = await Promise.all([getNotifications({ page: page.value, page_size: 20 }), getNotificationUnreadCount()])
    if (request !== generation) return
    counts.value = unread
    total.value = data.total
    const list = Array.isArray(data) ? data : (data?.items || data?.notifications || [])
    notifications.value = list.map(n => ({
      id: n.id,
      type: n.type || 'message',
      title: n.title || '',
      desc: n.description || n.desc || '',
      time: formatDateTimeLocale(n.created_at),
      read: n.read ?? false
    }))
  } catch (e) {
    // 通知中心是可降级的横切能力：后端未部署/租户暂无通知时不能污染页面冒烟，
    // 也不能让每个页面都出现全局错误弹窗。用户主动操作（标记已读）仍保留 error。
    if (request !== generation) return
    counts.value = null
    console.warn('[NotificationCenter] 通知服务不可用，已降级为空状态:', e)
    error.value = e?.message || '通知加载失败'
    notifications.value = []
  } finally {
    if (request === generation) loading.value = false
  }
}

function onTabChange() { /* tab 切换由 computed 过滤 */ }

async function handleClick(item) {
  const scope = auth.accessToken
  selected.value = item
  detailVisible.value = true
  if (!item.read) {
    try {
      await markNotificationRead(item.id)
      if (scope !== auth.accessToken) return
      await loadNotifications()
    } catch (e) {
      if (scope !== auth.accessToken) return
      console.error('[NotificationCenter] 标记已读失败:', e)
      ElMessage.error('标记已读失败：' + (e.message || '未知错误'))
    }
  }

}

async function markAllRead() {
  if (marking.value) return
  const scope = auth.accessToken
  marking.value = true
  try {
    await markAllNotificationsRead()
    if (scope !== auth.accessToken) return
    await loadNotifications()
    ElMessage.success('已全部标记为已读')
  } catch (e) {
    if (scope !== auth.accessToken) return
    console.error('[NotificationCenter] 全部已读失败:', e)
    ElMessage.error('全部已读失败：' + (e.message || '未知错误'))
  } finally { marking.value = false }
}

function changePage(delta) { page.value += delta; loadNotifications() }

function onVisibleChange(visible) {
  // 展开时加载最新通知
  if (visible) {
    loadNotifications()
  }
}

watch(() => [auth.accessToken, auth.userId, auth.tenantId], () => {
  selected.value = null; detailVisible.value = false
  notifications.value = []; counts.value = null; total.value = 0; page.value = 1
  loadNotifications()
}, { immediate: true, flush: 'sync' })
onBeforeUnmount(() => { generation++ })
</script>

<style scoped>
.notification-center {
  display: inline-flex;
  align-items: center;
}
.nc-trigger {
  border: 0;
  background: transparent;
  width: 36px;
  height: 36px;
  border-radius: 10px;
  display: grid;
  place-items: center;
  cursor: pointer;
  transition: all 0.2s;
  color: var(--text-2);
}
.nc-trigger:hover {
  background: var(--brand-soft);
  color: var(--brand);
}
.nc-icon {
  font-size: 18px;
}
.nc-badge :deep(.el-badge__content) {
  font-size: 10px;
  height: 16px;
  padding: 0 5px;
  border-radius: 8px;
}

.nc-dropdown {
  width: 360px;
  max-height: 480px;
  padding: 0 !important;
  border-radius: 12px !important;
  overflow: hidden;
}

.nc-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 14px 16px;
  border-bottom: 1px solid var(--border-1);
}
.nc-title {
  display: flex;
  align-items: center;
  gap: 8px;
  font-weight: 700;
  font-size: 14px;
  color: var(--text-1);
}
.nc-title .el-icon {
  color: var(--brand);
}

.nc-tabs {
  padding: 0 8px;
  border-bottom: 1px solid var(--border-1);
}
:deep(.nc-tabs .el-tabs__nav-wrap::after) {
  display: none;
}
:deep(.nc-tabs .el-tabs__item) {
  height: 36px;
  line-height: 36px;
  font-size: 13px;
  font-weight: 600;
  display: flex;
  align-items: center;
  gap: 4px;
}
.nc-tab-count {
  display: inline-block;
  min-width: 18px;
  height: 18px;
  line-height: 18px;
  text-align: center;
  padding: 0 5px;
  font-size: 10px;
  font-weight: 700;
  background: var(--brand-fill);
  color: var(--on-brand);
  border-radius: 9px;
}

.nc-list {
  max-height: 320px;
  overflow-y: auto;
}
.nc-item {
  display: flex;
  gap: 10px;
  padding: 12px 16px;
  cursor: pointer;
  transition: background 0.15s;
  border-bottom: 1px solid var(--border-1);
}
.nc-item:last-child {
  border-bottom: none;
}
.nc-item:hover {
  background: var(--bg-page);
}
.nc-item.unread {
  background: rgba(79, 70, 229, 0.04);
}
.nc-item-icon {
  width: 36px;
  height: 36px;
  border-radius: 10px;
  display: grid;
  place-items: center;
  font-size: 16px;
  flex-shrink: 0;
}
.nc-item-body {
  flex: 1;
  min-width: 0;
}
.nc-item-title {
  font-weight: 600;
  font-size: 13px;
  color: var(--text-1);
  display: flex;
  align-items: center;
  gap: 6px;
}
.nc-dot {
  width: 6px;
  height: 6px;
  border-radius: 50%;
  background: var(--brand-fill); color: var(--on-brand);
  flex-shrink: 0;
}
.nc-item-desc {
  font-size: 12px;
  color: var(--text-2);
  margin-top: 3px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.nc-item-time {
  font-size: 11px;
  color: var(--text-3);
  margin-top: 4px;
}

.nc-empty {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 8px;
  padding: 40px 16px;
  color: var(--text-3);
  font-size: 13px;
}

.nc-footer {
  padding: 10px 16px;
  border-top: 1px solid var(--border-1);
  text-align: center;
}
</style>
