<!-- Generated by Trae Work -->
<template>
  <el-dropdown trigger="click" @visible-change="onVisibleChange" class="notification-center">
    <div class="nc-trigger" @click.stop>
      <el-badge :value="unreadCount" :hidden="unreadCount === 0" :max="99" class="nc-badge">
        <el-icon class="nc-icon"><Bell /></el-icon>
      </el-badge>
    </div>
    <template #dropdown>
      <el-dropdown-menu class="nc-dropdown">
        <!-- 头部 -->
        <div class="nc-header">
          <div class="nc-title">
            <el-icon><Bell /></el-icon>
            <span>通知中心</span>
          </div>
          <el-button size="small" text type="primary" @click.stop="markAllRead" v-if="unreadCount > 0">全部已读</el-button>
        </div>

        <!-- Tab 分类 -->
        <el-tabs v-model="activeTab" class="nc-tabs" @tab-change="onTabChange">
          <el-tab-pane label="全部" name="all">
            <span class="nc-tab-count" v-if="unreadCount > 0">{{ unreadCount }}</span>
          </el-tab-pane>
          <el-tab-pane label="消息" name="message">
            <span class="nc-tab-count" v-if="countByType('message') > 0">{{ countByType('message') }}</span>
          </el-tab-pane>
          <el-tab-pane label="任务" name="task">
            <span class="nc-tab-count" v-if="countByType('task') > 0">{{ countByType('task') }}</span>
          </el-tab-pane>
          <el-tab-pane label="告警" name="alert">
            <span class="nc-tab-count" v-if="countByType('alert') > 0">{{ countByType('alert') }}</span>
          </el-tab-pane>
        </el-tabs>

        <!-- 通知列表 -->
        <div class="nc-list">
          <div
            v-for="item in filteredNotifications"
            :key="item.id"
            class="nc-item"
            :class="{ unread: !item.read }"
            @click="handleClick(item)"
          >
            <div class="nc-item-icon" :style="{ background: typeStyles[item.type].bg, color: typeStyles[item.type].color }">
              <el-icon><component :is="typeStyles[item.type].icon" /></el-icon>
            </div>
            <div class="nc-item-body">
              <div class="nc-item-title">
                {{ item.title }}
                <span v-if="!item.read" class="nc-dot"></span>
              </div>
              <div class="nc-item-desc">{{ item.desc }}</div>
              <div class="nc-item-time">{{ item.time }}</div>
            </div>
          </div>
          <div v-if="filteredNotifications.length === 0" class="nc-empty">
            <el-icon :size="32" style="color:#cbd5e1"><Check /></el-icon>
            <span>暂无{{ activeTab === 'all' ? '' : typeLabels[activeTab] }}通知</span>
          </div>
        </div>

        <!-- 底部 -->
        <div class="nc-footer">
          <el-button text size="small" @click.stop="viewAll">查看全部通知 →</el-button>
        </div>
      </el-dropdown-menu>
    </template>
  </el-dropdown>
</template>

<script setup>
import { ref, computed } from 'vue'
import { useRouter } from 'vue-router'
import { Bell, Message, List, Warning, Check } from '@element-plus/icons-vue'

const router = useRouter()
const activeTab = ref('all')

const typeStyles = {
  message: { icon: 'Message', bg: '#e0f2fe', color: '#0284c7' },
  task: { icon: 'List', bg: '#fef3c7', color: '#d97706' },
  alert: { icon: 'Warning', bg: '#fee2e2', color: '#dc2626' }
}
const typeLabels = { message: '消息', task: '任务', alert: '告警' }

// 模拟通知数据
const notifications = ref([
  { id: 1, type: 'task', title: '任务即将到期', desc: '「需求分析文档」任务还有 2 小时到期', time: '10 分钟前', read: false },
  { id: 2, type: 'message', title: 'AI 助手新消息', desc: '您的架构分析报告已生成完毕', time: '30 分钟前', read: false },
  { id: 3, type: 'alert', title: '系统资源告警', desc: '算子引擎 CPU 使用率超过 80%', time: '1 小时前', read: false },
  { id: 4, type: 'task', title: '新任务分配', desc: '「用户权限模块」已分配给您', time: '2 小时前', read: true },
  { id: 5, type: 'message', title: '项目阶段更新', desc: '项目已从需求阶段进入架构阶段', time: '3 小时前', read: true },
  { id: 6, type: 'alert', title: '工作流执行失败', desc: '「数据同步工作流」第 3 个节点执行失败', time: '5 小时前', read: true }
])

const unreadCount = computed(() => notifications.value.filter(n => !n.read).length)

function countByType(type) {
  return notifications.value.filter(n => n.type === type && !n.read).length
}

const filteredNotifications = computed(() => {
  if (activeTab.value === 'all') return notifications.value
  return notifications.value.filter(n => n.type === activeTab.value)
})

function onTabChange() { /* placeholder */ }

function handleClick(item) {
  if (!item.read) item.read = true
  // 根据类型跳转
  if (item.type === 'task') router.push('/tasks')
  else if (item.type === 'alert') router.push('/admin?tab=monitor')
  else if (item.type === 'message') router.push('/ai')
}

function markAllRead() {
  notifications.value.forEach(n => { n.read = true })
}

function viewAll() {
  router.push('/tasks')
}

function onVisibleChange(visible) {
  // 展开时可以加载最新通知
  if (visible) {
    // 预留：加载最新通知
  }
}
</script>

<style scoped>
.notification-center {
  display: inline-flex;
  align-items: center;
}
.nc-trigger {
  width: 36px;
  height: 36px;
  border-radius: 10px;
  display: grid;
  place-items: center;
  cursor: pointer;
  transition: all 0.2s;
  color: var(--text-2);
}
.nc-trigger:hover {
  background: var(--brand-soft);
  color: var(--brand-dark);
}
.nc-icon {
  font-size: 18px;
}
.nc-badge :deep(.el-badge__content) {
  font-size: 10px;
  height: 16px;
  padding: 0 5px;
  border-radius: 8px;
}

.nc-dropdown {
  width: 360px;
  max-height: 480px;
  padding: 0 !important;
  border-radius: 12px !important;
  overflow: hidden;
}

.nc-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 14px 16px;
  border-bottom: 1px solid var(--border-1);
}
.nc-title {
  display: flex;
  align-items: center;
  gap: 8px;
  font-weight: 700;
  font-size: 14px;
  color: var(--text-1);
}
.nc-title .el-icon {
  color: var(--brand);
}

.nc-tabs {
  padding: 0 8px;
  border-bottom: 1px solid var(--border-1);
}
:deep(.nc-tabs .el-tabs__nav-wrap::after) {
  display: none;
}
:deep(.nc-tabs .el-tabs__item) {
  height: 36px;
  line-height: 36px;
  font-size: 13px;
  font-weight: 600;
  display: flex;
  align-items: center;
  gap: 4px;
}
.nc-tab-count {
  display: inline-block;
  min-width: 18px;
  height: 18px;
  line-height: 18px;
  text-align: center;
  padding: 0 5px;
  font-size: 10px;
  font-weight: 700;
  background: var(--brand);
  color: #fff;
  border-radius: 9px;
}

.nc-list {
  max-height: 320px;
  overflow-y: auto;
}
.nc-item {
  display: flex;
  gap: 10px;
  padding: 12px 16px;
  cursor: pointer;
  transition: background 0.15s;
  border-bottom: 1px solid var(--border-1);
}
.nc-item:last-child {
  border-bottom: none;
}
.nc-item:hover {
  background: var(--bg-page);
}
.nc-item.unread {
  background: rgba(79, 70, 229, 0.04);
}
.nc-item-icon {
  width: 36px;
  height: 36px;
  border-radius: 10px;
  display: grid;
  place-items: center;
  font-size: 16px;
  flex-shrink: 0;
}
.nc-item-body {
  flex: 1;
  min-width: 0;
}
.nc-item-title {
  font-weight: 600;
  font-size: 13px;
  color: var(--text-1);
  display: flex;
  align-items: center;
  gap: 6px;
}
.nc-dot {
  width: 6px;
  height: 6px;
  border-radius: 50%;
  background: var(--brand);
  flex-shrink: 0;
}
.nc-item-desc {
  font-size: 12px;
  color: var(--text-2);
  margin-top: 3px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.nc-item-time {
  font-size: 11px;
  color: var(--text-3);
  margin-top: 4px;
}

.nc-empty {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 8px;
  padding: 40px 16px;
  color: var(--text-3);
  font-size: 13px;
}

.nc-footer {
  padding: 10px 16px;
  border-top: 1px solid var(--border-1);
  text-align: center;
}
</style>
