<!-- Generated by Trae Work -->
<template>
  <el-dialog
    v-model="visible"
    width="560px"
    :close-on-click-modal="false"
    :show-close="false"
    class="onboarding-dialog"
  >
    <div class="onboarding-wrap">
      <!-- 顶部进度 -->
      <div class="onboarding-progress">
        <div
          v-for="(step, i) in steps"
          :key="i"
          class="progress-dot"
          :class="{ active: currentIdx === i, done: i < currentIdx }"
          @click="goTo(i)"
        ></div>
      </div>

      <!-- 步骤内容 -->
      <div class="onboarding-content">
        <div class="onboarding-icon" :style="{ background: steps[currentIdx].bg, color: steps[currentIdx].color }">
          <el-icon :size="36"><component :is="steps[currentIdx].icon" /></el-icon>
        </div>
        <h2 class="onboarding-title">{{ steps[currentIdx].title }}</h2>
        <p class="onboarding-desc">{{ steps[currentIdx].desc }}</p>

        <!-- 快捷键提示 -->
        <div v-if="steps[currentIdx].shortcut" class="onboarding-shortcut">
          <span class="sc-label">快捷键</span>
          <kbd v-for="k in steps[currentIdx].shortcut" :key="k" class="kbd">{{ k }}</kbd>
        </div>
      </div>

      <!-- 底部操作 -->
      <div class="onboarding-footer">
        <el-button text @click="skip">跳过引导</el-button>
        <div class="nav-btns">
          <el-button v-if="currentIdx > 0" @click="prev">上一步</el-button>
          <el-button v-if="currentIdx < steps.length - 1" type="primary" @click="next">下一步</el-button>
          <el-button v-else type="primary" @click="finish">开始使用</el-button>
        </div>
      </div>
    </div>
  </el-dialog>
</template>

<script setup>
import { ref, onMounted, watch } from 'vue'
import { Odometer, Search, Menu, ChatDotRound, MagicStick } from '@element-plus/icons-vue'

const props = defineProps({
  modelValue: { type: Boolean, default: false }
})
const emit = defineEmits(['update:modelValue', 'finish'])

const visible = ref(props.modelValue)
const currentIdx = ref(0)

watch(() => props.modelValue, (v) => { visible.value = v })
watch(visible, (v) => { emit('update:modelValue', v) })

const steps = [
  {
    icon: 'Odometer',
    color: '#4f46e5',
    bg: '#eef2ff',
    title: '欢迎来到项目工作台',
    desc: '以项目为中心的工作方式。进入系统后，你将直接看到当前项目的全貌——进度、任务、资源一目了然。',
    shortcut: null
  },
  {
    icon: 'Menu',
    color: '#0ea5e9',
    bg: '#e0f2fe',
    title: '清晰的侧边栏导航',
    desc: '10 个核心模块，分 3 组展示。80% 的高频功能触手可及，低频功能通过搜索即可直达。',
    shortcut: ['Alt + 1~9']
  },
  {
    icon: 'Search',
    color: '#7c3aed',
    bg: '#ede9fe',
    title: '全局命令面板',
    desc: '按下 Ctrl+K，一切尽在掌握。跳转模块、快速操作、搜索任务，一个输入框全部搞定。',
    shortcut: ['Ctrl', 'K']
  },
  {
    icon: 'MagicStick',
    color: '#ec4899',
    bg: '#fce7f3',
    title: 'AI 驱动的智能体验',
    desc: '无论是需求分析、架构设计还是代码生成，AI 助手全程陪伴。根据项目阶段智能推荐最佳实践。',
    shortcut: null
  },
  {
    icon: 'ChatDotRound',
    color: '#10b981',
    bg: '#ecfdf5',
    title: '准备好了吗？',
    desc: '点击「开始使用」，开启你的知识图谱与 AI 驱动之旅。随时可以按 Shift + ? 查看所有快捷键。',
    shortcut: ['Shift', '?']
  }
]

function next() {
  if (currentIdx.value < steps.length - 1) currentIdx.value++
}
function prev() {
  if (currentIdx.value > 0) currentIdx.value--
}
function goTo(i) {
  currentIdx.value = i
}
function skip() {
  finish()
}
function finish() {
  localStorage.setItem('onboarding_done', '1')
  visible.value = false
  emit('finish')
}

// 首次访问自动展示
onMounted(() => {
  const done = localStorage.getItem('onboarding_done')
  if (!done) {
    setTimeout(() => { visible.value = true }, 800)
  }
})
</script>

<style scoped>
.onboarding-dialog :deep(.el-dialog) {
  border-radius: 18px;
  overflow: hidden;
  background: linear-gradient(180deg, #ffffff 0%, #fafbff 100%);
  box-shadow: 0 32px 80px -20px rgba(79, 70, 229, 0.3), 0 12px 32px -8px rgba(0, 0, 0, 0.15);
}
.onboarding-dialog :deep(.el-dialog__body) {
  padding: 0;
}

.onboarding-wrap {
  padding: 36px 40px 24px;
}

.onboarding-progress {
  display: flex;
  justify-content: center;
  gap: 8px;
  margin-bottom: 32px;
}
.progress-dot {
  width: 28px;
  height: 5px;
  border-radius: 3px;
  background: var(--bg-tertiary);
  cursor: pointer;
  transition: all 0.3s;
}
.progress-dot.active {
  background: linear-gradient(90deg, #4f46e5, #7c3aed);
  width: 36px;
}
.progress-dot.done {
  background: #a5b4fc;
}

.onboarding-content {
  text-align: center;
}
.onboarding-icon {
  width: 72px;
  height: 72px;
  border-radius: 20px;
  display: grid;
  place-items: center;
  margin: 0 auto 20px;
  animation: iconBounce 0.6s ease;
}
@keyframes iconBounce {
  0% { transform: scale(0.8); opacity: 0; }
  60% { transform: scale(1.08); }
  100% { transform: scale(1); opacity: 1; }
}
.onboarding-title {
  font-size: 22px;
  font-weight: 800;
  color: var(--text-1);
  margin: 0 0 12px;
}
.onboarding-desc {
  font-size: 14px;
  line-height: 1.7;
  color: var(--text-2);
  margin: 0 auto;
  max-width: 400px;
}

.onboarding-shortcut {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  margin-top: 20px;
  padding: 8px 14px;
  background: var(--bg-tertiary);
  border-radius: 8px;
}
.sc-label {
  font-size: 12px;
  color: var(--text-3);
  font-weight: 600;
}
.onboarding-shortcut .kbd {
  display: inline-block;
  padding: 2px 8px;
  font-size: 12px;
  font-weight: 600;
  background: var(--bg-card);
  color: var(--text-1);
  border: 1px solid var(--border);
  border-radius: 5px;
  box-shadow: 0 1px 2px rgba(0, 0, 0, 0.06);
}

.onboarding-footer {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-top: 32px;
  padding-top: 20px;
  border-top: 1px solid var(--border-ghost);
}
.nav-btns {
  display: flex;
  gap: 8px;
}
</style>
