<!-- Generated by Trae Work -->
<template>
  <!-- KPI 卡片骨架：4 列 -->
  <template v-if="type === 'kpi'">
    <div class="skeleton-kpi">
      <div v-for="i in count" :key="i" class="skeleton-kpi-card">
        <div class="skeleton skeleton-title" style="width: 40%; height: 12px; margin-bottom: 10px;"></div>
        <div class="skeleton skeleton-value" style="width: 60%; height: 24px; margin-bottom: 8px;"></div>
        <div class="skeleton skeleton-desc" style="width: 30%; height: 10px;"></div>
      </div>
    </div>
  </template>

  <!-- 卡片骨架：带标题 + 内容 -->
  <template v-else-if="type === 'card'">
    <div class="skeleton-card">
      <div class="skeleton-card-header">
        <div class="skeleton" style="width: 30%; height: 14px;"></div>
        <div class="skeleton" style="width: 16px; height: 16px; border-radius: 50%;"></div>
      </div>
      <div class="skeleton-card-body">
        <div class="skeleton" style="width: 100%; height: 12px; margin-bottom: 8px;"></div>
        <div class="skeleton" style="width: 85%; height: 12px; margin-bottom: 8px;"></div>
        <div class="skeleton" style="width: 60%; height: 12px;"></div>
      </div>
    </div>
  </template>

  <!-- 列表骨架：多行 -->
  <template v-else-if="type === 'list'">
    <div class="skeleton-list">
      <div v-for="i in count" :key="i" class="skeleton-list-item">
        <div class="skeleton" style="width: 40px; height: 40px; border-radius: 10px; flex-shrink: 0;"></div>
        <div style="flex: 1;">
          <div class="skeleton" style="width: 40%; height: 14px; margin-bottom: 8px;"></div>
          <div class="skeleton" style="width: 70%; height: 12px; margin-bottom: 6px;"></div>
          <div class="skeleton" style="width: 25%; height: 10px;"></div>
        </div>
      </div>
    </div>
  </template>

  <!-- 图表骨架：占位 -->
  <template v-else-if="type === 'chart'">
    <div class="skeleton-chart">
      <div class="skeleton" style="width: 25%; height: 14px; margin-bottom: 16px;"></div>
      <div class="skeleton-chart-bars">
        <div v-for="i in 8" :key="i" class="skeleton-bar" :style="{ height: 30 + Math.random() * 70 + '%' }"></div>
      </div>
    </div>
  </template>
</template>

<script setup>
defineProps({
  type: { type: String, default: 'card' }, // kpi | card | list | chart
  count: { type: Number, default: 4 }
})
</script>

<style scoped>
.skeleton-kpi {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 12px;
}
@media (max-width: 900px) {
  .skeleton-kpi { grid-template-columns: repeat(2, 1fr); }
}
.skeleton-kpi-card {
  background: var(--bg-surface);
  border: 1px solid var(--border-ghost);
  border-radius: 12px;
  padding: 16px;
}

.skeleton-card {
  background: var(--bg-surface);
  border: 1px solid var(--border-ghost);
  border-radius: 12px;
  padding: 16px;
}
.skeleton-card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 14px;
}
.skeleton-card-body {
  display: flex;
  flex-direction: column;
}

.skeleton-list {
  display: flex;
  flex-direction: column;
  gap: 12px;
}
.skeleton-list-item {
  display: flex;
  gap: 12px;
  background: var(--bg-surface);
  border: 1px solid var(--border-ghost);
  border-radius: 10px;
  padding: 12px;
}

.skeleton-chart {
  background: var(--bg-surface);
  border: 1px solid var(--border-ghost);
  border-radius: 12px;
  padding: 16px;
  height: 200px;
}
.skeleton-chart-bars {
  display: flex;
  align-items: flex-end;
  gap: 8px;
  height: calc(100% - 30px);
}
.skeleton-bar {
  flex: 1;
  background: linear-gradient(180deg, var(--brand-50), var(--bg-surface-2));
  border-radius: 4px 4px 0 0;
  min-height: 20%;
}
</style>
