# =============================================================
# Xiaobai (桌面小白 xiaobai) 打包脚本
# -------------------------------------------------------------
# .\build_exe.ps1 [-UseVenv <path>] [-UseCondaEnv <path>] [-BuildDir build] [-DistDir dist] [-SkipBuild]
# =============================================================
[CmdletBinding()]
param(
    [string]$UseVenv = "",
    [string]$UseCondaEnv = "",
    [string]$BuildDir = (Join-Path $PSScriptRoot "build"),
    [string]$DistDir  = (Join-Path $PSScriptRoot "dist"),
    [switch]$SkipBuild = $false
)

$ErrorActionPreference = "Stop"
$Root = $PSScriptRoot

# --- 0) 确保 Python 解释器可用 + 注入外部 venv/conda env --------------------
if ($UseVenv -and (Test-Path $UseVenv)) {
    $env:XIAOBAI_VENV_DIR = (Resolve-Path $UseVenv).Path
    $PyExe = Join-Path $env:XIAOBAI_VENV_DIR "Scripts\python.exe"
    if (!(Test-Path $PyExe)) { $PyExe = Join-Path $env:XIAOBAI_VENV_DIR "bin/python" }
} elseif ($UseCondaEnv -and (Test-Path $UseCondaEnv)) {
    $env:XIAOBAI_VENV_DIR = (Resolve-Path $UseCondaEnv).Path
    $PyExe = Join-Path $env:XIAOBAI_VENV_DIR "python.exe"
} else {
    $PyExe = (Get-Command python).Source
}

if (!(Test-Path $PyExe)) { throw "Python 解释器不存在: $PyExe" }
Write-Host "→ python = $PyExe" -ForegroundColor Cyan
& $PyExe --version

# --- 1) 安装打包依赖 ---------------------------------------------------------
if (-not $SkipBuild) {
    Write-Host "→ 安装 PyInstaller 与项目（可编辑）" -ForegroundColor Cyan
    Push-Location $Root
    try {
        & $PyExe -m pip install --upgrade pip | Out-Null
        & $PyExe -m pip install -e ".[build]" --no-cache-dir 2>&1 | Select-Object -Last 20
    } finally {
        Pop-Location
    }
}

# --- 2) 准备 spec / 输出目录 ------------------------------------------------
New-Item -ItemType Directory -Force -Path $BuildDir | Out-Null
New-Item -ItemType Directory -Force -Path $DistDir  | Out-Null

# --- 2a) 生成 runtime hook (windowed 模式下 stdout/stderr=None 的第二道保险)
$HookContent = @'
import sys, io
if sys.stdout is None:
    sys.stdout = io.StringIO()
if sys.stderr is None:
    sys.stderr = io.StringIO()
'@
$HookPath = Join-Path $BuildDir "_xiaobai_hook.py"
Set-Content -Path $HookPath -Value $HookContent -Encoding UTF8
Write-Host "→ runtime hook 已生成: $HookPath" -ForegroundColor DarkGray

# --- 2b) 路径正斜杠标准化（避免 spec 里 \U 触发 unicodeescape SyntaxError）
$RootFwd  = $Root.Replace('\','/')
$RunPyFwd = (Join-Path $Root "run.py").Replace('\','/')
$HookFwd  = $HookPath.Replace('\','/')

$SpecContent = @"
# -*- mode: python ; coding: utf-8 -*-
# Auto-generated by build_exe.ps1. 如需定制可改为手工维护 .spec 文件。
import os
from pathlib import Path
from PyInstaller.utils.hooks import collect_data_files, collect_submodules

_ROOT = Path(r"$RootFwd")   # 项目根目录，正斜杠

block_cipher = None

hiddenimports = []
datas = []

# ---- 显式资源收集（collect_data_files 可能漏掉嵌套 yaml / 顶层文件） ----
# 1) xiaobai_voice/config/*.yaml （确保 default_config.yaml / models.yaml 打进包）
datas += [
    (str(_ROOT / "xiaobai_voice" / "config" / "*.yaml"), "xiaobai_voice/config"),
]
# 2) pyproject.toml：版本号 / license 信息可能从 importlib.metadata 或直接读
datas += [
    (str(_ROOT / "pyproject.toml"), "xiaobai_voice"),
]
# 3) README.md 放到 exe 同级目录（COLLECT 根）
datas += [
    (str(_ROOT / "README.md"), "."),
]
# 4) 顶层 models/ 目录说明文件（若存在则一并打包）
_models_dir = _ROOT / "models"
if _models_dir.is_dir():
    for _f in _models_dir.iterdir():
        if _f.is_file():
            datas += [(str(_f), "models")]

# ---- 再附加 importlib.metadata 级别的 data_files（双保险） ----
datas += collect_data_files("xiaobai_voice", include_py_files=False, excludes=["tests"])

# 常见三方库 DLLs / 资源
hiddenimports += collect_submodules("sherpa_onnx")
hiddenimports += collect_submodules("onnxruntime")
hiddenimports += collect_submodules("sounddevice")
hiddenimports += collect_submodules("httpx")
hiddenimports += collect_submodules("uvicorn")
hiddenimports += collect_submodules("fastapi")
hiddenimports += collect_submodules("websockets")
hiddenimports += collect_submodules("PySide6")
hiddenimports += collect_submodules("pynput")
# CosyVoice2 / Fish-S2-Pro 可选，不打包失败不中断
try:
    import cosyvoice  # noqa: F401
    hiddenimports += collect_submodules("cosyvoice")
except Exception:
    pass
try:
    import fish_speech  # noqa: F401
    hiddenimports += collect_submodules("fish_speech")
except Exception:
    pass

a = Analysis(
    [r"$RunPyFwd"],
    pathex=[str(_ROOT)],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[r"$HookFwd"],
    excludes=[
        # 不把交互式 / dev 工具打入包
        "tkinter", "matplotlib", "pandas", "plotly", "pytest", "black", "flake8", "jupyter", "IPython",
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="Xiaobai",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name="Xiaobai",
)
"@
$SpecPath = Join-Path $BuildDir "Xiaobai.spec"
Set-Content -Path $SpecPath -Value $SpecContent -Encoding UTF8
Write-Host "→ spec 已生成: $SpecPath" -ForegroundColor DarkGray
Write-Host "    入口脚本: $RunPyFwd" -ForegroundColor DarkGray
Write-Host "    runtime hook: $HookFwd" -ForegroundColor DarkGray

# --- 3) 构建 -----------------------------------------------------------------
Push-Location $Root
try {
    Write-Host "→ PyInstaller 构建中（首次较慢）…" -ForegroundColor Cyan
    & $PyExe -m PyInstaller --noconfirm --clean `
        --workpath (Resolve-Path $BuildDir) `
        --distpath (Resolve-Path $DistDir) `
        $SpecPath
    if ($LASTEXITCODE -ne 0) { throw "PyInstaller 失败，退出码 $LASTEXITCODE" }
} finally {
    Pop-Location
}

$Exe = Join-Path $DistDir "Xiaobai\Xiaobai.exe"
if (!(Test-Path $Exe)) { throw "构建后找不到: $Exe" }
Write-Host "OK → $Exe" -ForegroundColor Green
Write-Host ""
Write-Host "提示: 验收必须以 Start-Process 双击方式启动（避免掩盖 stderr=None 问题）：" -ForegroundColor DarkYellow
Write-Host "    Start-Process $Exe"
Write-Host "    Start-Process $Exe -ArgumentList '--selftest-full'"
