// Copyright (c) 2026 璇玑 RelGraph · 算子统一系统 (OUS) · 三联盟
// Licensed under the MIT License.
// GitHub 主仓: https://github.com/aikjx/mox.git
// GitCode 镜像: https://gitcode.com/aikjx/mox

//! TPL-04 图谱实体模板：节点/边实体 → 双 DDL / Rust 模型 / 图 API / 3D 画布页 / graph.mmd / 路由 / 菜单。
//! 对齐 `GraphView`（3d-force-graph）与 kg 域入图链路。

use std::collections::BTreeMap;
use std::fmt::Write as _;

use super::naming;
use super::tpl_crud::menu_json;
use super::{CodegenError, CodegenOutput};
use crate::model::{EntityWithFields, MetaField};

pub fn generate_graph(
    entity: &EntityWithFields,
    tpl_code: &str,
) -> Result<CodegenOutput, CodegenError> {
    let ent = &entity.entity;
    let pascal = naming::to_pascal(&ent.entity_code);
    let camel = naming::to_camel(&ent.entity_code);
    let plural = ent
        .entity_plural
        .clone()
        .unwrap_or_else(|| naming::pluralize(&ent.entity_code));
    let table = ent
        .table_name
        .clone()
        .unwrap_or_else(|| format!("biz_{}", ent.entity_code));
    let edge_table = format!("{table}_edge");
    let visible: Vec<&MetaField> = entity.fields.iter().filter(|f| f.is_hidden == 0).collect();

    let mut artifacts = BTreeMap::new();
    artifacts.insert(format!("ddl/{table}.sql"), node_ddl(&table, &visible));
    artifacts.insert(format!("ddl/{edge_table}.sql"), edge_ddl(&edge_table, &table));
    artifacts.insert(
        format!("rust/{pascal}Graph.rs"),
        rust_model(&pascal, &visible),
    );
    artifacts.insert("ts/api.ts".to_string(), ts_api(&plural, &pascal, &edge_table));
    artifacts.insert(
        format!("vue/{pascal}GraphCanvas.vue"),
        canvas_vue(&pascal, &camel, &plural),
    );
    artifacts.insert("graph.mmd".to_string(), mermaid(ent, &visible));
    artifacts.insert(
        format!("router/{plural}.ts"),
        router(&pascal, &plural, &camel),
    );
    artifacts.insert("menu.json".to_string(), menu_json(ent, &plural, tpl_code));

    Ok(CodegenOutput {
        entity_code: ent.entity_code.clone(),
        template: tpl_code.to_string(),
        artifacts,
    })
}

fn node_ddl(table: &str, fields: &[&MetaField]) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "-- Generated by mox-platform-meta-core codegen (TPL-04 node)");
    let _ = writeln!(out, "CREATE TABLE {table} (");
    let _ = writeln!(out, "  id TEXT PRIMARY KEY,");
    let _ = writeln!(out, "  tenant_id TEXT NOT NULL,");
    for f in fields {
        let req = if f.is_required == 1 { " NOT NULL" } else { "" };
        let _ = writeln!(out, "  {} {}{req},", f.field_code, naming::sql_type(&f.field_type));
    }
    let _ = writeln!(out, "  created_at TEXT NOT NULL,");
    let _ = writeln!(out, "  updated_at TEXT NOT NULL");
    let _ = writeln!(out, ");");
    out
}

fn edge_ddl(edge_table: &str, node_table: &str) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "-- Generated by mox-platform-meta-core codegen (TPL-04 edge)");
    let _ = writeln!(out, "CREATE TABLE {edge_table} (");
    let _ = writeln!(out, "  id TEXT PRIMARY KEY,");
    let _ = writeln!(out, "  tenant_id TEXT NOT NULL,");
    let _ = writeln!(out, "  src_id TEXT NOT NULL REFERENCES {node_table}(id),");
    let _ = writeln!(out, "  dst_id TEXT NOT NULL REFERENCES {node_table}(id),");
    let _ = writeln!(out, "  rel_type TEXT NOT NULL,");
    let _ = writeln!(out, "  evidence_id TEXT,");
    let _ = writeln!(out, "  created_at TEXT NOT NULL");
    let _ = writeln!(out, ");");
    let _ = writeln!(out, "CREATE INDEX idx_{edge_table}_src ON {edge_table} (src_id);");
    let _ = writeln!(out, "CREATE INDEX idx_{edge_table}_dst ON {edge_table} (dst_id);");
    out
}

fn rust_model(pascal: &str, fields: &[&MetaField]) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "// Generated by mox-platform-meta-core codegen (TPL-04)");
    let _ = writeln!(out, "use serde::{{Deserialize, Serialize}};");
    let _ = writeln!(out);
    let _ = writeln!(out, "#[derive(Debug, Clone, Serialize, Deserialize)]");
    let _ = writeln!(out, "pub struct {pascal}Node {{");
    let _ = writeln!(out, "    pub id: String,");
    let _ = writeln!(out, "    pub tenant_id: String,");
    for f in fields {
        let ty = naming::rust_type(&f.field_type);
        let opt = if f.is_required == 1 { "" } else { "Option<" };
        let close = if f.is_required == 1 { "" } else { ">" };
        let _ = writeln!(out, "    pub {}: {opt}{ty}{close},", f.field_code);
    }
    let _ = writeln!(out, "    pub created_at: String,");
    let _ = writeln!(out, "    pub updated_at: String,");
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);
    let _ = writeln!(out, "#[derive(Debug, Clone, Serialize, Deserialize)]");
    let _ = writeln!(out, "pub struct {pascal}Edge {{");
    let _ = writeln!(out, "    pub id: String,");
    let _ = writeln!(out, "    pub src_id: String,");
    let _ = writeln!(out, "    pub dst_id: String,");
    let _ = writeln!(out, "    pub rel_type: String,");
    let _ = writeln!(out, "    pub evidence_id: Option<String>,");
    let _ = writeln!(out, "    pub created_at: String,");
    let _ = writeln!(out, "}}");
    out
}

fn ts_api(plural: &str, pascal: &str, edge_table: &str) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "// Generated by mox-platform-meta-core codegen (TPL-04)");
    let _ = writeln!(out, "import {{ http }} from './http';");
    let _ = writeln!(out);
    let _ = writeln!(out, "const BASE = '/api/biz/{plural}';");
    let _ = writeln!(out);
    let _ = writeln!(out, "export function nodes{pascal}() {{");
    let _ = writeln!(out, "  return http.get(`${{BASE}}/nodes`);");
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);
    let _ = writeln!(out, "export function edges{pascal}() {{");
    let _ = writeln!(out, "  return http.get(`${{BASE}}/edges`);");
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);
    let _ = writeln!(out, "export function link{pascal}(srcId: string, dstId: string, relType: string) {{");
    let _ = writeln!(out, "  return http.post(`${{BASE}}/edges`, {{ src_id: srcId, dst_id: dstId, rel_type: relType }});");
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);
    let _ = writeln!(out, "export const {pascal}EdgeTable = '{edge_table}';");
    out
}

fn canvas_vue(pascal: &str, camel: &str, plural: &str) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "<!-- Generated by mox-platform-meta-core codegen (TPL-04) -->");
    let _ = writeln!(out, "<template>");
    let _ = writeln!(out, "  <div ref=\"container\" class=\"{camel}-graph\"></div>");
    let _ = writeln!(out, "</template>");
    let _ = writeln!(out);
    let _ = writeln!(out, "<script setup lang=\"ts\">");
    let _ = writeln!(out, "import {{ onMounted, ref }} from 'vue';");
    let _ = writeln!(out, "import ForceGraph3D from '3d-force-graph';");
    let _ = writeln!(out, "import {{ nodes{pascal}, edges{pascal} }} from '../ts/api';");
    let _ = writeln!(out);
    let _ = writeln!(out, "const container = ref<HTMLDivElement | null>(null);");
    let _ = writeln!(out);
    let _ = writeln!(out, "onMounted(async () => {{");
    let _ = writeln!(out, "  const nodes = await nodes{pascal}();");
    let _ = writeln!(out, "  const links = await edges{pascal}();");
    let _ = writeln!(out, "  if (!container.value) return;");
    let _ = writeln!(out, "  ForceGraph3D()(container.value)");
    let _ = writeln!(out, "    .graphData({{ nodes, links }})");
    let _ = writeln!(out, "    .nodeLabel('id')");
    let _ = writeln!(out, "    .linkDirectionalArrowLength(4);");
    let _ = writeln!(out, "}});");
    let _ = writeln!(out, "</script>");
    let _ = writeln!(out);
    let _ = writeln!(out, "<style scoped>");
    let _ = writeln!(out, ".{camel}-graph {{ width: 100%; height: calc(100vh - 120px); }}");
    let _ = writeln!(out, "</style>");
    let _ = writeln!(out, "// route: /{plural}/graph");
    out
}

/// 生成 Mermaid ER 图骨架（节点实体 + 边实体），供 GraphView/入图预览。
fn mermaid(
    ent: &crate::model::MetaEntity,
    fields: &[&MetaField],
) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "--- Generated by mox-platform-meta-core codegen (TPL-04) ---");
    let _ = writeln!(out, "erDiagram");
    let _ = writeln!(out, "  {} {{", naming::to_pascal(&ent.entity_code).to_uppercase());
    for f in fields {
        let _ = writeln!(out, "    {} {}", f.field_type.to_uppercase(), f.field_code);
    }
    let _ = writeln!(out, "  }}");
    let _ = writeln!(
        out,
        "  {} ||--o{{ {}_EDGE : \"has\"",
        naming::to_pascal(&ent.entity_code).to_uppercase(),
        ent.entity_code.to_uppercase()
    );
    out
}

fn router(pascal: &str, plural: &str, camel: &str) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "// Generated by mox-platform-meta-core codegen (TPL-04)");
    let _ = writeln!(out, "import type {{ RouteRecordRaw }} from 'vue-router';");
    let _ = writeln!(out, "import {pascal}GraphCanvas from '../vue/{pascal}GraphCanvas.vue';");
    let _ = writeln!(out);
    let _ = writeln!(out, "export const {camel}Routes: RouteRecordRaw[] = [");
    let _ = writeln!(out, "  {{ path: '/{plural}/graph', name: '{camel}Graph', component: {pascal}GraphCanvas }},");
    let _ = writeln!(out, "];");
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{MetaEntity, MetaField};

    fn ent() -> EntityWithFields {
        let e = MetaEntity {
            entity_id: "ent_person".into(),
            tenant_id: "t001".into(),
            entity_code: "person".into(),
            entity_name: "人员".into(),
            entity_plural: None,
            table_name: None,
            description: None,
            icon: Some("user".into()),
            color: None,
            entity_category: "business".into(),
            storage_mode: "ext_slot".into(),
            shard_key: None,
            history_strategy: "none".into(),
            extends_entity_id: None,
            mixin_ids: None,
            tags: None,
            list_view_id: None,
            form_view_id: None,
            detail_view_id: None,
            workflow_id: None,
            is_system: 0,
            status: "active".into(),
            metadata: None,
            created_at: "2026-09-04T00:00:00Z".into(),
            updated_at: "2026-09-04T00:00:00Z".into(),
            created_by: None,
            updated_by: None,
            deleted_at: None,
            deleted_by: None,
            version: 1,
            _hash: None,
        };
        let f = MetaField {
            field_id: "fld_name".into(),
            tenant_id: "t001".into(),
            entity_id: "ent_person".into(),
            field_code: "full_name".into(),
            field_name: "姓名".into(),
            field_type: "string".into(),
            is_required: 1,
            is_unique: 0,
            is_indexed: 1,
            is_searchable: 1,
            is_sortable: 1,
            is_filterable: 1,
            is_exportable: 1,
            is_importable: 1,
            is_readonly: 0,
            is_hidden: 0,
            is_system: 0,
            default_value: None,
            default_expr: None,
            auto_fill_on: None,
            max_length: None,
            min_value: None,
            max_value: None,
            decimal_places: None,
            step: None,
            currency_code: None,
            unit: None,
            options_source: "none".into(),
            options_inline: None,
            options_sql: None,
            options_api: None,
            options_dict_code: None,
            relation_config: None,
            validations: None,
            formula_expr: None,
            formula_deps: None,
            ui_component: None,
            ui_props: None,
            ui_placeholder: None,
            ui_hint: None,
            ui_group: None,
            ui_sort_order: 0,
            ui_span: 1,
            ui_newline: 0,
            ui_dynamic_cond: None,
            field_permission: None,
            storage_slot: None,
            description: None,
            tags: None,
            status: "active".into(),
            metadata: None,
            created_at: "2026-09-04T00:00:00Z".into(),
            updated_at: "2026-09-04T00:00:00Z".into(),
            created_by: None,
            updated_by: None,
            deleted_at: None,
            deleted_by: None,
            version: 1,
            _hash: None,
        };
        EntityWithFields { entity: e, fields: vec![f], slot_map: Default::default() }
    }

    #[test]
    fn test_graph_artifacts_complete_and_deterministic() {
        let a = generate_graph(&ent(), "TPL-04").expect("ok");
        for path in [
            "ddl/biz_person.sql",
            "ddl/biz_person_edge.sql",
            "rust/PersonGraph.rs",
            "ts/api.ts",
            "vue/PersonGraphCanvas.vue",
            "graph.mmd",
            "router/persons.ts",
            "menu.json",
        ] {
            assert!(a.artifacts.contains_key(path), "missing {path}");
        }
        assert!(a.artifacts["ddl/biz_person_edge.sql"].contains("rel_type TEXT NOT NULL"));
        assert!(a.artifacts["graph.mmd"].starts_with("---"));
        assert!(a.artifacts["vue/PersonGraphCanvas.vue"].contains("ForceGraph3D"));
        assert_eq!(a, generate_graph(&ent(), "TPL-04").expect("b"), "deterministic");
    }
}
