// Copyright (c) 2026 璇玑 RelGraph · 算子统一系统 (OUS) · 三联盟
// Licensed under the MIT License.
// GitHub 主仓: https://github.com/aikjx/mox.git
// GitCode 镜像: https://gitcode.com/aikjx/mox

//! TPL-01 单表 CRUD 模板：实体元数据 → DDL / Rust 模型 / API / 列表页 / 表单页 / 路由 / 菜单。
//! 全部产物为确定性拼接，同输入字节级一致；生成器不产出任何 `todo!()` 骨架。

use std::collections::BTreeMap;
use std::fmt::Write as _;

use super::naming::{self, esc_str};
use super::{CodegenError, CodegenOutput};
use crate::model::{EntityWithFields, MetaField};

/// TPL-01 生成：单表 CRUD 成型项目工件。
///
/// # Errors
/// 仅透传内部拼接失败（当前实现为纯内存拼接，不产生错误；保留 `Result` 以稳定对外签名）。
pub fn generate_crud(
    entity: &EntityWithFields,
    tpl_code: &str,
) -> Result<CodegenOutput, CodegenError> {
    let ent = &entity.entity;
    let pascal = naming::to_pascal(&ent.entity_code);
    let camel = naming::to_camel(&ent.entity_code);
    let plural = ent
        .entity_plural
        .clone()
        .unwrap_or_else(|| naming::pluralize(&ent.entity_code));
    let table = ent
        .table_name
        .clone()
        .unwrap_or_else(|| format!("biz_{}", ent.entity_code));
    let visible: Vec<&MetaField> = entity.fields.iter().filter(|f| f.is_hidden == 0).collect();

    let mut artifacts = BTreeMap::new();
    artifacts.insert(format!("ddl/{table}.sql"), gen_ddl(&table, &visible));
    artifacts.insert(format!("rust/{pascal}.rs"), gen_rust_model(&pascal, &visible));
    artifacts.insert("ts/api.ts".to_string(), gen_ts_api(&plural, &pascal, &camel, &visible));
    artifacts.insert(
        format!("vue/{pascal}List.vue"),
        gen_list_vue(&pascal, &camel, &plural, &visible),
    );
    artifacts.insert(
        format!("vue/{pascal}Form.vue"),
        gen_form_vue(&pascal, &camel, &plural, &visible),
    );
    artifacts.insert(
        format!("router/{plural}.ts"),
        gen_router(&pascal, &plural, &camel),
    );
    artifacts.insert("menu.json".to_string(), menu_json(ent, &plural, tpl_code));

    Ok(CodegenOutput {
        entity_code: ent.entity_code.clone(),
        template: tpl_code.to_string(),
        artifacts,
    })
}

fn enum_options(f: &MetaField) -> Vec<(String, String)> {
    // options_inline 为 JSON 数组 [{"value","label",...}]；解析失败按空处理（确定性优先）。
    f.options_inline
        .as_deref()
        .and_then(|s| serde_json::from_str::<Vec<crate::model::EnumOption>>(s).ok())
        .map(|opts| {
            opts.into_iter()
                .map(|o| (o.value, o.label))
                .collect::<Vec<_>>()
        })
        .unwrap_or_default()
}

fn gen_ddl(table: &str, fields: &[&MetaField]) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "-- Generated by mox-platform-meta-core codegen (TPL-01)");
    let _ = writeln!(out, "CREATE TABLE {table} (");
    let _ = writeln!(out, "  id TEXT PRIMARY KEY,");
    let _ = writeln!(out, "  tenant_id TEXT NOT NULL,");
    let total = fields.len();
    for (i, f) in fields.iter().enumerate() {
        let ty = naming::sql_type(&f.field_type);
        let req = if f.is_required == 1 { " NOT NULL" } else { "" };
        let slot = f
            .storage_slot
            .as_deref()
            .map(|s| format!(" -- meta slot: {s}"))
            .unwrap_or_default();
        let comma = if i + 1 == total { "" } else { "," };
        let _ = writeln!(out, "  {} {ty}{req}{comma}{slot}", f.field_code);
    }
    let _ = writeln!(out, "  created_at TEXT NOT NULL,");
    let _ = writeln!(out, "  updated_at TEXT NOT NULL");
    let _ = writeln!(out, ");");
    for f in fields.iter().filter(|f| f.is_indexed == 1) {
        let _ = writeln!(
            out,
            "CREATE INDEX idx_{table}_{} ON {table} ({});",
            f.field_code, f.field_code
        );
    }
    out
}

fn gen_rust_model(pascal: &str, fields: &[&MetaField]) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "// Generated by mox-platform-meta-core codegen (TPL-01)");
    let _ = writeln!(out, "use serde::{{Deserialize, Serialize}};");
    let _ = writeln!(out);
    let _ = writeln!(out, "#[derive(Debug, Clone, Serialize, Deserialize)]");
    let _ = writeln!(out, "pub struct {pascal} {{");
    let _ = writeln!(out, "    pub id: String,");
    let _ = writeln!(out, "    pub tenant_id: String,");
    for f in fields {
        let ty = naming::rust_type(&f.field_type);
        let opt = if f.is_required == 1 { "" } else { "Option<" };
        let opt_close = if f.is_required == 1 { "" } else { ">" };
        let _ = writeln!(out, "    pub {}: {opt}{ty}{opt_close},", f.field_code);
    }
    let _ = writeln!(out, "    pub created_at: String,");
    let _ = writeln!(out, "    pub updated_at: String,");
    let _ = writeln!(out, "}}");
    out
}

fn gen_ts_api(plural: &str, pascal: &str, camel: &str, fields: &[&MetaField]) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "// Generated by mox-platform-meta-core codegen (TPL-01)");
    let _ = writeln!(out, "import {{ http }} from './http';");
    let _ = writeln!(out);
    let _ = writeln!(out, "export interface {pascal} {{");
    let _ = writeln!(out, "  id: string;");
    let _ = writeln!(out, "  tenant_id: string;");
    for f in fields {
        let opt = if f.is_required == 1 { "" } else { "?" };
        let _ = writeln!(
            out,
            "  {}{opt}: {};",
            f.field_code,
            naming::ts_type(&f.field_type)
        );
    }
    let _ = writeln!(out, "  created_at: string;");
    let _ = writeln!(out, "  updated_at: string;");
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);
    let _ = writeln!(out, "const BASE = '/api/biz/{plural}';");
    let _ = writeln!(out);
    let _ = writeln!(out, "export function list{pascal}(params?: Record<string, unknown>) {{");
    let _ = writeln!(out, "  return http.get(BASE, {{ params }});");
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);
    let _ = writeln!(out, "export function get{pascal}(id: string) {{");
    let _ = writeln!(out, "  return http.get(`${{BASE}}/${{id}}`);");
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);
    let _ = writeln!(out, "export function create{pascal}(data: Partial<{pascal}>) {{");
    let _ = writeln!(out, "  return http.post(BASE, data);");
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);
    let _ = writeln!(out, "export function update{pascal}(id: string, data: Partial<{pascal}>) {{");
    let _ = writeln!(out, "  return http.put(`${{BASE}}/${{id}}`, data);");
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);
    let _ = writeln!(out, "export function delete{pascal}(id: string) {{");
    let _ = writeln!(out, "  return http.delete(`${{BASE}}/${{id}}`);");
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);
    let _ = writeln!(out, "export const {camel}Api = {{ list{pascal}, get{pascal}, create{pascal}, update{pascal}, delete{pascal} }};");
    out
}

fn gen_list_vue(pascal: &str, camel: &str, plural: &str, fields: &[&MetaField]) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "<!-- Generated by mox-platform-meta-core codegen (TPL-01) -->");
    let _ = writeln!(out, "<template>");
    let _ = writeln!(out, "  <div class=\"{camel}-list\">");
    let _ = writeln!(out, "    <el-table :data=\"rows\" v-loading=\"loading\">");
    for f in fields.iter().take(8) {
        let _ = writeln!(
            out,
            "      <el-table-column prop=\"{}\" label=\"{}\" />",
            f.field_code,
            esc_str(&f.field_name)
        );
    }
    let _ = writeln!(out, "      <el-table-column label=\"操作\" fixed=\"right\">");
    let _ = writeln!(out, "        <template #default=\"{{ row }}\">");
    let _ = writeln!(out, "          <el-button link type=\"primary\" @click=\"edit(row)\">编辑</el-button>");
    let _ = writeln!(out, "          <el-button link type=\"danger\" @click=\"remove(row)\">删除</el-button>");
    let _ = writeln!(out, "        </template>");
    let _ = writeln!(out, "      </el-table-column>");
    let _ = writeln!(out, "    </el-table>");
    let _ = writeln!(out, "  </div>");
    let _ = writeln!(out, "</template>");
    let _ = writeln!(out);
    let _ = writeln!(out, "<script setup lang=\"ts\">");
    let _ = writeln!(out, "import {{ onMounted, ref }} from 'vue';");
    let _ = writeln!(out, "import {{ list{pascal}, delete{pascal}, type {pascal} }} from '../ts/api';");
    let _ = writeln!(out);
    let _ = writeln!(out, "const rows = ref<{pascal}[]>([]);");
    let _ = writeln!(out, "const loading = ref(false);");
    let _ = writeln!(out);
    let _ = writeln!(out, "async function reload() {{");
    let _ = writeln!(out, "  loading.value = true;");
    let _ = writeln!(out, "  try {{");
    let _ = writeln!(out, "    rows.value = await list{pascal}();");
    let _ = writeln!(out, "  }} finally {{");
    let _ = writeln!(out, "    loading.value = false;");
    let _ = writeln!(out, "  }}");
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);
    let _ = writeln!(out, "function edit(row: {pascal}) {{ /* 打开 {pascal}Form 并回填 row */ }}");
    let _ = writeln!(out, "async function remove(row: {pascal}) {{ await delete{pascal}(row.id); await reload(); }}");
    let _ = writeln!(out);
    let _ = writeln!(out, "onMounted(reload);");
    let _ = writeln!(out, "</script>");
    let _ = writeln!(out);
    let _ = writeln!(out, "<style scoped>");
    let _ = writeln!(out, ".{camel}-list {{ padding: 16px; }}");
    let _ = writeln!(out, "</style>");
    let _ = writeln!(out, "// route: /{plural}");
    out
}

fn gen_form_vue(pascal: &str, camel: &str, plural: &str, fields: &[&MetaField]) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "<!-- Generated by mox-platform-meta-core codegen (TPL-01) -->");
    let _ = writeln!(out, "<template>");
    let _ = writeln!(out, "  <el-form :model=\"form\" label-width=\"120px\" class=\"{camel}-form\">");
    for f in fields {
        let req = if f.is_required == 1 { " required" } else { "" };
        match f.field_type.as_str() {
            "integer" | "decimal" => {
                let _ = writeln!(
                    out,
                    "    <el-form-item label=\"{}\" prop=\"{}\"{req}>",
                    esc_str(&f.field_name),
                    f.field_code
                );
                let _ = writeln!(out, "      <el-input-number v-model=\"form.{}\" />", f.field_code);
                let _ = writeln!(out, "    </el-form-item>");
            }
            "boolean" => {
                let _ = writeln!(
                    out,
                    "    <el-form-item label=\"{}\" prop=\"{}\"{req}>",
                    esc_str(&f.field_name),
                    f.field_code
                );
                let _ = writeln!(out, "      <el-switch v-model=\"form.{}\" />", f.field_code);
                let _ = writeln!(out, "    </el-form-item>");
            }
            "datetime" => {
                let _ = writeln!(
                    out,
                    "    <el-form-item label=\"{}\" prop=\"{}\"{req}>",
                    esc_str(&f.field_name),
                    f.field_code
                );
                let _ = writeln!(
                    out,
                    "      <el-date-picker v-model=\"form.{}\" type=\"datetime\" />",
                    f.field_code
                );
                let _ = writeln!(out, "    </el-form-item>");
            }
            "enum" => {
                let _ = writeln!(
                    out,
                    "    <el-form-item label=\"{}\" prop=\"{}\"{req}>",
                    esc_str(&f.field_name),
                    f.field_code
                );
                let _ = writeln!(out, "      <el-select v-model=\"form.{}\">", f.field_code);
                for (value, label) in enum_options(f) {
                    let _ = writeln!(
                        out,
                        "        <el-option label=\"{}\" value=\"{}\" />",
                        esc_str(&label),
                        esc_str(&value)
                    );
                }
                let _ = writeln!(out, "      </el-select>");
                let _ = writeln!(out, "    </el-form-item>");
            }
            "text" => {
                let _ = writeln!(
                    out,
                    "    <el-form-item label=\"{}\" prop=\"{}\"{req}>",
                    esc_str(&f.field_name),
                    f.field_code
                );
                let _ = writeln!(
                    out,
                    "      <el-input v-model=\"form.{}\" type=\"textarea\" :rows=\"3\" />",
                    f.field_code
                );
                let _ = writeln!(out, "    </el-form-item>");
            }
            _ => {
                let _ = writeln!(
                    out,
                    "    <el-form-item label=\"{}\" prop=\"{}\"{req}>",
                    esc_str(&f.field_name),
                    f.field_code
                );
                let _ = writeln!(out, "      <el-input v-model=\"form.{}\" />", f.field_code);
                let _ = writeln!(out, "    </el-form-item>");
            }
        }
    }
    let _ = writeln!(out, "    <el-form-item>");
    let _ = writeln!(out, "      <el-button type=\"primary\" @click=\"submit\">保存</el-button>");
    let _ = writeln!(out, "    </el-form-item>");
    let _ = writeln!(out, "  </el-form>");
    let _ = writeln!(out, "</template>");
    let _ = writeln!(out);
    let _ = writeln!(out, "<script setup lang=\"ts\">");
    let _ = writeln!(out, "import {{ reactive }} from 'vue';");
    let _ = writeln!(out, "import {{ create{pascal}, update{pascal}, type {pascal} }} from '../ts/api';");
    let _ = writeln!(out);
    let _ = writeln!(out, "const props = defineProps<{{ initial?: Partial<{pascal}> }}>();");
    let _ = writeln!(out, "const form = reactive<Partial<{pascal}>>({{ ...props.initial }});");
    let _ = writeln!(out);
    let _ = writeln!(out, "async function submit() {{");
    let _ = writeln!(out, "  if (form.id) {{ await update{pascal}(form.id, form); }}");
    let _ = writeln!(out, "  else {{ await create{pascal}(form); }}");
    let _ = writeln!(out, "}}");
    let _ = writeln!(out, "</script>");
    let _ = writeln!(out);
    let _ = writeln!(out, "<style scoped>");
    let _ = writeln!(out, ".{camel}-form {{ max-width: 640px; }}");
    let _ = writeln!(out, "</style>");
    let _ = writeln!(out, "// route: /{plural}/form");
    out
}

fn gen_router(pascal: &str, plural: &str, camel: &str) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "// Generated by mox-platform-meta-core codegen (TPL-01)");
    let _ = writeln!(out, "import type {{ RouteRecordRaw }} from 'vue-router';");
    let _ = writeln!(out, "import {pascal}List from '../vue/{pascal}List.vue';");
    let _ = writeln!(out, "import {pascal}Form from '../vue/{pascal}Form.vue';");
    let _ = writeln!(out);
    let _ = writeln!(out, "export const {camel}Routes: RouteRecordRaw[] = [");
    let _ = writeln!(out, "  {{ path: '/{plural}', name: '{camel}List', component: {pascal}List }},");
    let _ = writeln!(out, "  {{ path: '/{plural}/form', name: '{camel}Form', component: {pascal}Form }},");
    let _ = writeln!(out, "];");
    out
}

/// 菜单登记 JSON（各模板共用）。
pub(crate) fn menu_json(
    ent: &crate::model::MetaEntity,
    plural: &str,
    tpl_code: &str,
) -> String {
    let icon = ent.icon.clone().unwrap_or_else(|| "menu".to_string());
    let json = serde_json::json!({
        "code": ent.entity_code,
        "name": ent.entity_name,
        "route": format!("/{plural}"),
        "icon": icon,
        "tpl": tpl_code,
    });
    serde_json::to_string_pretty(&json).unwrap_or_else(|_| "{}".to_string())
}
