// Copyright (c) 2026 璇玑 RelGraph · 算子统一系统 (OUS) · 三联盟
// Licensed under the MIT License.
// GitHub 主仓: https://github.com/aikjx/mox.git
// GitCode 镜像: https://gitcode.com/aikjx/mox

//! TPL-03 主子表模板：主实体 + 明细实体 → 双 DDL / 嵌套 Rust 模型 / API / 主子页面 / 路由 / 菜单。
//! 明细表自动携带 `master_id` 外键列。

use std::collections::BTreeMap;
use std::fmt::Write as _;

use super::naming;
use super::tpl_crud::menu_json;
use super::{CodegenError, CodegenOutput};
use crate::model::{EntityWithFields, MetaField};

/// TPL-03 生成：主实体 + 明细实体（明细自动加 `master_id`）。
///
/// # Errors
/// 主/明细实体校验失败（复用 [`super::generate`] 的校验规则）。
pub fn generate_master_detail(
    master: &EntityWithFields,
    detail: &EntityWithFields,
    tpl_code: &str,
) -> Result<CodegenOutput, CodegenError> {
    if master.entity.entity_code == detail.entity.entity_code {
        return Err(CodegenError::InvalidEntity(
            "master and detail entity_code must differ".into(),
        ));
    }
    let m = &master.entity;
    let d = &detail.entity;
    let mp = naming::to_pascal(&m.entity_code);
    let mc = naming::to_camel(&m.entity_code);
    let plural = m
        .entity_plural
        .clone()
        .unwrap_or_else(|| naming::pluralize(&m.entity_code));
    let mtable = m
        .table_name
        .clone()
        .unwrap_or_else(|| format!("biz_{}", m.entity_code));
    let dtable = d
        .table_name
        .clone()
        .unwrap_or_else(|| format!("biz_{}_detail", d.entity_code));
    let mv: Vec<&MetaField> = master.fields.iter().filter(|f| f.is_hidden == 0).collect();
    let dv: Vec<&MetaField> = detail.fields.iter().filter(|f| f.is_hidden == 0).collect();
    let dp = naming::to_pascal(&d.entity_code);

    let mut artifacts = BTreeMap::new();
    artifacts.insert(format!("ddl/{mtable}.sql"), ddl_master(&mtable, &mv));
    artifacts.insert(format!("ddl/{dtable}.sql"), ddl_detail(&dtable, &mtable, &dv));
    artifacts.insert(
        format!("rust/{mp}.rs"),
        rust_model(&mp, &dp, &mv, &dv),
    );
    artifacts.insert("ts/api.ts".to_string(), ts_api(&plural, &mp, &dp));
    artifacts.insert(
        format!("vue/{mp}MasterDetail.vue"),
        vue(&mp, &dp, &mc, &plural),
    );
    artifacts.insert(
        format!("router/{plural}.ts"),
        router(&mp, &plural, &mc),
    );
    artifacts.insert("menu.json".to_string(), menu_json(m, &plural, tpl_code));

    Ok(CodegenOutput {
        entity_code: m.entity_code.clone(),
        template: tpl_code.to_string(),
        artifacts,
    })
}

fn ddl_master(table: &str, fields: &[&MetaField]) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "-- Generated by mox-platform-meta-core codegen (TPL-03 master)");
    let _ = writeln!(out, "CREATE TABLE {table} (");
    let _ = writeln!(out, "  id TEXT PRIMARY KEY,");
    let _ = writeln!(out, "  tenant_id TEXT NOT NULL,");
    for f in fields {
        let req = if f.is_required == 1 { " NOT NULL" } else { "" };
        let _ = writeln!(out, "  {} {}{req},", f.field_code, naming::sql_type(&f.field_type));
    }
    let _ = writeln!(out, "  created_at TEXT NOT NULL,");
    let _ = writeln!(out, "  updated_at TEXT NOT NULL");
    let _ = writeln!(out, ");");
    out
}

fn ddl_detail(table: &str, master_table: &str, fields: &[&MetaField]) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "-- Generated by mox-platform-meta-core codegen (TPL-03 detail)");
    let _ = writeln!(out, "CREATE TABLE {table} (");
    let _ = writeln!(out, "  id TEXT PRIMARY KEY,");
    let _ = writeln!(out, "  tenant_id TEXT NOT NULL,");
    let _ = writeln!(out, "  master_id TEXT NOT NULL REFERENCES {master_table}(id),");
    for f in fields {
        let req = if f.is_required == 1 { " NOT NULL" } else { "" };
        let _ = writeln!(out, "  {} {}{req},", f.field_code, naming::sql_type(&f.field_type));
    }
    let _ = writeln!(out, "  sort_order INTEGER NOT NULL DEFAULT 0,");
    let _ = writeln!(out, "  created_at TEXT NOT NULL,");
    let _ = writeln!(out, "  updated_at TEXT NOT NULL");
    let _ = writeln!(out, ");");
    let _ = writeln!(out, "CREATE INDEX idx_{table}_master ON {table} (master_id);");
    out
}

fn rust_model(
    mp: &str,
    dp: &str,
    mfields: &[&MetaField],
    dfields: &[&MetaField],
) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "// Generated by mox-platform-meta-core codegen (TPL-03)");
    let _ = writeln!(out, "use serde::{{Deserialize, Serialize}};");
    let _ = writeln!(out);
    let _ = writeln!(out, "#[derive(Debug, Clone, Serialize, Deserialize)]");
    let _ = writeln!(out, "pub struct {dp}Detail {{");
    let _ = writeln!(out, "    pub id: String,");
    let _ = writeln!(out, "    pub master_id: String,");
    for f in dfields {
        let ty = naming::rust_type(&f.field_type);
        let opt = if f.is_required == 1 { "" } else { "Option<" };
        let close = if f.is_required == 1 { "" } else { ">" };
        let _ = writeln!(out, "    pub {}: {opt}{ty}{close},", f.field_code);
    }
    let _ = writeln!(out, "    pub sort_order: i64,");
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);
    let _ = writeln!(out, "#[derive(Debug, Clone, Serialize, Deserialize)]");
    let _ = writeln!(out, "pub struct {mp} {{");
    let _ = writeln!(out, "    pub id: String,");
    let _ = writeln!(out, "    pub tenant_id: String,");
    for f in mfields {
        let ty = naming::rust_type(&f.field_type);
        let opt = if f.is_required == 1 { "" } else { "Option<" };
        let close = if f.is_required == 1 { "" } else { ">" };
        let _ = writeln!(out, "    pub {}: {opt}{ty}{close},", f.field_code);
    }
    let _ = writeln!(out, "    pub details: Vec<{dp}Detail>,");
    let _ = writeln!(out, "    pub created_at: String,");
    let _ = writeln!(out, "    pub updated_at: String,");
    let _ = writeln!(out, "}}");
    out
}

fn ts_api(plural: &str, mp: &str, dp: &str) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "// Generated by mox-platform-meta-core codegen (TPL-03)");
    let _ = writeln!(out, "import {{ http }} from './http';");
    let _ = writeln!(out);
    let _ = writeln!(out, "const BASE = '/api/biz/{plural}';");
    let _ = writeln!(out);
    let _ = writeln!(out, "export function get{mp}WithDetails(id: string) {{");
    let _ = writeln!(out, "  return http.get(`${{BASE}}/${{id}}?with=details`);");
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);
    let _ = writeln!(out, "export function add{dp}(masterId: string, data: Record<string, unknown>) {{");
    let _ = writeln!(out, "  return http.post(`${{BASE}}/${{masterId}}/details`, data);");
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);
    let _ = writeln!(out, "export function remove{dp}(masterId: string, detailId: string) {{");
    let _ = writeln!(out, "  return http.delete(`${{BASE}}/${{masterId}}/details/${{detailId}}`);");
    let _ = writeln!(out, "}}");
    out
}

fn vue(mp: &str, dp: &str, mc: &str, plural: &str) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "<!-- Generated by mox-platform-meta-core codegen (TPL-03) -->");
    let _ = writeln!(out, "<template>");
    let _ = writeln!(out, "  <div class=\"{mc}-master-detail\">");
    let _ = writeln!(out, "    <el-table :data=\"masters\" highlight-current-row @current-change=\"onSelect\">");
    let _ = writeln!(out, "      <el-table-column prop=\"id\" label=\"ID\" />");
    let _ = writeln!(out, "    </el-table>");
    let _ = writeln!(out, "    <el-table :data=\"details\">");
    let _ = writeln!(out, "      <el-table-column prop=\"id\" label=\"明细ID\" />");
    let _ = writeln!(out, "      <el-table-column label=\"操作\">");
    let _ = writeln!(out, "        <template #default=\"{{ row }}\">");
    let _ = writeln!(out, "          <el-button link type=\"danger\" @click=\"removeDetail(row)\">删除</el-button>");
    let _ = writeln!(out, "        </template>");
    let _ = writeln!(out, "      </el-table-column>");
    let _ = writeln!(out, "    </el-table>");
    let _ = writeln!(out, "  </div>");
    let _ = writeln!(out, "</template>");
    let _ = writeln!(out);
    let _ = writeln!(out, "<script setup lang=\"ts\">");
    let _ = writeln!(out, "import {{ ref }} from 'vue';");
    let _ = writeln!(out, "import {{ get{mp}WithDetails, remove{dp}, type {mp} }} from '../ts/api';");
    let _ = writeln!(out);
    let _ = writeln!(out, "const masters = ref<{mp}[]>([]);");
    let _ = writeln!(out, "const details = ref<{{ id: string; [k: string]: unknown }}[]>([]);");
    let _ = writeln!(out);
    let _ = writeln!(out, "async function onSelect(row: {mp} | null) {{");
    let _ = writeln!(out, "  if (!row) return void (details.value = []);");
    let _ = writeln!(out, "  const full = await get{mp}WithDetails(row.id);");
    let _ = writeln!(out, "  details.value = full.details;");
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);
    let _ = writeln!(out, "async function removeDetail(row: {{ id: string; master_id?: string }}) {{");
    let _ = writeln!(out, "  if (row.master_id) await remove{dp}(row.master_id, row.id);");
    let _ = writeln!(out, "}}");
    let _ = writeln!(out, "</script>");
    let _ = writeln!(out);
    let _ = writeln!(out, "<style scoped>");
    let _ = writeln!(out, ".{mc}-master-detail {{ padding: 16px; display: grid; gap: 16px; }}");
    let _ = writeln!(out, "</style>");
    let _ = writeln!(out, "// route: /{plural}/master-detail");
    out
}

fn router(mp: &str, plural: &str, mc: &str) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "// Generated by mox-platform-meta-core codegen (TPL-03)");
    let _ = writeln!(out, "import type {{ RouteRecordRaw }} from 'vue-router';");
    let _ = writeln!(out, "import {mp}MasterDetail from '../vue/{mp}MasterDetail.vue';");
    let _ = writeln!(out);
    let _ = writeln!(out, "export const {mc}Routes: RouteRecordRaw[] = [");
    let _ = writeln!(out, "  {{ path: '/{plural}/master-detail', name: '{mc}MasterDetail', component: {mp}MasterDetail }},");
    let _ = writeln!(out, "];");
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{MetaEntity, MetaField};

    fn ent(code: &str) -> EntityWithFields {
        let e = MetaEntity {
            entity_id: format!("ent_{code}"),
            tenant_id: "t001".into(),
            entity_code: code.into(),
            entity_name: code.into(),
            entity_plural: None,
            table_name: None,
            description: None,
            icon: None,
            color: None,
            entity_category: "business".into(),
            storage_mode: "ext_slot".into(),
            shard_key: None,
            history_strategy: "none".into(),
            extends_entity_id: None,
            mixin_ids: None,
            tags: None,
            list_view_id: None,
            form_view_id: None,
            detail_view_id: None,
            workflow_id: None,
            is_system: 0,
            status: "active".into(),
            metadata: None,
            created_at: "2026-09-04T00:00:00Z".into(),
            updated_at: "2026-09-04T00:00:00Z".into(),
            created_by: None,
            updated_by: None,
            deleted_at: None,
            deleted_by: None,
            version: 1,
            _hash: None,
        };
        let f = MetaField {
            field_id: format!("fld_{code}"),
            tenant_id: "t001".into(),
            entity_id: format!("ent_{code}"),
            field_code: "amount".into(),
            field_name: "金额".into(),
            field_type: "decimal".into(),
            is_required: 0,
            is_unique: 0,
            is_indexed: 0,
            is_searchable: 0,
            is_sortable: 1,
            is_filterable: 0,
            is_exportable: 1,
            is_importable: 1,
            is_readonly: 0,
            is_hidden: 0,
            is_system: 0,
            default_value: None,
            default_expr: None,
            auto_fill_on: None,
            max_length: None,
            min_value: None,
            max_value: None,
            decimal_places: None,
            step: None,
            currency_code: None,
            unit: None,
            options_source: "none".into(),
            options_inline: None,
            options_sql: None,
            options_api: None,
            options_dict_code: None,
            relation_config: None,
            validations: None,
            formula_expr: None,
            formula_deps: None,
            ui_component: None,
            ui_props: None,
            ui_placeholder: None,
            ui_hint: None,
            ui_group: None,
            ui_sort_order: 0,
            ui_span: 1,
            ui_newline: 0,
            ui_dynamic_cond: None,
            field_permission: None,
            storage_slot: None,
            description: None,
            tags: None,
            status: "active".into(),
            metadata: None,
            created_at: "2026-09-04T00:00:00Z".into(),
            updated_at: "2026-09-04T00:00:00Z".into(),
            created_by: None,
            updated_by: None,
            deleted_at: None,
            deleted_by: None,
            version: 1,
            _hash: None,
        };
        EntityWithFields { entity: e, fields: vec![f], slot_map: Default::default() }
    }

    #[test]
    fn test_master_detail_artifacts_and_reject_same_code() {
        let out = generate_master_detail(&ent("order"), &ent("item"), "TPL-03").expect("ok");
        assert!(out.artifacts.contains_key("ddl/biz_order.sql"));
        assert!(out.artifacts.contains_key("ddl/biz_item_detail.sql"));
        let ddl = &out.artifacts["ddl/biz_item_detail.sql"];
        assert!(ddl.contains("REFERENCES biz_order(id)"));
        assert!(out.artifacts["rust/Order.rs"].contains("pub details: Vec<ItemDetail>"));
        assert_eq!(out, generate_master_detail(&ent("order"), &ent("item"), "TPL-03").expect("b"));

        let err = generate_master_detail(&ent("same"), &ent("same"), "TPL-03").expect_err("reject");
        assert!(matches!(err, CodegenError::InvalidEntity(_)));
    }
}
