// Copyright (c) 2026 璇玑 RelGraph · 算子统一系统 (OUS) · 三联盟
// Licensed under the MIT License.
// GitHub 主仓: https://github.com/aikjx/mox.git
// GitCode 镜像: https://gitcode.com/aikjx/mox

//! TPL-05 工作流模板：实体审批流 → workflow.json DAG 定义 / TS Runner / 路由 / 菜单。
//! 对齐 `WorkflowView` / primiflow DAG 执行引擎；流程定义数据化，无需写流程代码。

use std::collections::BTreeMap;
use std::fmt::Write as _;

use super::naming;
use super::tpl_crud::menu_json;
use super::{CodegenError, CodegenOutput};
use crate::model::EntityWithFields;

/// 默认审批 DAG：start → draft → approve → end（条件驳回回 draft），2 串联合议位。
const DEFAULT_NODES: [(&str, &str); 4] =
    [("start", "开始"), ("draft", "填报"), ("approve", "审批"), ("end", "结束")];

pub fn generate_workflow(
    entity: &EntityWithFields,
    tpl_code: &str,
) -> Result<CodegenOutput, CodegenError> {
    let ent = &entity.entity;
    let pascal = naming::to_pascal(&ent.entity_code);
    let camel = naming::to_camel(&ent.entity_code);
    let plural = ent
        .entity_plural
        .clone()
        .unwrap_or_else(|| naming::pluralize(&ent.entity_code));

    let mut artifacts = BTreeMap::new();
    artifacts.insert(
        format!("wf/{}.workflow.json", ent.entity_code),
        workflow_json(ent),
    );
    artifacts.insert(
        format!("ts/{pascal}Workflow.ts"),
        runner_ts(&pascal, &camel, &plural),
    );
    artifacts.insert(
        format!("router/{plural}.ts"),
        router(&pascal, &plural, &camel),
    );
    artifacts.insert("menu.json".to_string(), menu_json(ent, &plural, tpl_code));

    Ok(CodegenOutput {
        entity_code: ent.entity_code.clone(),
        template: tpl_code.to_string(),
        artifacts,
    })
}

fn workflow_json(ent: &crate::model::MetaEntity) -> String {
    let json = serde_json::json!({
        "workflow_code": format!("wf_{}", ent.entity_code),
        "workflow_name": format!("{}审批流", ent.entity_name),
        "entity_code": ent.entity_code,
        "version": 1,
        "nodes": DEFAULT_NODES.iter().map(|(id, name)| {
            serde_json::json!({ "id": id, "name": name, "type": if *id == "start" || *id == "end" { "event" } else { "task" } })
        }).collect::<Vec<_>>(),
        "transitions": [
            { "from": "start", "to": "draft", "condition": null },
            { "from": "draft", "to": "approve", "condition": "submitted == true" },
            { "from": "approve", "to": "end", "condition": "approved == true" },
            { "from": "approve", "to": "draft", "condition": "approved == false" }
        ],
        "roles": { "start": ["applicant"], "approve": ["approver"], "admin": ["admin"] }
    });
    serde_json::to_string_pretty(&json).unwrap_or_else(|_| "{}".to_string())
}

fn runner_ts(pascal: &str, camel: &str, plural: &str) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "// Generated by mox-platform-meta-core codegen (TPL-05)");
    let _ = writeln!(out, "import {{ http }} from './http';");
    let _ = writeln!(out);
    let _ = writeln!(out, "const BASE = '/api/biz/{plural}/workflow';");
    let _ = writeln!(out);
    let _ = writeln!(out, "export interface {pascal}Instance {{");
    let _ = writeln!(out, "  id: string;");
    let _ = writeln!(out, "  biz_id: string;");
    let _ = writeln!(out, "  instance_status: string;");
    let _ = writeln!(out, "  current_node_id: string;");
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);
    let _ = writeln!(out, "export function start{pascal}Workflow(bizId: string) {{");
    let _ = writeln!(out, "  return http.post(BASE, {{ biz_id: bizId }});");
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);
    let _ = writeln!(out, "export function decide{pascal}(instanceId: string, approved: boolean, comment?: string) {{");
    let _ = writeln!(out, "  return http.post(`${{BASE}}/${{instanceId}}/decide`, {{ approved, comment: comment ?? '' }});");
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);
    let _ = writeln!(out, "export const {camel}Workflow = {{ start{pascal}Workflow, decide{pascal} }};");
    out
}

fn router(pascal: &str, plural: &str, camel: &str) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "// Generated by mox-platform-meta-core codegen (TPL-05)");
    let _ = writeln!(out, "import type {{ RouteRecordRaw }} from 'vue-router';");
    let _ = writeln!(out, "import {pascal}List from '../vue/{pascal}List.vue';");
    let _ = writeln!(out);
    let _ = writeln!(out, "export const {camel}Routes: RouteRecordRaw[] = [");
    let _ = writeln!(out, "  {{ path: '/{plural}/workflow', name: '{camel}Workflow', component: {pascal}List }},");
    let _ = writeln!(out, "];");
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{MetaEntity, MetaField};

    fn ent() -> EntityWithFields {
        let e = MetaEntity {
            entity_id: "ent_leave".into(),
            tenant_id: "t001".into(),
            entity_code: "leave".into(),
            entity_name: "请假".into(),
            entity_plural: None,
            table_name: None,
            description: None,
            icon: None,
            color: None,
            entity_category: "business".into(),
            storage_mode: "ext_slot".into(),
            shard_key: None,
            history_strategy: "none".into(),
            extends_entity_id: None,
            mixin_ids: None,
            tags: None,
            list_view_id: None,
            form_view_id: None,
            detail_view_id: None,
            workflow_id: None,
            is_system: 0,
            status: "active".into(),
            metadata: None,
            created_at: "2026-09-04T00:00:00Z".into(),
            updated_at: "2026-09-04T00:00:00Z".into(),
            created_by: None,
            updated_by: None,
            deleted_at: None,
            deleted_by: None,
            version: 1,
            _hash: None,
        };
        let f = MetaField {
            field_id: "fld_reason".into(),
            tenant_id: "t001".into(),
            entity_id: "ent_leave".into(),
            field_code: "reason".into(),
            field_name: "事由".into(),
            field_type: "text".into(),
            is_required: 1,
            is_unique: 0,
            is_indexed: 0,
            is_searchable: 1,
            is_sortable: 0,
            is_filterable: 0,
            is_exportable: 1,
            is_importable: 1,
            is_readonly: 0,
            is_hidden: 0,
            is_system: 0,
            default_value: None,
            default_expr: None,
            auto_fill_on: None,
            max_length: None,
            min_value: None,
            max_value: None,
            decimal_places: None,
            step: None,
            currency_code: None,
            unit: None,
            options_source: "none".into(),
            options_inline: None,
            options_sql: None,
            options_api: None,
            options_dict_code: None,
            relation_config: None,
            validations: None,
            formula_expr: None,
            formula_deps: None,
            ui_component: None,
            ui_props: None,
            ui_placeholder: None,
            ui_hint: None,
            ui_group: None,
            ui_sort_order: 0,
            ui_span: 1,
            ui_newline: 0,
            ui_dynamic_cond: None,
            field_permission: None,
            storage_slot: None,
            description: None,
            tags: None,
            status: "active".into(),
            metadata: None,
            created_at: "2026-09-04T00:00:00Z".into(),
            updated_at: "2026-09-04T00:00:00Z".into(),
            created_by: None,
            updated_by: None,
            deleted_at: None,
            deleted_by: None,
            version: 1,
            _hash: None,
        };
        EntityWithFields { entity: e, fields: vec![f], slot_map: Default::default() }
    }

    #[test]
    fn test_workflow_artifacts_complete_and_deterministic() {
        let a = generate_workflow(&ent(), "TPL-05").expect("ok");
        assert!(a.artifacts.contains_key("wf/leave.workflow.json"));
        assert!(a.artifacts.contains_key("ts/LeaveWorkflow.ts"));
        let wf = &a.artifacts["wf/leave.workflow.json"];
        assert!(wf.contains("wf_leave"));
        assert!(wf.contains("approve"));
        assert_eq!(a, generate_workflow(&ent(), "TPL-05").expect("b"), "deterministic");
    }
}
