// Copyright (c) 2026 璇玑 RelGraph · 算子统一系统 (OUS) · 三联盟
// Licensed under the MIT License.
// GitHub 主仓: https://github.com/aikjx/mox.git
// GitCode 镜像: https://gitcode.com/aikjx/mox

//! TPL-06 AI 对话域模板：实体 AI 助手 → Chat 页面 / 会话 API / 路由 / 菜单。
//! 对齐 `ChatView` / `CaomeiView`；会话与消息持久化走 ai 域既有端点。

use std::collections::BTreeMap;
use std::fmt::Write as _;

use super::naming;
use super::tpl_crud::menu_json;
use super::{CodegenError, CodegenOutput};
use crate::model::EntityWithFields;

pub fn generate_ai_chat(
    entity: &EntityWithFields,
    tpl_code: &str,
) -> Result<CodegenOutput, CodegenError> {
    let ent = &entity.entity;
    let pascal = naming::to_pascal(&ent.entity_code);
    let camel = naming::to_camel(&ent.entity_code);
    let plural = ent
        .entity_plural
        .clone()
        .unwrap_or_else(|| naming::pluralize(&ent.entity_code));

    let mut artifacts = BTreeMap::new();
    artifacts.insert(
        format!("vue/{pascal}Chat.vue"),
        chat_vue(&pascal, &camel, &plural, &ent.entity_name),
    );
    artifacts.insert("ts/api.ts".to_string(), ts_api(&plural, &pascal));
    artifacts.insert(
        format!("router/{plural}.ts"),
        router(&pascal, &plural, &camel),
    );
    artifacts.insert("menu.json".to_string(), menu_json(ent, &plural, tpl_code));

    Ok(CodegenOutput {
        entity_code: ent.entity_code.clone(),
        template: tpl_code.to_string(),
        artifacts,
    })
}

fn chat_vue(pascal: &str, camel: &str, plural: &str, entity_name: &str) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "<!-- Generated by mox-platform-meta-core codegen (TPL-06) -->");
    let _ = writeln!(out, "<template>");
    let _ = writeln!(out, "  <div class=\"{camel}-chat\">");
    let _ = writeln!(out, "    <div class=\"messages\">");
    let _ = writeln!(out, "      <div v-for=\"(m, i) in messages\" :key=\"i\" :class=\"['msg', m.role]\">");
    let _ = writeln!(out, "        {{{{ m.content }}}}");
    let _ = writeln!(out, "      </div>");
    let _ = writeln!(out, "    </div>");
    let _ = writeln!(out, "    <el-input v-model=\"draft\" type=\"textarea\" :rows=\"2\"");
    let _ = writeln!(out, "              :placeholder=\"'向 {entity_name} AI 助手提问…'\" @keydown.enter.exact.prevent=\"send\" />");
    let _ = writeln!(out, "    <el-button type=\"primary\" :loading=\"busy\" @click=\"send\">发送</el-button>");
    let _ = writeln!(out, "  </div>");
    let _ = writeln!(out, "</template>");
    let _ = writeln!(out);
    let _ = writeln!(out, "<script setup lang=\"ts\">");
    let _ = writeln!(out, "import {{ ref }} from 'vue';");
    let _ = writeln!(out, "import {{ chat{pascal}, type ChatMessage }} from '../ts/api';");
    let _ = writeln!(out);
    let _ = writeln!(out, "const messages = ref<ChatMessage[]>([]);");
    let _ = writeln!(out, "const draft = ref('');");
    let _ = writeln!(out, "const busy = ref(false);");
    let _ = writeln!(out);
    let _ = writeln!(out, "async function send() {{");
    let _ = writeln!(out, "  const text = draft.value.trim();");
    let _ = writeln!(out, "  if (!text || busy.value) return;");
    let _ = writeln!(out, "  busy.value = true;");
    let _ = writeln!(out, "  messages.value.push({{ role: 'user', content: text }});");
    let _ = writeln!(out, "  try {{");
    let _ = writeln!(out, "    const reply = await chat{pascal}(messages.value);");
    let _ = writeln!(out, "    messages.value.push({{ role: 'assistant', content: reply }});");
    let _ = writeln!(out, "  }} finally {{");
    let _ = writeln!(out, "    busy.value = false;");
    let _ = writeln!(out, "    draft.value = '';");
    let _ = writeln!(out, "  }}");
    let _ = writeln!(out, "}}");
    let _ = writeln!(out, "</script>");
    let _ = writeln!(out);
    let _ = writeln!(out, "<style scoped>");
    let _ = writeln!(out, ".{camel}-chat {{ display: flex; flex-direction: column; gap: 8px; padding: 16px; height: calc(100vh - 120px); }}");
    let _ = writeln!(out, ".msg.user {{ align-self: flex-end; background: var(--el-color-primary-light-9); }}");
    let _ = writeln!(out, ".msg.assistant {{ align-self: flex-start; background: var(--el-fill-color-light); }}");
    let _ = writeln!(out, "</style>");
    let _ = writeln!(out, "// route: /{plural}/chat");
    out
}

fn ts_api(plural: &str, pascal: &str) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "// Generated by mox-platform-meta-core codegen (TPL-06)");
    let _ = writeln!(out, "import {{ http }} from './http';");
    let _ = writeln!(out);
    let _ = writeln!(out, "export interface ChatMessage {{ role: 'user' | 'assistant'; content: string; }}");
    let _ = writeln!(out);
    let _ = writeln!(out, "const BASE = '/api/ai/{plural}';");
    let _ = writeln!(out);
    let _ = writeln!(out, "export function chat{pascal}(messages: ChatMessage[]) {{");
    let _ = writeln!(out, "  return http.post(`${{BASE}}/chat`, {{ messages }});");
    let _ = writeln!(out, "}}");
    out
}

fn router(pascal: &str, plural: &str, camel: &str) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "// Generated by mox-platform-meta-core codegen (TPL-06)");
    let _ = writeln!(out, "import type {{ RouteRecordRaw }} from 'vue-router';");
    let _ = writeln!(out, "import {pascal}Chat from '../vue/{pascal}Chat.vue';");
    let _ = writeln!(out);
    let _ = writeln!(out, "export const {camel}Routes: RouteRecordRaw[] = [");
    let _ = writeln!(out, "  {{ path: '/{plural}/chat', name: '{camel}Chat', component: {pascal}Chat }},");
    let _ = writeln!(out, "];");
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{MetaEntity, MetaField};

    fn ent() -> EntityWithFields {
        let e = MetaEntity {
            entity_id: "ent_contract".into(),
            tenant_id: "t001".into(),
            entity_code: "contract".into(),
            entity_name: "合同".into(),
            entity_plural: None,
            table_name: None,
            description: None,
            icon: None,
            color: None,
            entity_category: "business".into(),
            storage_mode: "ext_slot".into(),
            shard_key: None,
            history_strategy: "none".into(),
            extends_entity_id: None,
            mixin_ids: None,
            tags: None,
            list_view_id: None,
            form_view_id: None,
            detail_view_id: None,
            workflow_id: None,
            is_system: 0,
            status: "active".into(),
            metadata: None,
            created_at: "2026-09-04T00:00:00Z".into(),
            updated_at: "2026-09-04T00:00:00Z".into(),
            created_by: None,
            updated_by: None,
            deleted_at: None,
            deleted_by: None,
            version: 1,
            _hash: None,
        };
        let f = MetaField {
            field_id: "fld_title".into(),
            tenant_id: "t001".into(),
            entity_id: "ent_contract".into(),
            field_code: "title".into(),
            field_name: "标题".into(),
            field_type: "string".into(),
            is_required: 1,
            is_unique: 0,
            is_indexed: 1,
            is_searchable: 1,
            is_sortable: 1,
            is_filterable: 0,
            is_exportable: 1,
            is_importable: 1,
            is_readonly: 0,
            is_hidden: 0,
            is_system: 0,
            default_value: None,
            default_expr: None,
            auto_fill_on: None,
            max_length: None,
            min_value: None,
            max_value: None,
            decimal_places: None,
            step: None,
            currency_code: None,
            unit: None,
            options_source: "none".into(),
            options_inline: None,
            options_sql: None,
            options_api: None,
            options_dict_code: None,
            relation_config: None,
            validations: None,
            formula_expr: None,
            formula_deps: None,
            ui_component: None,
            ui_props: None,
            ui_placeholder: None,
            ui_hint: None,
            ui_group: None,
            ui_sort_order: 0,
            ui_span: 1,
            ui_newline: 0,
            ui_dynamic_cond: None,
            field_permission: None,
            storage_slot: None,
            description: None,
            tags: None,
            status: "active".into(),
            metadata: None,
            created_at: "2026-09-04T00:00:00Z".into(),
            updated_at: "2026-09-04T00:00:00Z".into(),
            created_by: None,
            updated_by: None,
            deleted_at: None,
            deleted_by: None,
            version: 1,
            _hash: None,
        };
        EntityWithFields { entity: e, fields: vec![f], slot_map: Default::default() }
    }

    #[test]
    fn test_ai_chat_artifacts_complete_and_deterministic() {
        let a = generate_ai_chat(&ent(), "TPL-06").expect("ok");
        for path in ["vue/ContractChat.vue", "ts/api.ts", "router/contracts.ts", "menu.json"] {
            assert!(a.artifacts.contains_key(path), "missing {path}");
        }
        assert!(a.artifacts["ts/api.ts"].contains("const BASE = '/api/ai/contracts'"));
        assert!(a.artifacts["ts/api.ts"].contains("${BASE}/chat"));
        assert!(a.artifacts["vue/ContractChat.vue"].contains("合同"));
        assert_eq!(a, generate_ai_chat(&ent(), "TPL-06").expect("b"), "deterministic");
    }
}
