// Copyright (c) 2026 璇玑 RelGraph · 算子统一系统 (OUS) · 三联盟
// Licensed under the MIT License.
// GitHub 主仓: https://github.com/aikjx/mox.git
// GitCode 镜像: https://gitcode.com/aikjx/mox

//! TPL-02 树表模板：父子层级实体 → DDL(parent_id) / Rust 模型 / 树 API / 树页面 / 路由 / 菜单。

use std::collections::BTreeMap;
use std::fmt::Write as _;

use super::naming;
use super::tpl_crud::menu_json;
use super::{CodegenError, CodegenOutput};
use crate::model::{EntityWithFields, MetaField};

pub fn generate_tree(
    entity: &EntityWithFields,
    tpl_code: &str,
) -> Result<CodegenOutput, CodegenError> {
    let ent = &entity.entity;
    let pascal = naming::to_pascal(&ent.entity_code);
    let camel = naming::to_camel(&ent.entity_code);
    let plural = ent
        .entity_plural
        .clone()
        .unwrap_or_else(|| naming::pluralize(&ent.entity_code));
    let table = ent
        .table_name
        .clone()
        .unwrap_or_else(|| format!("biz_{}", ent.entity_code));
    let visible: Vec<&MetaField> = entity.fields.iter().filter(|f| f.is_hidden == 0).collect();

    let mut artifacts = BTreeMap::new();
    artifacts.insert(format!("ddl/{table}.sql"), ddl(&table, &visible));
    artifacts.insert(format!("rust/{pascal}.rs"), rust_model(&pascal, &visible));
    artifacts.insert("ts/api.ts".to_string(), ts_api(&plural, &pascal, &visible));
    artifacts.insert(
        format!("vue/{pascal}Tree.vue"),
        tree_vue(&pascal, &camel, &plural),
    );
    artifacts.insert(
        format!("router/{plural}.ts"),
        router(&pascal, &plural, &camel),
    );
    artifacts.insert("menu.json".to_string(), menu_json(ent, &plural, tpl_code));

    Ok(CodegenOutput {
        entity_code: ent.entity_code.clone(),
        template: tpl_code.to_string(),
        artifacts,
    })
}

fn ddl(table: &str, fields: &[&MetaField]) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "-- Generated by mox-platform-meta-core codegen (TPL-02)");
    let _ = writeln!(out, "CREATE TABLE {table} (");
    let _ = writeln!(out, "  id TEXT PRIMARY KEY,");
    let _ = writeln!(out, "  tenant_id TEXT NOT NULL,");
    let _ = writeln!(out, "  parent_id TEXT NOT NULL,");
    for f in fields {
        let req = if f.is_required == 1 { " NOT NULL" } else { "" };
        let _ = writeln!(out, "  {} {}{req},", f.field_code, naming::sql_type(&f.field_type));
    }
    let _ = writeln!(out, "  sort_order INTEGER NOT NULL DEFAULT 0,");
    let _ = writeln!(out, "  created_at TEXT NOT NULL,");
    let _ = writeln!(out, "  updated_at TEXT NOT NULL");
    let _ = writeln!(out, ");");
    let _ = writeln!(out, "CREATE INDEX idx_{table}_parent ON {table} (parent_id);");
    out
}

fn rust_model(pascal: &str, fields: &[&MetaField]) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "// Generated by mox-platform-meta-core codegen (TPL-02)");
    let _ = writeln!(out, "use serde::{{Deserialize, Serialize}};");
    let _ = writeln!(out);
    let _ = writeln!(out, "#[derive(Debug, Clone, Serialize, Deserialize)]");
    let _ = writeln!(out, "pub struct {pascal} {{");
    let _ = writeln!(out, "    pub id: String,");
    let _ = writeln!(out, "    pub tenant_id: String,");
    let _ = writeln!(out, "    pub parent_id: String,");
    for f in fields {
        let ty = naming::rust_type(&f.field_type);
        let opt = if f.is_required == 1 { "" } else { "Option<" };
        let close = if f.is_required == 1 { "" } else { ">" };
        let _ = writeln!(out, "    pub {}: {opt}{ty}{close},", f.field_code);
    }
    let _ = writeln!(out, "    pub sort_order: i64,");
    let _ = writeln!(out, "    pub children: Vec<{pascal}>,");
    let _ = writeln!(out, "    pub created_at: String,");
    let _ = writeln!(out, "    pub updated_at: String,");
    let _ = writeln!(out, "}}");
    out
}

fn ts_api(plural: &str, pascal: &str, fields: &[&MetaField]) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "// Generated by mox-platform-meta-core codegen (TPL-02)");
    let _ = writeln!(out, "import {{ http }} from './http';");
    let _ = writeln!(out);
    let _ = writeln!(out, "export interface {pascal} {{");
    let _ = writeln!(out, "  id: string;");
    let _ = writeln!(out, "  parent_id: string;");
    for f in fields {
        let opt = if f.is_required == 1 { "" } else { "?" };
        let _ = writeln!(out, "  {}{opt}: {};", f.field_code, naming::ts_type(&f.field_type));
    }
    let _ = writeln!(out, "  sort_order: number;");
    let _ = writeln!(out, "  children: {pascal}[];");
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);
    let _ = writeln!(out, "const BASE = '/api/biz/{plural}';");
    let _ = writeln!(out);
    let _ = writeln!(out, "export function tree{pascal}() {{");
    let _ = writeln!(out, "  return http.get(`${{BASE}}/tree`);");
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);
    let _ = writeln!(out, "export function move{pascal}(id: string, newParentId: string) {{");
    let _ = writeln!(out, "  return http.post(`${{BASE}}/${{id}}/move`, {{ parent_id: newParentId }});");
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);
    let _ = writeln!(out, "export function create{pascal}(data: Partial<{pascal}>) {{");
    let _ = writeln!(out, "  return http.post(BASE, data);");
    let _ = writeln!(out, "}}");
    out
}

fn tree_vue(pascal: &str, camel: &str, plural: &str) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "<!-- Generated by mox-platform-meta-core codegen (TPL-02) -->");
    let _ = writeln!(out, "<template>");
    let _ = writeln!(out, "  <div class=\"{camel}-tree\">");
    let _ = writeln!(out, "    <el-tree :data=\"tree\" node-key=\"id\" default-expand-all draggable");
    let _ = writeln!(out, "              @node-drop=\"onDrop\">");
    let _ = writeln!(out, "      <template #default=\"{{ data }}\">");
    let _ = writeln!(out, "        <span>{{{{ data.name }}}}</span>");
    let _ = writeln!(out, "      </template>");
    let _ = writeln!(out, "    </el-tree>");
    let _ = writeln!(out, "  </div>");
    let _ = writeln!(out, "</template>");
    let _ = writeln!(out);
    let _ = writeln!(out, "<script setup lang=\"ts\">");
    let _ = writeln!(out, "import {{ onMounted, ref }} from 'vue';");
    let _ = writeln!(out, "import {{ tree{pascal}, move{pascal}, type {pascal} }} from '../ts/api';");
    let _ = writeln!(out);
    let _ = writeln!(out, "const tree = ref<{pascal}[]>([]);");
    let _ = writeln!(out);
    let _ = writeln!(out, "async function onDrop(drag: {pascal}, target: {pascal} | null) {{");
    let _ = writeln!(out, "  await move{pascal}(drag.id, target?.id ?? '');");
    let _ = writeln!(out, "  tree.value = await tree{pascal}();");
    let _ = writeln!(out, "}}");
    let _ = writeln!(out);
    let _ = writeln!(out, "onMounted(async () => {{ tree.value = await tree{pascal}(); }});");
    let _ = writeln!(out, "</script>");
    let _ = writeln!(out);
    let _ = writeln!(out, "<style scoped>");
    let _ = writeln!(out, ".{camel}-tree {{ padding: 16px; }}");
    let _ = writeln!(out, "</style>");
    let _ = writeln!(out, "// route: /{plural}/tree");
    out
}

fn router(pascal: &str, plural: &str, camel: &str) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "// Generated by mox-platform-meta-core codegen (TPL-02)");
    let _ = writeln!(out, "import type {{ RouteRecordRaw }} from 'vue-router';");
    let _ = writeln!(out, "import {pascal}Tree from '../vue/{pascal}Tree.vue';");
    let _ = writeln!(out);
    let _ = writeln!(out, "export const {camel}Routes: RouteRecordRaw[] = [");
    let _ = writeln!(out, "  {{ path: '/{plural}/tree', name: '{camel}Tree', component: {pascal}Tree }},");
    let _ = writeln!(out, "];");
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{MetaEntity, MetaField};

    fn ent() -> EntityWithFields {
        let e = MetaEntity {
            entity_id: "ent_dept".into(),
            tenant_id: "t001".into(),
            entity_code: "department".into(),
            entity_name: "部门".into(),
            entity_plural: None,
            table_name: None,
            description: None,
            icon: Some("office-building".into()),
            color: None,
            entity_category: "business".into(),
            storage_mode: "ext_slot".into(),
            shard_key: None,
            history_strategy: "none".into(),
            extends_entity_id: None,
            mixin_ids: None,
            tags: None,
            list_view_id: None,
            form_view_id: None,
            detail_view_id: None,
            workflow_id: None,
            is_system: 0,
            status: "active".into(),
            metadata: None,
            created_at: "2026-09-04T00:00:00Z".into(),
            updated_at: "2026-09-04T00:00:00Z".into(),
            created_by: None,
            updated_by: None,
            deleted_at: None,
            deleted_by: None,
            version: 1,
            _hash: None,
        };
        let f = MetaField {
            field_id: "fld_name".into(),
            tenant_id: "t001".into(),
            entity_id: "ent_dept".into(),
            field_code: "dept_name".into(),
            field_name: "部门名称".into(),
            field_type: "string".into(),
            is_required: 1,
            is_unique: 0,
            is_indexed: 0,
            is_searchable: 1,
            is_sortable: 1,
            is_filterable: 0,
            is_exportable: 1,
            is_importable: 1,
            is_readonly: 0,
            is_hidden: 0,
            is_system: 0,
            default_value: None,
            default_expr: None,
            auto_fill_on: None,
            max_length: None,
            min_value: None,
            max_value: None,
            decimal_places: None,
            step: None,
            currency_code: None,
            unit: None,
            options_source: "none".into(),
            options_inline: None,
            options_sql: None,
            options_api: None,
            options_dict_code: None,
            relation_config: None,
            validations: None,
            formula_expr: None,
            formula_deps: None,
            ui_component: None,
            ui_props: None,
            ui_placeholder: None,
            ui_hint: None,
            ui_group: None,
            ui_sort_order: 0,
            ui_span: 1,
            ui_newline: 0,
            ui_dynamic_cond: None,
            field_permission: None,
            storage_slot: None,
            description: None,
            tags: None,
            status: "active".into(),
            metadata: None,
            created_at: "2026-09-04T00:00:00Z".into(),
            updated_at: "2026-09-04T00:00:00Z".into(),
            created_by: None,
            updated_by: None,
            deleted_at: None,
            deleted_by: None,
            version: 1,
            _hash: None,
        };
        EntityWithFields { entity: e, fields: vec![f], slot_map: Default::default() }
    }

    #[test]
    fn test_tree_artifacts_complete_and_deterministic() {
        let a = generate_tree(&ent(), "TPL-02").expect("ok");
        for path in [
            "ddl/biz_department.sql",
            "rust/Department.rs",
            "ts/api.ts",
            "vue/DepartmentTree.vue",
            "router/departments.ts",
            "menu.json",
        ] {
            assert!(a.artifacts.contains_key(path), "missing {path}");
        }
        assert!(a.artifacts["ddl/biz_department.sql"].contains("parent_id TEXT NOT NULL"));
        assert!(a.artifacts["rust/Department.rs"].contains("pub children: Vec<Department>"));
        assert!(a.artifacts["ts/api.ts"].contains("/tree"));
        assert_eq!(a, generate_tree(&ent(), "TPL-02").expect("b"), "deterministic");
    }
}
