[package]
name = "mox-flow-operator-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
mox-platform-foundation = { path = "../../../foundation/mox-platform-foundation" }
serde = { workspace = true }
async-trait = { workspace = true }

[dev-dependencies]



