[package]
name = "mox-platform-system-svc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
mox-platform-foundation = { path = "../../../foundation/mox-platform-foundation" }
mox-platform-api = { path = "../../../api/mox-platform-api" }
async-trait = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]



