-- =============================================================================
-- ⚠ 已废弃 / 已合并 —— 不要单独安装本文件
-- =============================================================================
-- 本文件原是“模式 B 增量扩展包”，重复定义了 14 张已存在于
-- mox_sys-universal-template.sql 的表（sys_resource / sys_policy / sys_relation /
-- sys_user_mfa / sys_audit_change / sys_inbox_event / sys_feature_flag* /
-- sys_i18n_* / sys_plan* / sys_usage_meter / sys_webhook）。
--
-- 为消除“重复设计”，这 14 张表的定义已并入唯一权威母版：
--     mox_sys/mox_sys-universal-template.sql   （单一归一化 DDL，含全部 56 张表）
--
-- 一键安装只需执行该单一文件，详见同目录 install.sql / install.ps1。
-- 本文件仅保留作历史指针，不再包含任何可执行 DDL。
-- =============================================================================
