@echo off
chcp 65001 >nul
cd /d "d:\a10\aikjx\gitcode\infotopograph\docs\enterprise"
ren "11-mox 模块化系统架构测试验证优化修复报告.md" "11-MOX测试验证优化修复报告.md"
ren "14-mox 模块化系统架构愿景核心架构与业务流程总纲.md" "14-MOX愿景核心架构与业务流程总纲.md"
ren "15-产品规范标准-人人爱用全自动mox 模块化系统架构-V1.0.md" "15-产品规范标准-人人爱用全自动MOX-V1.0.md"
ren "17-算子系统mox 模块化系统架构分析与归一化设计.md" "17-算子系统MOX分析与归一化设计.md"
ren "23-竞品mox 模块化系统架构功能对比与可用性判定报告-V1.0.md" "23-竞品MOX功能对比与可用性判定报告-V1.0.md"
ren "27-企业级测试与评测主控提示词与mox 模块化系统架构自动化测试报告-V1.0.md" "27-企业级测试与评测主控提示词与MOX自动化测试报告-V1.0.md"
ren "28-mox 模块化系统架构分析与文档归一化报告-V1.0.md" "28-MOX分析与文档归一化报告-V1.0.md"
ren "MOX-AI驱动mox 模块化系统架构平台-企业级设计-mox 模块化系统架构分析-v3.0.md" "MOX-AI驱动MOX平台-企业级设计-MOX分析-v3.0.md"
cd /d "d:\a10\aikjx\gitcode\infotopograph\docs\enterprise"
if exist "14-mox 模块化系统架构愿景核心架构与业务流程总纲.html" ren "14-mox 模块化系统架构愿景核心架构与业务流程总纲.html" "14-MOX愿景核心架构与业务流程总纲.html"
if exist "15-产品规范标准-人人爱用全自动mox 模块化系统架构-V1.0.html" ren "15-产品规范标准-人人爱用全自动mox 模块化系统架构-V1.0.html" "15-产品规范标准-人人爱用全自动MOX-V1.0.html"
cd /d "d:\a10\aikjx\gitcode\infotopograph\docs\modules"
ren "对话开发系统-mox 模块化系统架构分析与业务流程图.md" "对话开发系统-MOX分析与业务流程图.md"
if exist "专家联盟-mox 模块化系统架构业务流程归一化手册-V1.0.md" ren "专家联盟-mox 模块化系统架构业务流程归一化手册-V1.0.md" "专家联盟-MOX业务流程归一化手册-V1.0.md"
echo DONE > "d:\a10\aikjx\gitcode\infotopograph\scripts\rename-bat-done.txt"
