-- mox v3.0 relational baseline
-- Target: MySQL 8.3+, InnoDB, utf8mb4
-- IDs: application-generated UUID v7 stored as BINARY(16)
-- Time: UTC DATETIME(3); API adapters may expose epoch milliseconds
-- This is a clean schema. It intentionally creates mox_v3, never drops legacy.

SET NAMES utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS `mox_v3`
  CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE `mox_v3`;
SET sql_mode = 'STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- 01. Tenant and organisation foundation
CREATE TABLE `sys_tenant` (
  `id` BINARY(16) NOT NULL COMMENT 'UUID v7',
  `tenant_code` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `tenant_name` VARCHAR(160) NOT NULL,
  `tenant_mode` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'L' COMMENT 'L logical, P physical, H hybrid',
  `status` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'A' COMMENT 'A active, I inactive, D disabled',
  `plan_code` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'FREE',
  `data_region` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `timezone` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'UTC',
  `locale` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'zh-CN',
  `settings` JSON DEFAULT NULL,
  `created_at` BINARY(16) DEFAULT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` BINARY(16) DEFAULT NULL,
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted_at` DATETIME(3) DEFAULT NULL,
  `deleted_by` BINARY(16) DEFAULT NULL,
  `row_version` BIGINT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_code` (`tenant_code`),
  KEY `idx_tenant_status` (`status`, `updated_at`),
  CONSTRAINT `chk_tenant_mode` CHECK (`tenant_mode` IN ('L','P','H')),
  CONSTRAINT `chk_tenant_status` CHECK (`status` IN ('A','I','D'))
) ENGINE=InnoDB COMMENT='租户主表';

CREATE TABLE `sys_enterprise` (
  `id` BINARY(16) NOT NULL,
  `tenant_id` BINARY(16) NOT NULL,
  `enterprise_code` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `enterprise_name` VARCHAR(200) NOT NULL,
  `legal_name` VARCHAR(200) DEFAULT NULL,
  `registration_no` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `enterprise_type` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'COMPANY',
  `status` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'A',
  `is_default` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'N',
  `profile` JSON DEFAULT NULL,
  `created_at` BINARY(16) DEFAULT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` BINARY(16) DEFAULT NULL, `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted_at` DATETIME(3) DEFAULT NULL, `deleted_by` BINARY(16) DEFAULT NULL, `row_version` BIGINT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_enterprise_code` (`tenant_id`,`enterprise_code`),
  KEY `idx_enterprise_status` (`tenant_id`,`status`,`updated_at`),
  KEY `idx_enterprise_reg_no` (`tenant_id`,`registration_no`)
) ENGINE=InnoDB COMMENT='租户内企业主体';

CREATE TABLE `sys_org_unit` (
  `id` BINARY(16) NOT NULL,
  `tenant_id` BINARY(16) NOT NULL,
  `enterprise_id` BINARY(16) NOT NULL,
  `parent_id` BINARY(16) DEFAULT NULL,
  `org_code` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `org_name` VARCHAR(160) NOT NULL,
  `org_type` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'DEPT' COMMENT 'ROOT, COMPANY, DEPT, TEAM, VIRTUAL',
  `path_key` VARCHAR(2000) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `level_no` INT UNSIGNED NOT NULL DEFAULT 0,
  `sort_no` INT NOT NULL DEFAULT 0,
  `manager_id` BINARY(16) DEFAULT NULL,
  `status` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'A',
  `created_at` BINARY(16) DEFAULT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` BINARY(16) DEFAULT NULL, `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted_at` DATETIME(3) DEFAULT NULL, `deleted_by` BINARY(16) DEFAULT NULL, `row_version` BIGINT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_org_code` (`tenant_id`,`enterprise_id`,`org_code`),
  KEY `idx_org_parent` (`tenant_id`,`enterprise_id`,`parent_id`,`sort_no`),
  KEY `idx_org_path` (`tenant_id`,`enterprise_id`,`path_key`(191)),
  CONSTRAINT `chk_org_status` CHECK (`status` IN ('A','I','D'))
) ENGINE=InnoDB COMMENT='企业组织树节点';

CREATE TABLE `sys_user` (
  `id` BINARY(16) NOT NULL,
  `login_name` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `display_name` VARCHAR(160) NOT NULL,
  `email` VARCHAR(254) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `phone` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `password_hash` VARBINARY(255) DEFAULT NULL COMMENT '只存 Argon2id/bcrypt 摘要',
  `user_type` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'PERSON',
  `status` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'A',
  `locale` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'zh-CN',
  `timezone` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'UTC',
  `avatar_object_id` BINARY(16) DEFAULT NULL,
  `last_login_at` DATETIME(3) DEFAULT NULL, `last_login_ip` VARBINARY(16) DEFAULT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted_at` DATETIME(3) DEFAULT NULL, `deleted_by` BINARY(16) DEFAULT NULL, `row_version` BIGINT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`), UNIQUE KEY `uk_user_login` (`login_name`),
  KEY `idx_user_email` (`email`), KEY `idx_user_status` (`status`,`updated_at`),
  CONSTRAINT `chk_user_status` CHECK (`status` IN ('A','I','D'))
) ENGINE=InnoDB COMMENT='全局身份主体';

CREATE TABLE `sys_tenant_member` (
  `id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) NOT NULL, `user_id` BINARY(16) NOT NULL,
  `member_code` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `member_type` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'USER',
  `status` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'A',
  `is_owner` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'N',
  `default_enterprise_id` BINARY(16) DEFAULT NULL, `default_org_unit_id` BINARY(16) DEFAULT NULL,
  `joined_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `expires_at` DATETIME(3) DEFAULT NULL,
  `created_at` BINARY(16) DEFAULT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted_at` DATETIME(3) DEFAULT NULL, `deleted_by` BINARY(16) DEFAULT NULL, `row_version` BIGINT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`), UNIQUE KEY `uk_member_tenant_user` (`tenant_id`,`user_id`),
  KEY `idx_member_user` (`user_id`,`status`), KEY `idx_member_tenant_status` (`tenant_id`,`status`),
  CONSTRAINT `chk_member_status` CHECK (`status` IN ('A','I','D'))
) ENGINE=InnoDB COMMENT='用户与租户成员关系';

CREATE TABLE `sys_org_member` (
  `id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) NOT NULL, `enterprise_id` BINARY(16) NOT NULL,
  `org_unit_id` BINARY(16) NOT NULL, `member_id` BINARY(16) NOT NULL,
  `relation_type` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'MEMBER',
  `is_primary` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'N',
  `valid_from` DATETIME(3) DEFAULT NULL, `valid_to` DATETIME(3) DEFAULT NULL,
  `created_at` BINARY(16) DEFAULT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `deleted_at` DATETIME(3) DEFAULT NULL,
  PRIMARY KEY (`id`), UNIQUE KEY `uk_org_member` (`org_unit_id`,`member_id`),
  KEY `idx_org_member_tenant` (`tenant_id`,`enterprise_id`,`org_unit_id`), KEY `idx_member_org` (`tenant_id`,`member_id`)
) ENGINE=InnoDB COMMENT='成员与企业部门多对多关系';

CREATE TABLE `sys_post` (
  `id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) NOT NULL, `post_code` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `post_name` VARCHAR(120) NOT NULL,
  `post_level` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL, `status` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'A', `sort_no` INT NOT NULL DEFAULT 0,
  `created_at` BINARY(16) DEFAULT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_by` BINARY(16) DEFAULT NULL, `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), `deleted_at` DATETIME(3) DEFAULT NULL, `deleted_by` BINARY(16) DEFAULT NULL, `row_version` BIGINT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`), UNIQUE KEY `uk_post_code` (`tenant_id`,`post_code`), KEY `idx_post_status` (`tenant_id`,`status`,`sort_no`)
) ENGINE=InnoDB COMMENT='租户岗位';

CREATE TABLE `sys_member_post` (
  `id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) NOT NULL, `member_id` BINARY(16) NOT NULL, `post_id` BINARY(16) NOT NULL, `is_primary` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'N', `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `deleted_at` DATETIME(3) DEFAULT NULL,
  PRIMARY KEY (`id`), UNIQUE KEY `uk_member_post` (`member_id`,`post_id`), KEY `idx_post_member` (`tenant_id`,`post_id`,`member_id`)
) ENGINE=InnoDB COMMENT='成员岗位关系';

-- 02. IAM, menus, identity federation and settings
CREATE TABLE `sys_role` (
  `id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) NOT NULL, `role_code` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `role_name` VARCHAR(120) NOT NULL,
  `role_type` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'CUSTOM', `data_scope` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'S' COMMENT 'S self, D dept, E enterprise, T tenant, C custom', `status` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'A', `sort_no` INT NOT NULL DEFAULT 0,
  `created_at` BINARY(16) DEFAULT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_by` BINARY(16) DEFAULT NULL, `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), `deleted_at` DATETIME(3) DEFAULT NULL, `deleted_by` BINARY(16) DEFAULT NULL, `row_version` BIGINT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`), UNIQUE KEY `uk_role_code` (`tenant_id`,`role_code`), KEY `idx_role_scope` (`tenant_id`,`data_scope`,`status`),
  CONSTRAINT `chk_role_scope` CHECK (`data_scope` IN ('S','D','E','T','C'))
) ENGINE=InnoDB COMMENT='租户角色';

CREATE TABLE `sys_permission` (
  `id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) NOT NULL, `perm_code` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `perm_name` VARCHAR(160) NOT NULL,
  `resource_type` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `action_code` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `status` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'A', `description` VARCHAR(500) DEFAULT NULL,
  `created_at` BINARY(16) DEFAULT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), `deleted_at` DATETIME(3) DEFAULT NULL,
  PRIMARY KEY (`id`), UNIQUE KEY `uk_perm_code` (`tenant_id`,`perm_code`), KEY `idx_perm_resource` (`tenant_id`,`resource_type`,`action_code`)
) ENGINE=InnoDB COMMENT='资源操作权限';

CREATE TABLE `sys_user_role` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) NOT NULL, `member_id` BINARY(16) NOT NULL, `role_id` BINARY(16) NOT NULL, `assigned_by` BINARY(16) DEFAULT NULL, `assigned_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `deleted_at` DATETIME(3) DEFAULT NULL, PRIMARY KEY (`id`), UNIQUE KEY `uk_user_role` (`member_id`,`role_id`), KEY `idx_role_member` (`tenant_id`,`role_id`,`member_id`)) ENGINE=InnoDB COMMENT='成员角色关系';
CREATE TABLE `sys_role_permission` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) NOT NULL, `role_id` BINARY(16) NOT NULL, `permission_id` BINARY(16) NOT NULL, `created_at` BINARY(16) DEFAULT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `deleted_at` DATETIME(3) DEFAULT NULL, PRIMARY KEY (`id`), UNIQUE KEY `uk_role_perm` (`role_id`,`permission_id`), KEY `idx_perm_role` (`tenant_id`,`permission_id`,`role_id`)) ENGINE=InnoDB COMMENT='角色权限关系';
CREATE TABLE `sys_role_org_scope` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) NOT NULL, `role_id` BINARY(16) NOT NULL, `enterprise_id` BINARY(16) DEFAULT NULL, `org_unit_id` BINARY(16) DEFAULT NULL, `scope_mode` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'I' COMMENT 'I include, X exclude', `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `deleted_at` DATETIME(3) DEFAULT NULL, PRIMARY KEY (`id`), KEY `idx_role_org_scope` (`tenant_id`,`role_id`,`enterprise_id`,`org_unit_id`)) ENGINE=InnoDB COMMENT='角色组织数据范围';

CREATE TABLE `sys_menu` (
  `id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) DEFAULT NULL COMMENT 'NULL 表示平台菜单', `tenant_scope_id` BINARY(16) GENERATED ALWAYS AS (COALESCE(`tenant_id`,UNHEX('00000000000000000000000000000000'))) STORED, `parent_id` BINARY(16) DEFAULT NULL, `menu_code` VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `menu_name` VARCHAR(160) NOT NULL,
  `menu_type` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'MENU' COMMENT 'DIR, MENU, BUTTON, API', `route_path` VARCHAR(500) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL, `component` VARCHAR(500) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL, `icon` VARCHAR(160) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL, `sort_no` INT NOT NULL DEFAULT 0, `is_visible` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'Y', `permission_code` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL, `config` JSON DEFAULT NULL, `status` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'A',
  `created_at` BINARY(16) DEFAULT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), `deleted_at` DATETIME(3) DEFAULT NULL,
  PRIMARY KEY (`id`), UNIQUE KEY `uk_menu_code` (`tenant_scope_id`,`menu_code`), KEY `idx_menu_parent` (`tenant_id`,`parent_id`,`sort_no`)
) ENGINE=InnoDB COMMENT='平台和租户菜单';
CREATE TABLE `sys_role_menu` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) NOT NULL, `role_id` BINARY(16) NOT NULL, `menu_id` BINARY(16) NOT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `deleted_at` DATETIME(3) DEFAULT NULL, PRIMARY KEY (`id`), UNIQUE KEY `uk_role_menu` (`role_id`,`menu_id`), KEY `idx_menu_role` (`tenant_id`,`menu_id`,`role_id`)) ENGINE=InnoDB COMMENT='角色菜单关系';

CREATE TABLE `sys_identity_provider` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) DEFAULT NULL, `tenant_scope_id` BINARY(16) GENERATED ALWAYS AS (COALESCE(`tenant_id`,UNHEX('00000000000000000000000000000000'))) STORED, `provider_code` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `provider_type` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'OIDC, SAML, LDAP, WECHAT, DINGTALK', `display_name` VARCHAR(120) NOT NULL, `config_ciphertext` VARBINARY(8192) NOT NULL, `status` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'A', `created_at` BINARY(16) DEFAULT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), `deleted_at` DATETIME(3) DEFAULT NULL, PRIMARY KEY (`id`), UNIQUE KEY `uk_idp_code` (`tenant_scope_id`,`provider_code`), KEY `idx_idp_type` (`tenant_id`,`provider_type`,`status`)) ENGINE=InnoDB COMMENT='SSO/LDAP 身份提供商';
CREATE TABLE `sys_user_identity` (`id` BINARY(16) NOT NULL, `provider_id` BINARY(16) NOT NULL, `user_id` BINARY(16) NOT NULL, `external_subject` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, `claims` JSON DEFAULT NULL, `last_seen_at` DATETIME(3) DEFAULT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `deleted_at` DATETIME(3) DEFAULT NULL, PRIMARY KEY (`id`), UNIQUE KEY `uk_identity_subject` (`provider_id`,`external_subject`), KEY `idx_identity_user` (`user_id`)) ENGINE=InnoDB COMMENT='外部身份到本地用户映射';
CREATE TABLE `sys_session` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) DEFAULT NULL, `user_id` BINARY(16) NOT NULL, `session_hash` BINARY(32) NOT NULL, `ip_addr` VARBINARY(16) DEFAULT NULL, `user_agent` VARCHAR(1000) DEFAULT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `last_seen_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `expires_at` DATETIME(3) NOT NULL, `revoked_at` DATETIME(3) DEFAULT NULL, PRIMARY KEY (`id`), UNIQUE KEY `uk_session_hash` (`session_hash`), KEY `idx_session_user` (`user_id`,`revoked_at`,`expires_at`)) ENGINE=InnoDB COMMENT='登录会话（只存摘要）';
CREATE TABLE `sys_api_key` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) NOT NULL, `member_id` BINARY(16) DEFAULT NULL, `key_name` VARCHAR(120) NOT NULL, `key_prefix` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `key_hash` BINARY(32) NOT NULL, `scopes` JSON DEFAULT NULL, `status` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'A', `expires_at` DATETIME(3) DEFAULT NULL, `last_used_at` DATETIME(3) DEFAULT NULL, `revoked_at` DATETIME(3) DEFAULT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), PRIMARY KEY (`id`), UNIQUE KEY `uk_api_key_hash` (`key_hash`), KEY `idx_api_key_tenant` (`tenant_id`,`status`,`expires_at`)) ENGINE=InnoDB COMMENT='租户 API 凭证';
CREATE TABLE `sys_setting` (`id` BINARY(16) NOT NULL, `scope_kind` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'G global, T tenant, E enterprise, U user', `scope_id` BINARY(16) DEFAULT NULL, `scope_key` BINARY(16) GENERATED ALWAYS AS (COALESCE(`scope_id`,UNHEX('00000000000000000000000000000000'))) STORED, `setting_key` VARCHAR(160) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `value_type` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'TEXT', `value_text` LONGTEXT DEFAULT NULL, `value_json` JSON DEFAULT NULL, `is_secret` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'N', `updated_by` BINARY(16) DEFAULT NULL, `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), PRIMARY KEY (`id`), UNIQUE KEY `uk_setting_scope_key` (`scope_kind`,`scope_key`,`setting_key`), KEY `idx_setting_key` (`setting_key`), CONSTRAINT `chk_setting_scope` CHECK ((`scope_kind` = 'G' AND `scope_id` IS NULL) OR (`scope_kind` IN ('T','E','U') AND `scope_id` IS NOT NULL))) ENGINE=InnoDB COMMENT='分层配置（全局/租户/企业/用户）';
CREATE TABLE `sys_enum_type` (`id` BINARY(16) NOT NULL, `enum_code` VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `enum_name` VARCHAR(120) NOT NULL, `is_system` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'N', `status` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'A', `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), PRIMARY KEY (`id`), UNIQUE KEY `uk_enum_code` (`enum_code`)) ENGINE=InnoDB COMMENT='枚举类型';
CREATE TABLE `sys_enum_item` (`id` BINARY(16) NOT NULL, `enum_id` BINARY(16) NOT NULL, `item_code` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `item_label` VARCHAR(120) NOT NULL, `sort_no` INT NOT NULL DEFAULT 0, `is_default` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'N', `status` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'A', `extra` JSON DEFAULT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), PRIMARY KEY (`id`), UNIQUE KEY `uk_enum_item` (`enum_id`,`item_code`), KEY `idx_enum_item_status` (`enum_id`,`status`,`sort_no`)) ENGINE=InnoDB COMMENT='枚举项';

-- 03. Audit, outbox, idempotency, files and licensing
CREATE TABLE `sys_audit_event` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) DEFAULT NULL, `request_id` BINARY(16) DEFAULT NULL, `trace_id` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL, `actor_user_id` BINARY(16) DEFAULT NULL, `actor_member_id` BINARY(16) DEFAULT NULL, `action_code` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `resource_type` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `resource_id` BINARY(16) DEFAULT NULL, `result_code` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'S', `ip_addr` VARBINARY(16) DEFAULT NULL, `user_agent` VARCHAR(1000) DEFAULT NULL, `changed_fields` JSON DEFAULT NULL, `before_data` JSON DEFAULT NULL, `after_data` JSON DEFAULT NULL, `prev_hash` BINARY(32) DEFAULT NULL, `event_hash` BINARY(32) NOT NULL, `occurred_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), PRIMARY KEY (`id`), UNIQUE KEY `uk_audit_hash` (`event_hash`), KEY `idx_audit_tenant_time` (`tenant_id`,`occurred_at`), KEY `idx_audit_resource` (`resource_type`,`resource_id`,`occurred_at`), KEY `idx_audit_actor` (`actor_user_id`,`occurred_at`)) ENGINE=InnoDB COMMENT='统一不可变审计事件';
CREATE TABLE `sys_outbox_event` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) DEFAULT NULL, `aggregate_type` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `aggregate_id` BINARY(16) NOT NULL, `event_type` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `payload` JSON NOT NULL, `event_key` VARCHAR(255) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `status` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'P' COMMENT 'P pending, R retrying, S sent, F dead', `attempts` INT UNSIGNED NOT NULL DEFAULT 0, `available_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `sent_at` DATETIME(3) DEFAULT NULL, `last_error` VARCHAR(2000) DEFAULT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), PRIMARY KEY (`id`), UNIQUE KEY `uk_outbox_event_key` (`event_key`), KEY `idx_outbox_dispatch` (`status`,`available_at`,`created_at`)) ENGINE=InnoDB COMMENT='事务消息 outbox';
CREATE TABLE `sys_idempotency_key` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) DEFAULT NULL, `actor_id` BINARY(16) DEFAULT NULL, `idempotency_key` VARCHAR(255) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `request_hash` BINARY(32) NOT NULL, `response_code` INT DEFAULT NULL, `response_body` JSON DEFAULT NULL, `status` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'P', `expires_at` DATETIME(3) NOT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), PRIMARY KEY (`id`), UNIQUE KEY `uk_idempotency_scope` (`tenant_id`,`actor_id`,`idempotency_key`), KEY `idx_idempotency_expire` (`expires_at`)) ENGINE=InnoDB COMMENT='幂等请求记录';
CREATE TABLE `sys_file_object` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) DEFAULT NULL, `bucket_name` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `object_key` VARCHAR(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, `file_name` VARCHAR(255) NOT NULL, `content_type` VARCHAR(255) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL, `size_bytes` BIGINT UNSIGNED NOT NULL, `sha256` BINARY(32) NOT NULL, `storage_class` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'STANDARD', `encryption_mode` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'SSE', `status` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'A', `created_at` BINARY(16) DEFAULT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `deleted_at` DATETIME(3) DEFAULT NULL, PRIMARY KEY (`id`), UNIQUE KEY `uk_file_hash` (`tenant_id`,`sha256`,`size_bytes`), KEY `idx_file_object` (`bucket_name`,`object_key`(191)), KEY `idx_file_tenant_time` (`tenant_id`,`created_at`)) ENGINE=InnoDB COMMENT='对象存储文件元数据';
CREATE TABLE `sys_file_link` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) DEFAULT NULL, `file_id` BINARY(16) NOT NULL, `resource_type` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `resource_id` BINARY(16) NOT NULL, `purpose_code` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'ATTACHMENT', `sort_no` INT NOT NULL DEFAULT 0, `created_at` BINARY(16) DEFAULT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `deleted_at` DATETIME(3) DEFAULT NULL, PRIMARY KEY (`id`), UNIQUE KEY `uk_file_link` (`file_id`,`resource_type`,`resource_id`,`purpose_code`), KEY `idx_link_resource` (`tenant_id`,`resource_type`,`resource_id`,`sort_no`)) ENGINE=InnoDB COMMENT='文件业务关联';
CREATE TABLE `sys_license` (`id` BINARY(16) NOT NULL, `license_code` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `subject_code` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `edition_code` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `features` JSON NOT NULL, `issued_at` DATETIME(3) NOT NULL, `expires_at` DATETIME(3) DEFAULT NULL, `signature` VARBINARY(4096) NOT NULL, `status` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'A', `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), PRIMARY KEY (`id`), UNIQUE KEY `uk_license_code` (`license_code`), KEY `idx_license_subject` (`subject_code`,`status`,`expires_at`)) ENGINE=InnoDB COMMENT='平台许可证';
CREATE TABLE `sys_sequence` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) DEFAULT NULL, `sequence_code` VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `current_value` BIGINT UNSIGNED NOT NULL DEFAULT 0, `step_no` INT UNSIGNED NOT NULL DEFAULT 1, `min_value` BIGINT UNSIGNED NOT NULL DEFAULT 1, `max_value` BIGINT UNSIGNED NOT NULL DEFAULT 18446744073709551615, `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), PRIMARY KEY (`id`), UNIQUE KEY `uk_sequence_scope` (`tenant_id`,`sequence_code`)) ENGINE=InnoDB COMMENT='业务序列号；取号必须在事务内 SELECT FOR UPDATE';

-- 04. Metadata and code generation (one canonical model)
CREATE TABLE `meta_connection` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) NOT NULL, `connection_code` VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `driver_code` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `endpoint` VARCHAR(500) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `credential_ref` VARCHAR(255) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `status` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'A', `last_test_at` DATETIME(3) DEFAULT NULL, `last_error` VARCHAR(2000) DEFAULT NULL, `created_at` BINARY(16) DEFAULT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), `deleted_at` DATETIME(3) DEFAULT NULL, PRIMARY KEY (`id`), UNIQUE KEY `uk_meta_conn_code` (`tenant_id`,`connection_code`), KEY `idx_meta_conn_status` (`tenant_id`,`status`)) ENGINE=InnoDB COMMENT='外部数据源连接';
CREATE TABLE `meta_catalog` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) NOT NULL, `connection_id` BINARY(16) NOT NULL, `catalog_name` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, `schema_name` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL, `last_scanned_at` DATETIME(3) DEFAULT NULL, `status` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'A', `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), `deleted_at` DATETIME(3) DEFAULT NULL, PRIMARY KEY (`id`), UNIQUE KEY `uk_meta_catalog` (`connection_id`,`catalog_name`,`schema_name`), KEY `idx_meta_catalog_tenant` (`tenant_id`,`status`)) ENGINE=InnoDB COMMENT='数据源目录';
CREATE TABLE `meta_table` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) NOT NULL, `catalog_id` BINARY(16) NOT NULL, `table_name` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, `table_comment` VARCHAR(500) DEFAULT NULL, `table_type` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'TABLE', `row_count_est` BIGINT UNSIGNED DEFAULT NULL, `sensitivity_code` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL, `last_scanned_at` DATETIME(3) DEFAULT NULL, `status` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'A', `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), `deleted_at` DATETIME(3) DEFAULT NULL, PRIMARY KEY (`id`), UNIQUE KEY `uk_meta_table_name` (`catalog_id`,`table_name`), KEY `idx_meta_table_tenant` (`tenant_id`,`status`)) ENGINE=InnoDB COMMENT='元数据表';
CREATE TABLE `meta_column` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) NOT NULL, `table_id` BINARY(16) NOT NULL, `column_name` VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, `ordinal_no` INT UNSIGNED NOT NULL, `data_type` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `is_nullable` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'Y', `is_pk` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'N', `is_sensitive` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'N', `length_no` INT UNSIGNED DEFAULT NULL, `scale_no` INT UNSIGNED DEFAULT NULL, `default_expr` VARCHAR(500) DEFAULT NULL, `comment_text` VARCHAR(500) DEFAULT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `deleted_at` DATETIME(3) DEFAULT NULL, PRIMARY KEY (`id`), UNIQUE KEY `uk_meta_column_name` (`table_id`,`column_name`), KEY `idx_meta_column_order` (`table_id`,`ordinal_no`)) ENGINE=InnoDB COMMENT='元数据列';
CREATE TABLE `meta_snapshot` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) NOT NULL, `catalog_id` BINARY(16) NOT NULL, `snapshot_no` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `schema_hash` BINARY(32) NOT NULL, `object_count` INT UNSIGNED NOT NULL DEFAULT 0, `status` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'S' COMMENT 'P processing, S success, F failed', `error_text` VARCHAR(2000) DEFAULT NULL, `started_at` DATETIME(3) NOT NULL, `finished_at` DATETIME(3) DEFAULT NULL, `created_at` BINARY(16) DEFAULT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), PRIMARY KEY (`id`), UNIQUE KEY `uk_meta_snapshot_no` (`catalog_id`,`snapshot_no`), KEY `idx_meta_snapshot_time` (`tenant_id`,`created_at`)) ENGINE=InnoDB COMMENT='元数据扫描快照';
CREATE TABLE `meta_entity` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) NOT NULL, `entity_code` VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `entity_name` VARCHAR(160) NOT NULL, `storage_mode` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'RELATIONAL', `physical_table_id` BINARY(16) DEFAULT NULL, `entity_type` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'MASTER', `status` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'A', `config` JSON DEFAULT NULL, `created_at` BINARY(16) DEFAULT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_by` BINARY(16) DEFAULT NULL, `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), `deleted_at` DATETIME(3) DEFAULT NULL, `row_version` BIGINT UNSIGNED NOT NULL DEFAULT 1, PRIMARY KEY (`id`), UNIQUE KEY `uk_meta_entity_code` (`tenant_id`,`entity_code`), KEY `idx_meta_entity_type` (`tenant_id`,`entity_type`,`status`)) ENGINE=InnoDB COMMENT='低代码实体定义';
CREATE TABLE `meta_field` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) NOT NULL, `entity_id` BINARY(16) NOT NULL, `field_code` VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `field_name` VARCHAR(160) NOT NULL, `field_type` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `is_required` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'N', `is_unique` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'N', `is_searchable` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'N', `default_value` JSON DEFAULT NULL, `validation` JSON DEFAULT NULL, `ui_config` JSON DEFAULT NULL, `sort_no` INT NOT NULL DEFAULT 0, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), `deleted_at` DATETIME(3) DEFAULT NULL, PRIMARY KEY (`id`), UNIQUE KEY `uk_meta_field_code` (`entity_id`,`field_code`), KEY `idx_meta_field_entity` (`tenant_id`,`entity_id`,`sort_no`)) ENGINE=InnoDB COMMENT='低代码实体字段';
CREATE TABLE `meta_view` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) NOT NULL, `entity_id` BINARY(16) DEFAULT NULL, `view_code` VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `view_name` VARCHAR(160) NOT NULL, `view_type` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'LIST', `config` JSON NOT NULL, `is_default` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'N', `status` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'A', `created_at` BINARY(16) DEFAULT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), `deleted_at` DATETIME(3) DEFAULT NULL, PRIMARY KEY (`id`), UNIQUE KEY `uk_meta_view_code` (`tenant_id`,`view_code`), KEY `idx_meta_view_entity` (`tenant_id`,`entity_id`,`view_type`)) ENGINE=InnoDB COMMENT='实体视图定义';
CREATE TABLE `meta_view_field` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) NOT NULL, `view_id` BINARY(16) NOT NULL, `field_id` BINARY(16) NOT NULL, `column_label` VARCHAR(160) DEFAULT NULL, `sort_no` INT NOT NULL DEFAULT 0, `is_visible` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'Y', `config` JSON DEFAULT NULL, PRIMARY KEY (`id`), UNIQUE KEY `uk_meta_view_field` (`view_id`,`field_id`), KEY `idx_meta_view_field_sort` (`tenant_id`,`view_id`,`sort_no`)) ENGINE=InnoDB COMMENT='视图字段配置';
CREATE TABLE `gen_project` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) NOT NULL, `project_code` VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `project_name` VARCHAR(160) NOT NULL, `template_id` BINARY(16) DEFAULT NULL, `entity_id` BINARY(16) DEFAULT NULL, `language_code` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'RUST', `framework_code` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL, `options` JSON DEFAULT NULL, `status` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'A', `created_at` BINARY(16) DEFAULT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), `deleted_at` DATETIME(3) DEFAULT NULL, PRIMARY KEY (`id`), UNIQUE KEY `uk_gen_project_code` (`tenant_id`,`project_code`), KEY `idx_gen_project_status` (`tenant_id`,`status`)) ENGINE=InnoDB COMMENT='统一代码生成项目';
CREATE TABLE `gen_template` (`id` BINARY(16) NOT NULL, `template_code` VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `template_name` VARCHAR(160) NOT NULL, `template_version` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `engine_code` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'MUSTACHE', `content` LONGTEXT NOT NULL, `checksum` BINARY(32) NOT NULL, `status` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'A', `created_at` BINARY(16) DEFAULT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), `deleted_at` DATETIME(3) DEFAULT NULL, PRIMARY KEY (`id`), UNIQUE KEY `uk_gen_template_version` (`template_code`,`template_version`), KEY `idx_gen_template_status` (`template_code`,`status`)) ENGINE=InnoDB COMMENT='代码生成模板';
CREATE TABLE `gen_artifact` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) NOT NULL, `project_id` BINARY(16) NOT NULL, `artifact_type` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `file_name` VARCHAR(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, `file_object_id` BINARY(16) DEFAULT NULL, `content_hash` BINARY(32) NOT NULL, `generation_no` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `status` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'S', `created_at` BINARY(16) DEFAULT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), PRIMARY KEY (`id`), UNIQUE KEY `uk_gen_artifact` (`project_id`,`generation_no`,`file_name`(191)), KEY `idx_gen_artifact_project` (`tenant_id`,`project_id`,`created_at`)) ENGINE=InnoDB COMMENT='代码生成产物';

-- 05. Forms and workflow
CREATE TABLE `flow_form` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) NOT NULL, `form_code` VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `form_name` VARCHAR(160) NOT NULL, `version_no` INT UNSIGNED NOT NULL DEFAULT 1, `schema_json` JSON NOT NULL, `status` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'A', `created_at` BINARY(16) DEFAULT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), `deleted_at` DATETIME(3) DEFAULT NULL, PRIMARY KEY (`id`), UNIQUE KEY `uk_flow_form_version` (`tenant_id`,`form_code`,`version_no`), KEY `idx_flow_form_status` (`tenant_id`,`status`)) ENGINE=InnoDB COMMENT='流程表单定义';
CREATE TABLE `flow_definition` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) NOT NULL, `flow_code` VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `flow_name` VARCHAR(160) NOT NULL, `current_version_id` BINARY(16) DEFAULT NULL, `status` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'A', `created_at` BINARY(16) DEFAULT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), `deleted_at` DATETIME(3) DEFAULT NULL, PRIMARY KEY (`id`), UNIQUE KEY `uk_flow_code` (`tenant_id`,`flow_code`), KEY `idx_flow_status` (`tenant_id`,`status`)) ENGINE=InnoDB COMMENT='流程定义主表';
CREATE TABLE `flow_definition_version` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) NOT NULL, `definition_id` BINARY(16) NOT NULL, `version_no` INT UNSIGNED NOT NULL, `definition_json` JSON NOT NULL, `checksum` BINARY(32) NOT NULL, `publish_status` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'D' COMMENT 'D draft, P published, R retired', `published_at` DATETIME(3) DEFAULT NULL, `created_at` BINARY(16) DEFAULT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), PRIMARY KEY (`id`), UNIQUE KEY `uk_flow_definition_version` (`definition_id`,`version_no`), KEY `idx_flow_version_status` (`tenant_id`,`publish_status`)) ENGINE=InnoDB COMMENT='不可变流程版本';
CREATE TABLE `flow_instance` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) NOT NULL, `enterprise_id` BINARY(16) DEFAULT NULL, `definition_version_id` BINARY(16) NOT NULL, `business_type` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `business_id` BINARY(16) NOT NULL, `business_no` VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL, `initiator_member_id` BINARY(16) NOT NULL, `instance_status` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'R' COMMENT 'R running, S success, F failed, C cancelled', `started_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `ended_at` DATETIME(3) DEFAULT NULL, `context` JSON DEFAULT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), PRIMARY KEY (`id`), KEY `idx_flow_instance_biz` (`tenant_id`,`business_type`,`business_id`), KEY `idx_flow_instance_status` (`tenant_id`,`instance_status`,`started_at`)) ENGINE=InnoDB COMMENT='流程实例';
CREATE TABLE `flow_task` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) NOT NULL, `instance_id` BINARY(16) NOT NULL, `node_code` VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `node_name` VARCHAR(160) NOT NULL, `task_status` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'P' COMMENT 'P pending, R running, S success, F failed, C cancelled', `assignee_member_id` BINARY(16) DEFAULT NULL, `candidate_rule` JSON DEFAULT NULL, `due_at` DATETIME(3) DEFAULT NULL, `claimed_at` DATETIME(3) DEFAULT NULL, `completed_at` DATETIME(3) DEFAULT NULL, `decision_code` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL, `comment_text` VARCHAR(2000) DEFAULT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), PRIMARY KEY (`id`), KEY `idx_flow_task_pending` (`tenant_id`,`task_status`,`assignee_member_id`,`due_at`), KEY `idx_flow_task_instance` (`instance_id`,`created_at`)) ENGINE=InnoDB COMMENT='流程人工/自动任务';
CREATE TABLE `flow_task_actor` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) NOT NULL, `task_id` BINARY(16) NOT NULL, `actor_kind` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'U user, R role, O org', `actor_id` BINARY(16) NOT NULL, `is_primary` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'N', `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), PRIMARY KEY (`id`), UNIQUE KEY `uk_flow_task_actor` (`task_id`,`actor_kind`,`actor_id`), KEY `idx_flow_actor` (`tenant_id`,`actor_kind`,`actor_id`)) ENGINE=InnoDB COMMENT='流程任务候选执行者';

-- 06. RPA, scheduler business layer and connectors
CREATE TABLE `rpa_node` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) NOT NULL, `node_code` VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `node_name` VARCHAR(160) NOT NULL, `agent_version` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL, `capabilities` JSON DEFAULT NULL, `status` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'I' COMMENT 'A online, I offline, D disabled', `last_heartbeat_at` DATETIME(3) DEFAULT NULL, `endpoint` VARCHAR(500) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), `deleted_at` DATETIME(3) DEFAULT NULL, PRIMARY KEY (`id`), UNIQUE KEY `uk_rpa_node_code` (`tenant_id`,`node_code`), KEY `idx_rpa_node_health` (`tenant_id`,`status`,`last_heartbeat_at`)) ENGINE=InnoDB COMMENT='RPA 执行节点';
CREATE TABLE `rpa_node_assignment` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) NOT NULL, `node_id` BINARY(16) NOT NULL, `org_unit_id` BINARY(16) DEFAULT NULL, `member_id` BINARY(16) DEFAULT NULL, `assignment_type` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'ALLOW', `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `deleted_at` DATETIME(3) DEFAULT NULL, PRIMARY KEY (`id`), KEY `idx_rpa_assignment_node` (`tenant_id`,`node_id`), KEY `idx_rpa_assignment_subject` (`tenant_id`,`org_unit_id`,`member_id`)) ENGINE=InnoDB COMMENT='RPA 节点授权';
CREATE TABLE `rpa_workflow` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) NOT NULL, `workflow_code` VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `workflow_name` VARCHAR(160) NOT NULL, `version_no` INT UNSIGNED NOT NULL DEFAULT 1, `definition_json` JSON NOT NULL, `status` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'A', `created_at` BINARY(16) DEFAULT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), `deleted_at` DATETIME(3) DEFAULT NULL, PRIMARY KEY (`id`), UNIQUE KEY `uk_rpa_workflow_version` (`tenant_id`,`workflow_code`,`version_no`), KEY `idx_rpa_workflow_status` (`tenant_id`,`status`)) ENGINE=InnoDB COMMENT='RPA 流程定义';
CREATE TABLE `rpa_job` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) NOT NULL, `job_code` VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `job_name` VARCHAR(160) NOT NULL, `workflow_id` BINARY(16) NOT NULL, `schedule_type` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'CRON', `schedule_expr` VARCHAR(255) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL, `misfire_policy` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'FIRE_ONCE', `status` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'A', `last_run_at` DATETIME(3) DEFAULT NULL, `next_run_at` DATETIME(3) DEFAULT NULL, `created_at` BINARY(16) DEFAULT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), `deleted_at` DATETIME(3) DEFAULT NULL, PRIMARY KEY (`id`), UNIQUE KEY `uk_rpa_job_code` (`tenant_id`,`job_code`), KEY `idx_rpa_job_schedule` (`status`,`next_run_at`), KEY `idx_rpa_job_tenant` (`tenant_id`,`status`)) ENGINE=InnoDB COMMENT='租户业务调度任务';
CREATE TABLE `rpa_job_run` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) NOT NULL, `job_id` BINARY(16) NOT NULL, `run_no` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `run_status` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'P' COMMENT 'P pending, R running, S success, F failed, C cancelled', `trigger_type` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'SCHEDULE', `node_id` BINARY(16) DEFAULT NULL, `attempt_no` INT UNSIGNED NOT NULL DEFAULT 0, `started_at` DATETIME(3) DEFAULT NULL, `ended_at` DATETIME(3) DEFAULT NULL, `input_data` JSON DEFAULT NULL, `output_data` JSON DEFAULT NULL, `error_text` VARCHAR(4000) DEFAULT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), PRIMARY KEY (`id`), UNIQUE KEY `uk_rpa_job_run_no` (`job_id`,`run_no`), KEY `idx_rpa_run_dispatch` (`tenant_id`,`run_status`,`created_at`), KEY `idx_rpa_run_job_time` (`job_id`,`created_at`)) ENGINE=InnoDB COMMENT='RPA 作业运行实例';
CREATE TABLE `connector_endpoint` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) NOT NULL, `endpoint_code` VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `endpoint_name` VARCHAR(160) NOT NULL, `protocol_code` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'FTP, SFTP, HTTP, DB, S3', `address` VARCHAR(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, `credential_ref` VARCHAR(255) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL, `status` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'A', `config` JSON DEFAULT NULL, `created_at` BINARY(16) DEFAULT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), `deleted_at` DATETIME(3) DEFAULT NULL, PRIMARY KEY (`id`), UNIQUE KEY `uk_endpoint_code` (`tenant_id`,`endpoint_code`), KEY `idx_endpoint_protocol` (`tenant_id`,`protocol_code`,`status`)) ENGINE=InnoDB COMMENT='外部连接端点';
CREATE TABLE `connector_task` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) NOT NULL, `task_code` VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `task_name` VARCHAR(160) NOT NULL, `source_endpoint_id` BINARY(16) NOT NULL, `target_endpoint_id` BINARY(16) DEFAULT NULL, `task_type` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'TRANSFER, SYNC, PROBE', `schedule_expr` VARCHAR(255) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL, `status` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'A', `config` JSON DEFAULT NULL, `created_at` BINARY(16) DEFAULT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), `deleted_at` DATETIME(3) DEFAULT NULL, PRIMARY KEY (`id`), UNIQUE KEY `uk_connector_task_code` (`tenant_id`,`task_code`), KEY `idx_connector_task_status` (`tenant_id`,`status`,`task_type`)) ENGINE=InnoDB COMMENT='文件/数据连接任务';
CREATE TABLE `connector_task_item` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) NOT NULL, `task_id` BINARY(16) NOT NULL, `item_no` INT UNSIGNED NOT NULL, `source_path` VARCHAR(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, `target_path` VARCHAR(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL, `item_status` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'P', `checksum` BINARY(32) DEFAULT NULL, `size_bytes` BIGINT UNSIGNED DEFAULT NULL, `error_text` VARCHAR(2000) DEFAULT NULL, `started_at` DATETIME(3) DEFAULT NULL, `ended_at` DATETIME(3) DEFAULT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), PRIMARY KEY (`id`), UNIQUE KEY `uk_connector_item_no` (`task_id`,`item_no`), KEY `idx_connector_item_status` (`tenant_id`,`item_status`,`created_at`)) ENGINE=InnoDB COMMENT='连接任务明细';

-- 07. Notifications
CREATE TABLE `notify_message` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) DEFAULT NULL, `message_type` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'SYSTEM', `title` VARCHAR(255) NOT NULL, `body` LONGTEXT NOT NULL, `payload` JSON DEFAULT NULL, `sender_id` BINARY(16) DEFAULT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `expires_at` DATETIME(3) DEFAULT NULL, PRIMARY KEY (`id`), KEY `idx_notify_message_time` (`tenant_id`,`created_at`)) ENGINE=InnoDB COMMENT='通知消息';
CREATE TABLE `notify_recipient` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) DEFAULT NULL, `message_id` BINARY(16) NOT NULL, `user_id` BINARY(16) NOT NULL, `delivery_channel` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'INBOX', `delivery_status` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'P', `read_at` DATETIME(3) DEFAULT NULL, `delivered_at` DATETIME(3) DEFAULT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), PRIMARY KEY (`id`), UNIQUE KEY `uk_notify_recipient` (`message_id`,`user_id`,`delivery_channel`), KEY `idx_notify_user` (`tenant_id`,`user_id`,`read_at`,`created_at`), KEY `idx_notify_delivery` (`delivery_status`,`created_at`)) ENGINE=InnoDB COMMENT='通知接收人';

-- 08. Expert alliance and knowledge graph
CREATE TABLE `ea_alliance` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) NOT NULL, `alliance_code` VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `alliance_name` VARCHAR(160) NOT NULL, `collaboration_mode` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'DYNAMIC' COMMENT 'PIPELINE, FANOUT, DEBATE, HIERARCHY, ITERATIVE, DYNAMIC', `fusion_strategy` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'WEIGHTED', `policy` JSON DEFAULT NULL, `status` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'A', `created_at` BINARY(16) DEFAULT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), `deleted_at` DATETIME(3) DEFAULT NULL, PRIMARY KEY (`id`), UNIQUE KEY `uk_ea_alliance_code` (`tenant_id`,`alliance_code`), KEY `idx_ea_alliance_status` (`tenant_id`,`status`)) ENGINE=InnoDB COMMENT='专家联盟';
CREATE TABLE `ea_expert` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) DEFAULT NULL, `expert_code` VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `expert_name` VARCHAR(160) NOT NULL, `expert_type` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'AGENT' COMMENT 'HUMAN, AGENT, SERVICE, SYSTEM', `provider_code` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL, `profile` JSON DEFAULT NULL, `quality_score` DECIMAL(8,6) NOT NULL DEFAULT 0, `status` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'A', `created_at` BINARY(16) DEFAULT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), `deleted_at` DATETIME(3) DEFAULT NULL, PRIMARY KEY (`id`), UNIQUE KEY `uk_ea_expert_code` (`tenant_id`,`expert_code`), KEY `idx_ea_expert_match` (`tenant_id`,`status`,`quality_score`)) ENGINE=InnoDB COMMENT='专家注册';
CREATE TABLE `ea_capability` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) DEFAULT NULL, `capability_code` VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `capability_name` VARCHAR(160) NOT NULL, `domain_code` VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL, `definition` JSON DEFAULT NULL, `status` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'A', `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), `deleted_at` DATETIME(3) DEFAULT NULL, PRIMARY KEY (`id`), UNIQUE KEY `uk_ea_capability_code` (`tenant_id`,`capability_code`), KEY `idx_ea_capability_domain` (`tenant_id`,`domain_code`,`status`)) ENGINE=InnoDB COMMENT='专家能力';
CREATE TABLE `ea_expert_capability` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) DEFAULT NULL, `expert_id` BINARY(16) NOT NULL, `capability_id` BINARY(16) NOT NULL, `proficiency` DECIMAL(8,6) NOT NULL DEFAULT 0, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `deleted_at` DATETIME(3) DEFAULT NULL, PRIMARY KEY (`id`), UNIQUE KEY `uk_ea_expert_capability` (`expert_id`,`capability_id`), KEY `idx_ea_capability_expert` (`tenant_id`,`capability_id`,`proficiency`)) ENGINE=InnoDB COMMENT='专家能力关系';
CREATE TABLE `ea_domain` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) DEFAULT NULL, `domain_code` VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `domain_name` VARCHAR(160) NOT NULL, `parent_id` BINARY(16) DEFAULT NULL, `path_key` VARCHAR(1000) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL, `status` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'A', `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), `deleted_at` DATETIME(3) DEFAULT NULL, PRIMARY KEY (`id`), UNIQUE KEY `uk_ea_domain_code` (`tenant_id`,`domain_code`), KEY `idx_ea_domain_parent` (`tenant_id`,`parent_id`)) ENGINE=InnoDB COMMENT='专家领域';
CREATE TABLE `ea_expert_domain` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) NOT NULL, `expert_id` BINARY(16) NOT NULL, `domain_id` BINARY(16) NOT NULL, `level_code` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'EXPERT', `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `deleted_at` DATETIME(3) DEFAULT NULL, PRIMARY KEY (`id`), UNIQUE KEY `uk_ea_expert_domain` (`expert_id`,`domain_id`), KEY `idx_ea_domain_expert` (`tenant_id`,`domain_id`,`level_code`)) ENGINE=InnoDB COMMENT='专家领域关系';
CREATE TABLE `ea_case` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) NOT NULL, `case_code` VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `title` VARCHAR(255) NOT NULL, `problem_text` LONGTEXT NOT NULL, `solution_text` LONGTEXT DEFAULT NULL, `quality_score` DECIMAL(8,6) DEFAULT NULL, `source_task_id` BINARY(16) DEFAULT NULL, `tags` JSON DEFAULT NULL, `status` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'A', `created_at` BINARY(16) DEFAULT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), `deleted_at` DATETIME(3) DEFAULT NULL, PRIMARY KEY (`id`), UNIQUE KEY `uk_ea_case_code` (`tenant_id`,`case_code`), KEY `idx_ea_case_quality` (`tenant_id`,`status`,`quality_score`)) ENGINE=InnoDB COMMENT='专家协作案例';
CREATE TABLE `ea_task` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) NOT NULL, `alliance_id` BINARY(16) NOT NULL, `task_no` VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `title` VARCHAR(255) NOT NULL, `input_data` JSON NOT NULL, `task_status` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'P', `initiator_member_id` BINARY(16) NOT NULL, `started_at` DATETIME(3) DEFAULT NULL, `ended_at` DATETIME(3) DEFAULT NULL, `result_data` JSON DEFAULT NULL, `error_text` VARCHAR(4000) DEFAULT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), PRIMARY KEY (`id`), UNIQUE KEY `uk_ea_task_no` (`tenant_id`,`task_no`), KEY `idx_ea_task_dispatch` (`tenant_id`,`task_status`,`created_at`), KEY `idx_ea_task_alliance` (`alliance_id`,`created_at`)) ENGINE=InnoDB COMMENT='专家联盟协作任务';
CREATE TABLE `ea_task_node` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) NOT NULL, `task_id` BINARY(16) NOT NULL, `node_code` VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `expert_id` BINARY(16) DEFAULT NULL, `node_type` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'EXECUTE' COMMENT 'EXECUTE, CONDITION, FUSION, HUMAN', `node_status` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'P', `input_data` JSON DEFAULT NULL, `output_data` JSON DEFAULT NULL, `attempt_no` INT UNSIGNED NOT NULL DEFAULT 0, `started_at` DATETIME(3) DEFAULT NULL, `ended_at` DATETIME(3) DEFAULT NULL, `error_text` VARCHAR(4000) DEFAULT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), PRIMARY KEY (`id`), UNIQUE KEY `uk_ea_task_node` (`task_id`,`node_code`), KEY `idx_ea_node_dispatch` (`tenant_id`,`node_status`,`created_at`), KEY `idx_ea_node_task` (`task_id`)) ENGINE=InnoDB COMMENT='联盟任务执行节点';
CREATE TABLE `ea_task_edge` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) NOT NULL, `task_id` BINARY(16) NOT NULL, `from_node_id` BINARY(16) NOT NULL, `to_node_id` BINARY(16) NOT NULL, `condition_expr` JSON DEFAULT NULL, `data_mapping` JSON DEFAULT NULL, PRIMARY KEY (`id`), UNIQUE KEY `uk_ea_task_edge` (`task_id`,`from_node_id`,`to_node_id`), KEY `idx_ea_edge_to` (`task_id`,`to_node_id`), KEY `idx_ea_edge_from` (`task_id`,`from_node_id`)) ENGINE=InnoDB COMMENT='联盟任务 DAG 边';
CREATE TABLE `ea_task_result` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) NOT NULL, `task_id` BINARY(16) NOT NULL, `result_type` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'FINAL', `result_data` JSON NOT NULL, `quality_score` DECIMAL(8,6) DEFAULT NULL, `is_final` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'N', `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), PRIMARY KEY (`id`), KEY `idx_ea_result_task` (`tenant_id`,`task_id`,`is_final`,`created_at`)) ENGINE=InnoDB COMMENT='联盟任务结果';

CREATE TABLE `kg_graph` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) NOT NULL, `graph_code` VARCHAR(96) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `graph_name` VARCHAR(160) NOT NULL, `ontology_version` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL, `backend_code` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'ROCKSDB', `status` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'A', `created_at` BINARY(16) DEFAULT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), `deleted_at` DATETIME(3) DEFAULT NULL, PRIMARY KEY (`id`), UNIQUE KEY `uk_kg_graph_code` (`tenant_id`,`graph_code`), KEY `idx_kg_graph_status` (`tenant_id`,`status`)) ENGINE=InnoDB COMMENT='知识图谱索引元数据';
CREATE TABLE `kg_entity` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) NOT NULL, `graph_id` BINARY(16) NOT NULL, `entity_type` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `entity_key` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, `label` VARCHAR(255) NOT NULL, `properties` JSON DEFAULT NULL, `source_ref` VARCHAR(255) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL, `embedding_ref` VARCHAR(255) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), `deleted_at` DATETIME(3) DEFAULT NULL, PRIMARY KEY (`id`), UNIQUE KEY `uk_kg_entity_key` (`graph_id`,`entity_type`,`entity_key`), KEY `idx_kg_entity_type` (`tenant_id`,`graph_id`,`entity_type`,`updated_at`)) ENGINE=InnoDB COMMENT='知识图谱实体索引';
CREATE TABLE `kg_relation` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) NOT NULL, `graph_id` BINARY(16) NOT NULL, `from_entity_id` BINARY(16) NOT NULL, `relation_type` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `to_entity_id` BINARY(16) NOT NULL, `properties` JSON DEFAULT NULL, `confidence` DECIMAL(8,6) DEFAULT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `deleted_at` DATETIME(3) DEFAULT NULL, PRIMARY KEY (`id`), UNIQUE KEY `uk_kg_relation` (`graph_id`,`from_entity_id`,`relation_type`,`to_entity_id`), KEY `idx_kg_relation_from` (`tenant_id`,`graph_id`,`from_entity_id`,`relation_type`), KEY `idx_kg_relation_to` (`tenant_id`,`graph_id`,`to_entity_id`,`relation_type`)) ENGINE=InnoDB COMMENT='知识图谱关系';

-- 09. AI provider, model and run trace
CREATE TABLE `ai_provider` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) DEFAULT NULL, `provider_code` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `provider_name` VARCHAR(120) NOT NULL, `endpoint` VARCHAR(500) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `credential_ref` VARCHAR(255) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `status` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'A', `config` JSON DEFAULT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), `deleted_at` DATETIME(3) DEFAULT NULL, PRIMARY KEY (`id`), UNIQUE KEY `uk_ai_provider_code` (`tenant_id`,`provider_code`), KEY `idx_ai_provider_status` (`tenant_id`,`status`)) ENGINE=InnoDB COMMENT='AI 模型供应商';
CREATE TABLE `ai_model` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) DEFAULT NULL, `provider_id` BINARY(16) NOT NULL, `model_code` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `model_type` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'CHAT' COMMENT 'CHAT, EMBED, RERANK, IMAGE, AUDIO', `capabilities` JSON DEFAULT NULL, `context_limit` INT UNSIGNED DEFAULT NULL, `unit_price_input` DECIMAL(18,8) DEFAULT NULL, `unit_price_output` DECIMAL(18,8) DEFAULT NULL, `status` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'A', `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), `deleted_at` DATETIME(3) DEFAULT NULL, PRIMARY KEY (`id`), UNIQUE KEY `uk_ai_model_code` (`tenant_id`,`model_code`), KEY `idx_ai_model_provider` (`tenant_id`,`provider_id`,`status`)) ENGINE=InnoDB COMMENT='AI 模型';
CREATE TABLE `ai_run` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) NOT NULL, `task_id` BINARY(16) DEFAULT NULL, `model_id` BINARY(16) NOT NULL, `run_type` VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'CHAT', `run_status` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'P', `request_hash` BINARY(32) DEFAULT NULL, `input_tokens` INT UNSIGNED DEFAULT NULL, `output_tokens` INT UNSIGNED DEFAULT NULL, `cost_amount` DECIMAL(18,8) DEFAULT NULL, `started_at` DATETIME(3) DEFAULT NULL, `ended_at` DATETIME(3) DEFAULT NULL, `error_text` VARCHAR(4000) DEFAULT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), PRIMARY KEY (`id`), KEY `idx_ai_run_task` (`tenant_id`,`task_id`,`created_at`), KEY `idx_ai_run_status` (`tenant_id`,`run_status`,`created_at`), KEY `idx_ai_run_model` (`model_id`,`created_at`)) ENGINE=InnoDB COMMENT='AI 调用运行记录';
CREATE TABLE `ai_message` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) NOT NULL, `run_id` BINARY(16) NOT NULL, `seq_no` INT UNSIGNED NOT NULL, `role_code` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'SYSTEM, USER, ASSISTANT, TOOL', `content_text` LONGTEXT DEFAULT NULL, `content_json` JSON DEFAULT NULL, `token_count` INT UNSIGNED DEFAULT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), PRIMARY KEY (`id`), UNIQUE KEY `uk_ai_message_seq` (`run_id`,`seq_no`), KEY `idx_ai_message_run` (`tenant_id`,`run_id`,`seq_no`)) ENGINE=InnoDB COMMENT='AI 对话消息';
CREATE TABLE `ai_tool_call` (`id` BINARY(16) NOT NULL, `tenant_id` BINARY(16) NOT NULL, `run_id` BINARY(16) NOT NULL, `message_id` BINARY(16) DEFAULT NULL, `tool_code` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, `arguments` JSON DEFAULT NULL, `result_data` JSON DEFAULT NULL, `call_status` CHAR(1) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'P', `started_at` DATETIME(3) DEFAULT NULL, `ended_at` DATETIME(3) DEFAULT NULL, `error_text` VARCHAR(4000) DEFAULT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), PRIMARY KEY (`id`), KEY `idx_ai_tool_run` (`tenant_id`,`run_id`,`created_at`), KEY `idx_ai_tool_status` (`tenant_id`,`call_status`,`created_at`)) ENGINE=InnoDB COMMENT='AI 工具调用轨迹';

-- End of baseline. QRTZ_* is installed separately from the official Quartz script.
