[package]
name = "mox-ai-agent-svc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
mox-platform-foundation = { path = "../../../foundation/mox-platform-foundation" }
mox-ai-api = { path = "../../../api/mox-ai-api" }
mox-ai-core = { path = "../../../core/ai/mox-ai-core" }
mox-ai-expert-svc = { path = "../mox-ai-expert-svc" }
async-trait = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]



