[package]
name = "mox-flow-primiflow-svc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
mox-platform-foundation = { path = "../../../foundation/mox-platform-foundation" }
mox-flow-api = { path = "../../../api/mox-flow-api" }
mox-flow-operator-core = { path = "../../../core/flow/mox-flow-operator-core" }
mox-flow-optimizer-core = { path = "../../../core/flow/mox-flow-optimizer-core" }
async-trait = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]


